### ISSUE TITLE
Signing commits via GPG

### ISSUE THREAD

**Issue by PHPoenX** [Gedsh/InviZible#1]
Hi!

Why you dont sign your commits?

**Comment by Gedsh** [comment]
OK. I think it is a good idea. I will begin.

**Comment by PHPoenX** [comment]
@Gedsh Can you upload your public signing key?

**Comment by Gedsh** [comment]
Uploaded already. You can not find its?

**Comment by PHPoenX** [comment]
@Gedsh Yes, I can`t

**Comment by Gedsh** [comment]
I don't know why are you have problems:
`
C:\>gpg --search Garmatin Oleksandr
gpg: data source: https://192.146.137.98:443
(1)     Oleksandr Garmatin <invizible.soft@gmail.com>
          4096 bit RSA key 8E5B96176B1A3A1D,      создан: 2019-08-08,    годен до: 2025-08-08
`
