### ISSUE TITLE
Replace Stericson busybox with meefik

### ISSUE THREAD

**Issue by MF-Debug** [Gedsh/InviZible#10]
Stericson busybox is outdated afaik. it would be better to replace in-app busybox with [meefik's](https://github.com/meefik/busybox)!

**Comment by Gedsh** [comment]
InviZible uses the internal busybox if external does not exist. And usually these are very simple commands. But there is no problem to replace. I will do it for the next beta.

**Comment by drogga3** [comment]
else this is a good candidate: https://github.com/Magisk-Modules-Repo/busybox-ndk
