### ISSUE TITLE
dns bootstrap

### ISSUE THREAD

**Issue by linsui** [Gedsh/InviZible#102]
The dnscrypt-proxy downloads lists from github and dnscrypt.info on start. But it can't resolve the domain.  Could it bootstrap with a encrypted dns? Thanks!

**Comment by Gedsh** [comment]
>  it can't resolve the domain

DNSCrypt uses bootstrap_resolvers to download the server list. Thus, you can configure it to the resolver accessible in your country.

> Could it bootstrap with a encrypted dns?

I think no. But I think it would be nice to ask the DNSCrypt developer directly. This is a good thing to implement if possible..

**Comment by linsui** [comment]
Yes, the problem is that I need an encrypted dns to get a correct result. Hosts from that also works since only two domains are needed. Is that possible? I'll also report upstream.

**Comment by linsui** [comment]
I'm going to use a proxy which resolve the dns to a hosts.

> You can try configuring DNSCrypt to use a Tor proxy. But I'm not sure if DNSCrypt is using proxy for bootstrapping.

Unfortunately it's more difficult to make tor work.

I thought this should be resolved upstream. Thanks!
