### ISSUE TITLE
DNS Leaking over plain DNS

### ISSUE THREAD

**Issue by Generator** [Gedsh/InviZible#104]
## Description
I have "AdGuard Home" as DoH server (with [DNS Stamps](https://dnscrypt.info/stamps/)) and main DNS server on LAN, all traffic coming from DoH shows the gateway IP (10.0.0.1), however some DNS records are leaking over plain DNS.

Ignore PTR record (```.in-addr.arpa```), ```.lan``` , ```dns.adguard.com``` and ```connectivitycheck.grapheneos.network```
![Screenshot 2021-10-21 at 21-32-35 AdGuard Home](https://user-images.githubusercontent.com/44146/138353018-2173e98d-bd61-445f-8136-a19fe86e17d0.png)

I've already had blocked ```1e100.net``` but there's other domains leaking, like Facebook (fbcdn.net), Amazon (.compute.amazonaws.com), Google (.googleusercontent.com) and others.

InviZible Pro is always on, its leaking when changing/connecting to networks.

**Comment by Gedsh** [comment]
>  its leaking when changing/connecting to networks

If you don't have DHCP on your local network and 10.0.0.70 is always your phone with InviZible, it can only mean that your phone temporarily disables VPN when switching networks. There are two solutions. Enable Always On VPN and Block connections without VPN in Android settings. If that doesn't help, the only way is to use Root mode for rooted device. In Root mode, the leak is prevented at the kernel level.
