### ISSUE TITLE
No DNS logs when using Root Mode

### ISSUE THREAD

**Issue by Generator** [Gedsh/InviZible#105]
## Description
When using 'Root Mode' DNS log show only what server is connect, system/apps without connections log
![Screenshot-2021-10-22-12-13-22](https://user-images.githubusercontent.com/44146/138444808-6f020ebc-3c94-4a5c-ba9e-7d6716667911.jpeg)

DNS logs are useful to see what (apps) is connecting to what.

**Comment by Gedsh** [comment]
Implemented in InviZible Pro beta 1.6.5
