### ISSUE TITLE
all dnscrypt config options. one by one.

### ISSUE THREAD

**Issue by DI555** [Gedsh/InviZible#11]
i want to thank the dev about IZ, this is really Great!
and pls pardon me for not posted just one little config option in the issue, let this issue be global about config options.
So let the writers post options here one by one.
And many thanks to the dev for keeping in IZ the sort order of config options according to dnscrypt's sample config file:
github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

**Comment by DI555** [comment]
the most avated one is the doh local server config:



##################################
#        Local DoH server        #
##################################

[local_doh]

## dnscrypt-proxy can act as a local DoH server. By doing so, web browsers
## requiring a direct connection to a DoH server in order to enable some
## features will enable these, without bypassing your DNS proxy.

## Addresses that the local DoH server should listen to

# listen_addresses = ['127.0.0.1:3000']


## Path of the DoH URL. This is not a file, but the part after the hostname
## in the URL. By convention, `/dns-query` is frequently chosen.
## For each `listen_address` the complete URL to access the server will be:
## `https://<listen_address><path>` (ex: `https://127.0.0.1/dns-query`)

# path = "/dns-query"


## Certificate file and key - Note that the certificate has to be trusted.
## See the documentation (wiki) for more information.

# cert_file = "localhost.pem"
# cert_key_file = "localhost.pem"

**Comment by Gedsh** [comment]
> the most awaited one is the doh local server config

OK. It's not a problem. Perhaps this feature will be added in the next beta.

**Comment by DI555** [comment]
many thanks for that!!!
and may be another one that can much speed up the browsing !!!
it's a local dns cache:



###########################
         DNS cache        #
###########################

   Enable a DNS cache to reduce latency and outgoing traffic

cache = true


   Cache size

cache_size = 1024


   Minimum TTL for cached entries

cache_min_ttl = 2400


   Maximum TTL for cached entries

cache_max_ttl = 86400


   Minimum TTL for negatively cached entries

cache_neg_min_ttl = 60


   Maximum TTL for negatively cached entries

cache_neg_max_ttl = 600



#############################

**Comment by Gedsh** [comment]
> many thanks for that!!!

You are welcome.

> local dns cache:

Already in use. I see no sense to change this option in the settings. You can see all the parameters used in the file /data/data/pan.alexander.tordnscrypt/app_data/dnscrypt-proxy/dnscrypt-proxy.toml

**Comment by DI555** [comment]
yes, i'm guided that file, but i think that maybe not all but the main parameters must be in ui, - for example great to be to set amount of that cache, and switch it on or off :

___________________________________________________________
**Enable a DNS cache to reduce latency and outgoing traffic

cache = true ( just a visual switch )

**Cache size

cache_size = 1024
_____________________________________________________________

**Comment by Gedsh** [comment]
>  set amount of that cache, and switch it on or off 

How often do you change the cache size and turn it on and off? 
And what is the reason to change its default values? Please explain. I have never touched it.

**Comment by DI555** [comment]
i mean each other wants to configurate this by ownself!
for me it's qite good would be set it to much amount, just to be possible not to ping dnscrypt server by a days ;) !!!
and take some experiments on tha value for optimal time for resolving dnd...
for other reasons even could be switch it off, ...for example if browser's dns cach is on and just to use it ...
So it's very needed option, end even to change it many times.

**Comment by Gedsh** [comment]
> i mean each other wants to configurate this by ownself!

This is very rare, in my opinion.

> take some experiments on that value for optimal time for resolving dns

> for example if browser's dns cach is on and just to use it ... or for reasons to make minimum lags for pipelining write to server in a realtime...

Oh, usually nobody play with this. But I am planing to add "open config file" option. There you can change all the parameters in a text editor. I think this is better for people who like experiments.

**Comment by DI555** [comment]
wow, it's grait! i'm only planning to write about that !!!
than, please, add 'open config file' option 3 times for each instances of modules, - dnscrypt, tor and i2p !!!

**Comment by DI555** [comment]
but nevertheless , those 2 dns cache options are quite good !!!
just remember how it used to be when we was tuning our browsers with browser's chache some time ago when internet speed was much slow !!!

**Comment by Gedsh** [comment]
> please, add 'open config file' option 3 times for each instances of modules, - dnscrypt, tor and i2p !!!

OK.

> just remember how it used to be when we was tuning our browsers with browser's chache some time ago when internet speed was much slow !!!

It's in the past :)

**Comment by Gedsh** [comment]
Added edit configuration files options in beta version 0.7.2.
