### ISSUE TITLE
Force restart when using root mode

### ISSUE THREAD

**Issue by mahdi921** [Gedsh/InviZible#113]
Hello. I'm on Android 11 and whenever I try to start any of the modules with root mode the whole android crashes and restarts. When I get back to the app afterwards it says that android has blocked connectivity to the internet so we restored it back check the phone settings; which is confusing. I haven't been able to get around this with anything that came in my mind and there's no one reporting this issue.

**Comment by Gedsh** [comment]
Hello. In root mode, InviZible uses root only to change iptables rules. You can try using your device iptables: Menu -> Common Settings -> Select Iptables -> Use Device Iptables. You can also play around with busybox settings.

**Comment by mahdi921** [comment]
Yo changing iptables settings to device iptables resolved the issue. Thank you. Closing this.
