### ISSUE TITLE
win builds

### ISSUE THREAD

**Issue by DI555** [Gedsh/InviZible#115]
now and for windows there are no suitable gui for tor, dnscrypt and i2p ((
could it be possible build and windows IZ versions too, please ?

**Comment by Gedsh** [comment]
Unfortunately this is impossible. InviZible uses specific features of Android and its Linux kernel. For Windows, it is required to develop an application from scratch.

**Comment by DI555** [comment]
i thought that if it's java, - possible to build IZ just like java app, for windows and linux..

**Comment by Gedsh** [comment]
> i thought that if it's java

The core features of InviZible are written in C. DNSCrypt is written in Golang. Tor and Purple I2P are written in C ++. Even the InviZible java code is highly platform dependent and cannot be used on platforms other than Android.
