### ISSUE TITLE
[Feature Request] DNS User filter   and  filtering rules syntax

### ISSUE THREAD

**Issue by Pantyhose-X** [Gedsh/InviZible#116]
- `||example.org^` - block access to the example.org domain and all its subdomains
- `||*.example^`- block access All prefixes  to domains  `.example`
- `||example.*^`- block access All suffixes to domains  `example.`
- `||*example*^`- block access All prefixes, midfixes, suffixes
- `@@||*example.org*^` - unblock access to the example.org domain and all its subdomains
- `0.0.0.0 example.org` - will now return 0.0.0.0 address for the example.org domain (but not its subdomains). Other IP 

ip range rules syntax `" "`  `*`
- `"0.0.0.0/24"` -block access to ip range   domains  `0.0.0.0/24`
- `"0.0.0.*"` -block access to  ip range Incremental domains  `0.0.0.*` 
-  `"0.0.0.0"` -block access to all domains whose CNAME response returns this IP address

**Comment by Pantyhose-X** [comment]
RENAME
rename pattern-based baocking (blacklist)
rename pattern-based whitelisting (blacklists bypass)
rename pattern-based IP blocking (IP blacklist)

Use integrated Editor

**Comment by Gedsh** [comment]
InviZible uses DNSCrypt for DNS handling. Therefore, you should ask the DNSCrypt developer to add this feature. I can not do it.
https://github.com/DNSCrypt/dnscrypt-proxy

You can also use the syntax already available https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters

**Comment by Pantyhose-X** [comment]
> InviZible uses DNSCrypt for DNS handling. Therefore, you should ask the DNSCrypt developer to add this feature. I can not do it. https://github.com/DNSCrypt/dnscrypt-proxy
> 
> You can also use the syntax already available https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters


vpn mode 
Similar to adguard dns filters
![images](https://cdn.adguard.com/public/Adguard/Release_notes/Android/v3.2/dnsfilter.gif)
