### ISSUE TITLE
Problems when using "croc" file transfer application.

### ISSUE THREAD

**Issue by tuqueque** [Gedsh/InviZible#117]
Hello... First of all, this is a fantastic program! ...I recommend it to anyone I can and I'll donate to it next year, when I hope to be in a better situation regarding money.

Now, my problem...

I've been testing the (also fantastic... and open source) croc file transfer application (for PC: https://github.com/schollz/croc and for Android: https://f-droid.org/en/packages/com.github.howeyc.crocgui/ ), but when I try to transfer a file (from my PC to my phone) large enough, it throws an error midway...

I tried several times and is always the same, the Android version of croc closes in my phone and in my PC I get an error... I even tried using croc in my phone through Termux and it also throws an error... Then, I closed Invizible, and everything went smoothly.

When croc closes in my phone, my PC throws one of these two errors (I X-ed my IP addresses just out of caution):

This one:
```
Sending (->xxx.xxx.x.xxx:48098)
  33% |██████              | (232/700 MB, 1.490 MB/s) [2m31s:5m13s]2021/12/16 18:03:06 EOF
```

Or this one:
```
Sending (->xxx.xxx.x.xxx:48126)
  70% |██████████████      | (496/700 MB, 2.271 MB/s) [2m30s:1m29s]
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9010->xxx.xxx.x.xxx:51614: write: connection reset by peer
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9010->xxx.xxx.x.xxx:51614: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9010->xxx.xxx.x.xxx:51614: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9013->xxx.xxx.x.xxx:34586: write: connection reset by peer
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9013->xxx.xxx.x.xxx:34586: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9013->xxx.xxx.x.xxx:34586: write: broken pipe
[error]	2021/12/16 18:06:53 tcp.go:407: write error on channel 2: write tcp4 xxx.xxx.x.xxx:9011->xxx.xxx.x.xxx:55848: write: connection reset by peer
panic: connection.Write failed: write tcp 127.0.0.1:42540->127.0.0.1:9010: write: connection reset by peer

goroutine 97 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).sendData(0xc000178400, 0x0)
	github.com/schollz/croc/v9/src/croc/croc.go:1598 +0x6fb
created by github.com/schollz/croc/v9/src/croc.(*Client).updateState
	github.com/schollz/croc/v9/src/croc/croc.go:1428 +0x6cb
```
EDIT:
Now that I notice... croc fails in my phone after 2:30 minutes after I begin every download... so hopefully, that gives you a hint of what might be happening... Just in case, I just posted a bug report in croc's Github page to make sure is not croc's fault.

Thank you very much!

**Comment by Gedsh** [comment]
Hello, Thank you!

Try to enable Bypass LAN addresses in Fast Settings.

**Comment by tuqueque** [comment]
Hey, thanks for the reply...

Nope, it didn't work... I should have explained that while I did enable TOR and DNScrypt-Proxy on InviZible, I also excluded croc (and some other apps) from using TOR in the Fast Settings section (a great option to have, I must say).

Any other ideas?

**Comment by Gedsh** [comment]
> Any other ideas?

If you are using firewall in InviZible, you should enable LAN for croc. Or better to temporarily disable the firewall.

If that doesn't work, I'll need to take the time to test the croc app myself.

**Comment by tuqueque** [comment]
Nope, I'm not using the firewall feature of InviZible... So yes, I'll suggest you to test the croc app for yourself. It's a rather straightforward app to use, so it shouldn't take too long to do the testing.

**Comment by Gedsh** [comment]
I checked croc and there are no problems with small files. Unfortunately, now I have absolutely no time to test gigabyte files. Sorry.

Maybe later I will have more time.

**Comment by tuqueque** [comment]
> I checked croc and there are no problems with small files. Unfortunately, now I have absolutely no time to test gigabyte files. Sorry.
> 
> Maybe later I will have more time.

Yes, as I said, if the file is transferred in less than 2:30 minutes, everything goes fine, but when the file takes more than that (big files), that's when I get the problem.

I hope next year you have time to test it properly. Thank you very much and happy new year!
