### ISSUE TITLE
DNSCrypt and LAN connectivity issues.

### ISSUE THREAD

**Issue by Git-Forked** [Gedsh/InviZible#119]
Using only the DNSCrypt, and firewall; (not tor or ip2)
I have been using this app for over a year with mostly great experiences.
I have some issues with certain apps not being able to communicate over the LAN. 
A specific app that has issues is "KDE Connect". 
I have enabled LAN for it in the firewall. 
When DNSCrypt is activated "KDE Connect" cannot reach my Linux computer on the same LAN.
And When DNSCrypt is deactivated "KDE Connect" connects in less than a second.

**Comment by Gedsh** [comment]
Please try the new beta version 1.4.6 or enable MENU -> Fast Settings -> Bypass LAN addresses.

Also make sure you have allowed LAN in the firewall for the appropriate applications.

**Comment by Git-Forked** [comment]
> Please try the new beta version 1.4.6 

I'll try it.

> or enable MENU -> Fast Settings -> Bypass LAN addresses.

Bypass LAN claims it is only for TOR connections, however it was already enabled anyways. 

> Also make sure you have allowed LAN in the firewall for the appropriate applications.

Line 5 of my first statement says "I have enabled LAN for it in the firewall."

**Comment by Git-Forked** [comment]
Beta version you suggested does not work at all for me.  When I press the "START" button it just keeps showing a popup/toast "VPN mode is off", however it is selected as the active in the 3 dot menu.  I cannot proceed past this point to do further testing.

**Comment by Generator** [comment]
Try adding forward rules on DNSCrypt settings
`192.in-addr.arpa 192.168.1.1`

Or equivalent to your network

**Comment by Git-Forked** [comment]
> Try adding forward rules on DNSCrypt settings `192.in-addr.arpa 192.168.1.1`
> 
> Or equivalent to your network

Tried that before you ever suggested it, and it does not help the issue.

**Comment by Gedsh** [comment]
> Beta version you suggested does not work at all for me.

Please try the new beta version 1.4.8. If you run into similar problems, you can try restarting your phone.

As for KDE Connect, I cannot test it on my PC as I am using Linux Mint with Cinnamon and I don't want to install KDE. But I have feedback that on version 1.4.6 KDE Connect works fine.

**Comment by Generator** [comment]
@Git-Forked adding the hostnames on KDEConnec on the app settings might help (ex: desktop.lan)

@Gedsh you don't need to install the whole DE, but requires some dependencies from KDE. 
I use it on XFCE

**Comment by Gedsh** [comment]
> you don't need to install the whole DE, but requires some dependencies from KDE

I know. But this is actually about 85% of KDE. I use a PC for development, so I don't want to experiment with its stability.

**Comment by Git-Forked** [comment]
> @Git-Forked adding the hostnames on KDEConnec on the app settings might help (ex: desktop.lan) I also was having issues with KDEConnect and "Block connections without VPN" enabled on any pVPN app, adding hostnames instead of IP scan fixes the issue.

No luck with that for me.  Thanks for offering suggestions though.

**Comment by Git-Forked** [comment]
> > Beta version you suggested does not work at all for me.
> 
> Please try the new beta version 1.4.9. If you run into similar problems, you can try restarting your phone.
> 
> As for KDE Connect, I cannot test it on my PC as I am using Linux Mint with Cinnamon and I don't want to install KDE. But I have feedback that on version 1.4.6 KDE Connect works fine.

@Gedsh 
When will these beta changes roll out to F-Droid repository?

**Comment by Gedsh** [comment]
> When will these beta changes roll out to F-Droid repository?

With stable version. I don't know the exact date. When the beta becomes stable enough.

**Comment by Git-Forked** [comment]
Just updated to the 5.6.0 version from F-Droid, and it still KDE Connect and Linksys router app do not have connectivity to the LAN.

**Comment by awebeer256** [comment]
> Try adding forward rules on DNSCrypt settings
> `192.in-addr.arpa 192.168.1.1`
> Or equivalent to your network

And how am I supposed to figure out what the equivalent for my network is? Is it supposed to be the default gateway? What if I want it to work on multiple Wi-Fi networks?

 >As for KDE Connect, I cannot test it on my PC as I am using Linux Mint with Cinnamon and I don't want to install KDE. But I have feedback that on version 1.4.6 KDE Connect works fine.

Just run Kubuntu in a live session 😒.

> I also was having issues with KDEConnect and "Block connections without VPN" enabled on any pVPN app, adding hostnames instead of IP scan fixes the issue.

When I added the hostname, InviZible started logging the hostname in red, which I think means it blocked the DNS query.

**Comment by Generator** [comment]
And how am I supposed to figure out what the equivalent for my network is? Is it supposed to be the default gateway? What if I want it to work on multiple Wi-Fi networks?

Its your router DNS server, on android settings check the info of your WiFi network and there's DNS, gateway, subnet etc...

If your network is 10.0.0.x and DNS server 10.0.0.1 then set ```10.in-addr.arpa 10.0.0.1```

**Comment by Gedsh** [comment]
> Just run Kubuntu in a live session

Unfortunately, I do not currently have time for such tests.

**Comment by Git-Forked** [comment]
Another app affected is Warpinator. 
Warpinator cannot see other devices running Warpinator over the LAN.

Suggested fixes do not resolve it: 

1.  Bypass LAN
2.  192.in-addr.arpa 192.168.1.1
