### ISSUE TITLE
No systemless/Magisk support.

### ISSUE THREAD

**Issue by drogga3** [Gedsh/InviZible#12]
Currently, installation of InviZible requires writing to /system, for some this can be seen as undesireable, because it may break dm-verity, and makes restoring device to stock longer as the entire /system partition must be rewritten, instead of just boot partition for the majority of Magisk installation in order to restore to stock.

Currently, a recently updated dnscrypt-proxy2 Magisk module is available: https://github.com/Magisk-Modules-Repo/dnscrypt-proxy2

**Comment by Gedsh** [comment]
> Currently, installation of InviZible requires writing to /system

Why do you think so? You are wrong! InviZible never writes anything to /system and can be used completely without root privileges. Read the project's wiki.

> updated dnscrypt-proxy2 Magisk module is available

Everyone uses tools for their own purposes. The Magisk module is good, but InviZible can do march more things.

**Comment by drogga3** [comment]
Ouch, ouch, sorry for assuming things. If I use the root installation, where does it write? It's own /data?

**Comment by Gedsh** [comment]
> If I use the root installation

InviZible does not use root for an installation.

> where does it write? It's own /data?

Yes.

> Root is used to start binaries on own app /data as PID 0

This is just the option. Root is mainly required for modifying iptables rules to redirect internet traffic to InviZible modules.
