### ISSUE TITLE
Question: firewall + pDNSf + InviziblePro

### ISSUE THREAD

**Issue by Horizonbli** [Gedsh/InviZible#121]
I went ahead and set up a firewall + personalDNSfilter + InviziblePro, following the guides on your website.

Considering that the firewall will be forwarding connections to pDNSfilter, DNSCrypt (InviziblePro) blacklisting won't work, at all. Only pDNSfiler filters and blocks, if rules are set. Unless I am missing something.

Now, and I got no idea whether or not something like this is possible, but would there be a way to have both pDNSfilter and InviziblePro, in this case, have some sort of interoperability, so that users could benefit from blocking features from both apps?

Most likely isnt't possible, at all, but doesn't hurt to ask.

Thanks

Thanks

**Comment by Horizonbli** [comment]
Update:

After analysing pdnsf log, I found one entry refereeing that a DNS query had been blocked by dnscrypt-proxy. So, I disabled all filters from pdnsf, and tested dnscrypt blacklisting again. It wasn 't working. That was odd. So I thought of deleting InviziblePro cache and data and start from scratch.
Then, I got both pdnsf and inviziblepro working together.

DNS queries blocked by dnscrypt appear in pdnsf in green color. A bit confusing. I wish there was a way for pdnsf to know that the DNS query had been blocked by dnscrypt and show it in orange colour, so that we know dnscrypt blacklisting is working and differ from pdnsf own blocking.

One thing is for sure: great news that both blacklisting works and that I was wrong. Hope it wont fail again.

**Comment by Gedsh** [comment]
> Now, and I got no idea whether or not something like this is possible, but would there be a way to have both pDNSfilter and InviziblePro, in this case, have some sort of interoperability

They should work together seamlessly.

> DNS queries blocked by dnscrypt appear in pdnsf in green color. A bit confusing.

DNSCrypt responds HINFO when blocking a domain. So perhaps pDNSf thinks it is not blocked.
You can try playing around with block_query_response as described here: https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

>  I wish there was a way for pdnsf to know that the DNS query had been blocked by dnscrypt and show it in orange colour

I think you should ask the pDNSf developer about this. I haven't used pDNSf for a long time, but it's a great app. If my help is needed, I am always ready.
