### ISSUE TITLE
内置解析器有问题

### ISSUE THREAD

**Issue by biange200** [Gedsh/InviZible#123]
invizible内置dnscrypt解析器有问题  dnspod alidns用不了的
![Screenshot_2022-01-23-17-32-27-80_7016ae331e6b0e204f345bba08185605.jpg](https://user-images.githubusercontent.com/37582806/150910099-7b56e1a4-3011-45b2-82d6-bf67aba43004.jpg)![Screenshot_2022-01-23-17-32-37-67_7016ae331e6b0e204f345bba08185605.jpg](https://user-images.githubusercontent.com/37582806/150910141-6a9f1244-e290-4a0e-8ff5-a2736abfbf54.jpg)

我现在重新添加了这里面的https://github.com/CNMan/dnscrypt-proxy-config
https://raw.githubusercontent.com/CNMan/dnscrypt-proxy-config/master/public-resolvers.md
(https://cdn.jsdelivr.net/gh/CNMan/dnscrypt-proxy-config/master/public-resolvers.md)
![Screenshot_2022-01-25-12-15-32-42_d0ef7a9810af20f7b394f4f927b723b0.jpg](https://user-images.githubusercontent.com/37582806/150910240-da34fb93-c56c-4048-b4cc-fa2d3928624d.jpg)
他的alidns可以正常使用

**Comment by Gedsh** [comment]
InviZible does nothing with DNSCrypt server certificates. You can try stopping DNSCrypt. Then Menu -> DNSCrypt Settings -> Clean module folder. Then start DNSCrypt again. If this does not help, you can ask the DNSCrypt developer to remove or update the server hash.

**Comment by biange200** [comment]
I updated version 5.2 to clear the module folder. It seems to be working normally![Screenshot_2022-01-26-06-58-47-93_7016ae331e6b0e204f345bba08185605.jpg](https://user-images.githubusercontent.com/37582806/151074050-5422a9c3-a603-4855-a93e-8625d85b5dff.jpg)
