### ISSUE TITLE
IP blocklist is not working for me. Is it because of the way I have written them?

### ISSUE THREAD

**Issue by JJenkx** [Gedsh/InviZible#126]
Edit: it seems to be blocking pings to the addresses specified in the list. I am still investigating

Edit2: I believe this is specific to the browser (Vanadium) or maybe even specific to the GrapheneOS implementation of Vanadium. Terminal Pings to the IP addresses and visits to facebook.com on IceRaven browser both result in IPs being successfully blocked. I believe now that this should be closed unless I am missing something

I added the IP entries below, one per line, to list in Menu > DNSCrypt Settings > Pattern-based IPblocking (IP blacklist)

I have Tor and I2P routing disabled and only have "Protect NDS with DNSCRYPT" box checked off for this test. 

I am using GrapheneOS with Android 12 and this test is being performed on a secondary user profile (full second profile, not work profile or similar). I expected not to be able to load facebook.com, and for a split second, facebook.com shows as unreachable when the browser (Vanadium) has all data cleared before this test. After that split second facebook.com loads up and the IP addresses contained in the list also show up under the main DNS tab of this app. Is the list format I am using supported? If these are not supported, is there a way to generate supported ranges for facebook owned IPs?

This is the command I used to generate the list. aggregate6 is a pip program

```
whois -h whois.radb.net -- '-i origin AS32934' | grep -ioP '^route:.*\s\K\d.*' | aggregate6
```

```
31.13.24.0/21
31.13.64.0/18
45.64.40.0/22
66.220.144.0/20
69.63.176.0/20
69.171.224.0/19
74.119.76.0/22
102.132.96.0/20
103.4.96.0/22
129.134.0.0/16
147.75.208.0/20
157.240.0.0/16
173.252.64.0/18
179.60.192.0/22
185.60.216.0/22
185.89.216.0/22
204.15.20.0/22
```

**Comment by Gedsh** [comment]
> Is the list format I am using supported?

https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-blocked-ips.txt

> this test is being performed on a secondary user profile

If InviZible is only installed in the main profile in VPN mode, it may or may not work, depending on the rom. It should definitely work in Root mode.

> whois -h whois.1e100.net

You should also be aware that DNSCrypt does not actually block IP, but DNS if it resolves to the specified IP. So pay attention to the DNS cache.

**Comment by JJenkx** [comment]
Thank you for the reply. DNSCrypt is installed on the same profile. Strangely, it seems to be blocking the IP's even when I ping them directly. Maybe ping is still doing a dns lookup? It nice to see wildcard support.

Here is what my current ip-blacklist.txt looks like https://github.com/JJenkx/Personal/blob/main/ip-blacklist.txt
