### ISSUE TITLE
A question about using NextDNS within the app

### ISSUE THREAD

**Issue by X9DF** [Gedsh/InviZible#127]
Would something like supporting a custom profile made by the user be considered?  Ie. being able to use the https://dns.nextdns.io/XXXXXX URL provided by NextDNS.

**Comment by Generator** [comment]
You have a DNSCrypt address on my.nextdns.io or make a DNSCrypt stamp https://dnscrypt.info/stamps/

Select DNS-over-HTTPS and the other fields, then just add a custom provider on the app

**Comment by X9DF** [comment]
> You have a DNSCrypt address on my.nextdns.io or make a DNSCrypt stamp https://dnscrypt.info/stamps/
> 
> Select DNS-over-HTTPS and the other fields, then just add a custom provider on the app

Thanks for the info, does the option "no filter" mean that it transparently does the queries rather than intervening on them (like for blocking DNS queries by responding with 0.0.0.0 and the likes)? Does it affect anything but the metadata of what the app displays?

**Comment by X9DF** [comment]
It would appear NextDNS conveninelty shows a premade hash, was able to get it working with that.

However this raises an issue. I've been using "exclude applications" to make some apps not use the TOR network, however this also excludes them from the DNSCrypt part. Is there a way to make it still use the custom DNS?

**Comment by Gedsh** [comment]
> Does it affect anything but the metadata of what the app displays?

It is just for display.

> I've been using "exclude applications" to make some apps not use the TOR network, however this also excludes them from the DNSCrypt part.

It is actually impossible to exclude an application from DNSCrypt. All applications use DNSCrypt if it is running.

**Comment by X9DF** [comment]
> It is actually impossible to exclude an application from DNSCrypt. All applications use DNSCrypt if it is running.

Ah, it seems as though the NextDNS configuration page showed whatever was set up as the `bootstrap_resolvers` as the actual DNS the system was using. Seems to be working now.
