### ISSUE TITLE
Anonymized-DNS relays

### ISSUE THREAD

**Issue by fusionneur** [Gedsh/InviZible#129]
I observed a somewhat hidden feature - if you long press a server in "fast settings" > "select DNScrypt servers" list, you get access to another list of dnscrypt relays. The same list is shown by selecting a dnscrypt server such as "adguard-dns", when a clickable message appears where you are actually able to select the relays and i also see some are pre-defined.

Some thoughts around this:
- this option (anonymized relays) should be more visible and more intuitive. for example, there should be an entry in "Fast Settings" such as "Select DNSCrypt relays" (..which should be greyed out when only non-compatible dns server were selected)
- there should be a searchbox to search and select your favourite anon relay
- there should be a filter in the "DNSCrypt Settings" to show only dns servers which compatible with anonymized-dns relays (from my understanding only dnscrypt and odoh is currently supported..in this app's case only dnscrypt)
- the dns servers should be tagged whether it is relay compatible similar to how others are tagged with "DNSSEC" for example
- if selecting adguard-dns dns server for example, some anonymous relays are already predefined, even if a warning is shown that the server is incompatible with anonymization. Also for these non-compatible with relays servers, the message to allow relays selection should not be shown

**Comment by Gedsh** [comment]
> if you long press a server

No long press required. Just click "Anonymize relays are not used. Press to add".

>  for example, there should be an entry in "Fast Settings"

Anonymize relays are selected separately for each DNSCrypt server.

> there should be a searchbox to search and select your favourite anon relay

It's planned.

> there should be a filter in the "DNSCrypt Settings" to show only dns servers which compatible with anonymized-dns relays

All DNSCrypt servers are compatible. At least with force_tcp enabled. ODOH is a different technology.

> the dns servers should be tagged whether it is relay compatible similar to how others are tagged with "DNSSEC" for example

Unable to determine if DNSCrypt server is incompatible with anonymization with force_tcp disabled.

> Also for these non-compatible with relays servers, the message to allow relays selection should not be shown

Enable force_tcp in DNSCrypt settings. All DNSCrypt servers are compatible if this option is enabled.

**Comment by Gedsh** [comment]
> this is written in their description: "This server is incompatible with anonymization"

This description is only relevant when using UDP. With force_tcp enabled, the anonymization feature works. But you can just choose another servers if you are in doubt.
