### ISSUE TITLE
I'm not sure that DNSCrypt works

### ISSUE THREAD

**Issue by wuniversales** [Gedsh/InviZible#13]
As the title mentions, I am not sure that DNSCrypt works, no resolved dns address is shown, should we do any additional configuration to android? Maybe you need to redirect DNS requests to localhost?

**Comment by Gedsh** [comment]
>  should we do any additional configuration to android?

In root mode, everything works without additional configuration.
In proxy mode, please read project wiki.

> Maybe you need to redirect DNS requests to localhost?
In root mode, InviZible redirects DNS queries to 127.0.0.1:5354

> I am not sure that DNSCrypt works

There is one easy way to check this - when using default DNSCrypt servers, InviZible block most ads. But clear your browser cache after starting DNSCrypt.

**Comment by Kein** [comment]
Why is there no way to configure DNScrypt with your own custom config?

**Comment by Gedsh** [comment]
It is not so easy to implement a fully customizable DNSCrypt config compatible with InviZible. And this feature is not in demand.

**Comment by Kein** [comment]
Sow hat the point of security part of DNS Crypt if there is some shady config used? What if you set up your own DNS server and now ha impressive DB to sell?
_Security as a joke._

**Comment by Gedsh** [comment]
InviZible uses the configuration stored in the file: /data/data/pan.alexander.tordnscrypt/app_data/dnscrypt-proxy/dnscrypt-proxy.toml. If you have a root, you can check it. If you do not believe this, check the code. It is open source. If you do not believe in open-source, develop your own application.
