### ISSUE TITLE
Firewall_only mode

### ISSUE THREAD

**Issue by DI555** [Gedsh/InviZible#130]
please, provide firewall_only mode, when DNSC, TOR and PI2P not yet running. it is a very useful feature, providing firewall defendness more stable and better.
many thanks in anvance!

**Comment by Gedsh** [comment]
> please, provide firewall_only mode

Currently, this is almost impossible, as it requires significant changes to the InviZible code. And it doesn't make sense, since there are many full-featured firewalls available. The firewall in InviZible is only an auxiliary feature.

**Comment by DI555** [comment]
i see. but could be great if it’ll be placed in todo list, pls..
nevertheless firewall means much, and imo, more featured firewall will be better in anyways 👍👍👍

**Comment by Gedsh** [comment]
>  more featured firewall will be better in anyways 

I have plans to improve the firewall. You can use it with DNSCrypt as it provides basic security and does not affect internet speed.I see no reason to use the InviZible firewall alone.
