### ISSUE TITLE
Root Mode not showing

### ISSUE THREAD

**Issue by Luciogi** [Gedsh/InviZible#132]
Hi , I am using crdriod (custom rom), it gives an option which give root access to adb connection. So I installed InviZible Pro apk as system app. I expected to see root mode, in application  it is showing vpn mode and proxy mode only.
Is is possible to use root mode when app is installed as system app?

**Comment by Gedsh** [comment]
Hi, You cannot use InviZible as a system application. Install it as usual and if you have root, you will automatically switch to Root mode. Or you can do it manually.
If you don't see Root mode, it means that your phone is not rooted or InviZible simply can't use that type of root.
