### ISSUE TITLE
Degoogled using adaway

### ISSUE THREAD

**Issue by OrrellElectrics** [Gedsh/InviZible#133]
Hi sorry not so much an 'issue'

Can the app be used whilst using Adaway/Magisk on a degoogled (Lineage 18.1) One Plus 7 Pro or would it cause issues with the hosts file in Adaway?

Also my daughter has a Samsung Galaxy S6 Lite running Lineage 19 rooted and degoogled and it is causing me major problems as she likes to play the more popular games from the playstore - currently using Aurora but several of the top games will not start without Google Services Framework

If I was to install gapps on the S6 lite and install your excellent looking app would I leave adaway installed and it would allow her to install playstore games etc

I have several Sony android TV's at home and have always wondered how to 'minimize' what they can do, can this be installed on android tv's?

Thank you in advance

**Comment by Gedsh** [comment]
Hi,

> Can the app be used whilst using Adaway/Magisk on a degoogled (Lineage 18.1) One Plus 7 Pro or would it cause issues with the hosts file in Adaway?

You can use them together. But InviZible can also block ads, so there might not be much point in using Adaway.

> If I was to install gapps on the S6 lite and install your excellent looking app would I leave adaway installed and it would allow her to install playstore games etc

You can do that. No problem.

> I have several Sony android TV's at home and have always wondered how to 'minimize' what they can do, can this be installed on android tv's?

Yes. InviZible is designed to be used on Android TV.

**Comment by OrrellElectrics** [comment]
> Hi,
> 
> > Can the app be used whilst using Adaway/Magisk on a degoogled (Lineage 18.1) One Plus 7 Pro or would it cause issues with the hosts file in Adaway?
> 
> You can use them together. But InviZible can also block ads, so there might not be much point in using Adaway.
> 
> > If I was to install gapps on the S6 lite and install your excellent looking app would I leave adaway installed and it would allow her to install playstore games etc
> 
> You can do that. No problem.
> 
> > I have several Sony android TV's at home and have always wondered how to 'minimize' what they can do, can this be installed on android tv's?
> 
> Yes. InviZible is designed to be used on Android TV.

Hi thank you for the prompt rely

I did actually install it on my One Plus 7 Pro and enabled all 3 modules works great really good job - only minor issue it does drain the battery a while but I will be honest I have not looked at the various settings I just did a test run

I am using Mull and tried to do a search with Google (for the first time ever on my mobile) it would not connect which is ideal

I really liked how the it changed my location every 45 mins or so

It is perfect for Android TV again great job dev

**Comment by Gedsh** [comment]
> it does drain the battery a while

It's because of Purple I2P. This is a P2P network that requires continuous communication with routers.

You can use DNSCrypt and Tor, whose consumption is lower.

> great job dev

Thanks!
