### ISSUE TITLE
Root access attempt on start

### ISSUE THREAD

**Issue by fusionneur** [Gedsh/InviZible#135]
Even if root was not granted, and invizible running in proxy or vpn mode, it still attempts to gain root access on start.

To reproduce:
- switch to proxy/vpn, swipe up the app from recents screen, while it remains running in background.
- open the app from notification => a toast will be shown that root access has been denied

This can be reproduced as many times.

Expected:
- if not running in root mode, do not attempt to request it

**Comment by Gedsh** [comment]
> Even if root was not granted, and invizible running in proxy or vpn mode, it still attempt to gain root access on start.

InviZible should do this, since if root is not available, the Root mode and other root options will be hidden.

> if not running in root mode, do not attempt to request it

You cannot switch to Root mode until InviZible checks that root is actually available.

If you have any root manager like magisk just disable root for InviZible and you will never see the root access dialog.

**Comment by fusionneur** [comment]
I have magisk and i am seing these toast notifications whenever I open the app.

**Comment by Gedsh** [comment]
I also have magisk and don't see any toasts. Menu -> Settings -> Superuser Notification -> None. 
In any case, this is not an InviZible problem. I have no plans to change how InviZible works just to not show toasts on one single device.

**Comment by fusionneur** [comment]
> I also have magisk and don't see any toasts. Menu -> Settings -> Superuser Notification -> None. In any case, this is not an InviZible problem. I have no plans to change how InviZible works just to not show toasts on one single device.

This is just a workaround to hide the notification. The issue is not opened for the nugging itself, but rather for establishing a trust that the app would not attempt root request unless really needed. In case vpn/proxy is used, the root check in the code should be completely disabled..

**Comment by Gedsh** [comment]
> In case vpn/proxy is used, the root check in the code should be completely disabled.

So how is InviZible supposed to check if root is available to enable/disable features and options that require root? If you have ideas, welcome to make a pull request. Or you can create your own fork of InviZible with the desired behavior.

**Comment by fusionneur** [comment]
Expected behavior would be to request root access upon attempting to switch to root mode and when activating modules to run as root (https://github.com/Gedsh/InviZible/wiki/Run-Modules-With-Root-option). There might be some other features and toggles that I am not aware of right now, but these should trigger the root access request uppon switching the toggle on/off.

**Comment by Gedsh** [comment]
> Expected behavior would be to request root access upon attempting to switch to root mode

I don't like your idea. The root mode should only be visible if root is available.

**Comment by fusionneur** [comment]
From my perspective as a user it would be more intuitive to have the option there always and the GUI would be more consistent.

In my case, right now the option "root mode" is missing (because previously denied root access) which is not intuitive why it is unavailable unless you know/remember it was previously denied in magisk. The option should be, in my opinion, always there ready to be toggled and the root access request should be triggered only then.

**Comment by Gedsh** [comment]
> From my perspective as a user it would be more intuitive to have the option there always

The vast majority of users do not have root. Why should they see Root mode and why should I explain to them what root is and why it doesn't work on their phones?

**Comment by fusionneur** [comment]
All apps i used that have root requirement are requesting it upon activation of those features, unless root is required for the app to work. I don't know it just feels unnatural to see that root is being denied every time I open the app, even if I don't use any root features. Maybe it's just me...
