### ISSUE TITLE
[Question] DNSCrtypt advantages over Private DNS 

### ISSUE THREAD

**Issue by pflanzenandi** [Gedsh/InviZible#136]
I would like to know what advantages DNSCrypt has over the Androids internal Private DNS implementation, besides DNSCrypt anonymizing.

**Comment by Gedsh** [comment]
DNSCrypt can use the DNSCrypt protocol and DOH (DNS over HTTPS). Android private DNS uses DOT (DNS over TLS). You can read the differences here https://dnscrypt.info/faq

Also usually you can't use private DNS with a VPN.
