### ISSUE TITLE
dpiTunnel-cli, 4th module, pls !!!

### ISSUE THREAD

**Issue by DI555** [Gedsh/InviZible#138]
github.com/zhenyolka/DPITunnel-cli/releases

new dpiTunnel-cli has come with support console mode(what exactly IZ uses), as it’s command line implementated,
please, support 4th module feature for dpiTunnel-cli !!!
many thanks in advance!

**Comment by Gedsh** [comment]
dpiTunnel-cli requires root to work. It uses special features that cannot work without root.

And, as I said, I have no plans to add new modules to InviZible.
