### ISSUE TITLE
Possible to implement GoodbyeDPI?

### ISSUE THREAD

**Issue by MF-Debug** [Gedsh/InviZible#14]
I have found [this](https://github.com/ValdikSS/GoodbyeDPI) project which can bypass Deep Packet Inspection systems found in many Internet Service Providers used for blocking access to certain websites. Is it possible to implement it in this app?

**Comment by Gedsh** [comment]
I was talking with author of similar project https://github.com/bol-van/zapret about integration. It is possible. But it will be too difficult for users to configure, and for me to develop 3 modules InviZible Pro and  additionally GoodbyeDPI. So the answer is no for this time. Perhaps in the future I will change my decision.

It is better to develop separate application for this purpose.

**Comment by PHPoenX** [comment]
@MF-Debug No, it isnt possible. GoodbyeDPI is suitable only for using on Windows
We can use zapret on Android
