### ISSUE TITLE
support for custom socks proxy

### ISSUE THREAD

**Issue by soredake** [Gedsh/InviZible#143]
Right there is support for tor/i2p/dnscrypt, it would be nice if there is support for using custom socks proxy (tor is slow).

**Comment by Gedsh** [comment]
You can use ShadowSocks or SagerNet in VPN mode as a local encrypted proxy. I do not recommend using a remote Socks proxy as its traffic is not encrypted and can be tracked by the provider's DPI equpment. https://github.com/Gedsh/InviZible/wiki/Using-InviZible-alongside-with-VPN
