### ISSUE TITLE
XIAOMI USERS FIX: NOT AN ISSUE*

### ISSUE THREAD

**Issue by andmailconta** [Gedsh/InviZible#144]
I'm currently on MIUI 13
To fix Invizible killed by Android System, also as lost root permission, then do:

> 1 - Enable Auto Start for Magisk and Invizible;

> 2 - Check All Other Permissions for both;

> 3 - Disable Battery Optimizations for both;

> 4 - Open Xiaomi Security App, tap Settings icon, go to Boost Speed/Lock Apps and toggle on Magisk and Invizible.

Solved!

**Comment by Gedsh** [comment]
Thanks for the guide!
