### ISSUE TITLE
Intents

### ISSUE THREAD

**Issue by lgwapnitsky** [Gedsh/InviZible#147]
Is there a list of intents i can use for automation of triggering the app?

**Comment by Gedsh** [comment]
Hi. There are no intents. But you can use a shell script to manage InviZible modules. Menu -> Common Settings -> Enable script control.

**Comment by lgwapnitsky** [comment]
Is there a way to turn the script Into something that will work here?

**Comment by Gedsh** [comment]
I don't understand what exactly you want to achieve.

**Comment by lgwapnitsky** [comment]
Trying to automate the startup and shutdown using an app like tasker

**Comment by Gedsh** [comment]
Have you tried using Tasker with the mentioned shell script command?

**Comment by lgwapnitsky** [comment]
Shell script isn't doing anything at termux terminal

**Comment by Gedsh** [comment]
I checked it and it seems that Android versions from Android 8 do not allow this feature. I will check what I can do.

**Comment by lgwapnitsky** [comment]
Yes
Script doesn't activate anything, either in tasker or regular termux window
