### ISSUE TITLE
something happened on my android 

### ISSUE THREAD

**Issue by Gamefire238** [Gedsh/InviZible#148]
looks like the app closed the feature that was on my android, to be exact (feature "real time network speed" in notification bar) and often accompanied by a network disconnect!?

before 
![IMG_20220807_103717](https://user-images.githubusercontent.com/78879425/183272730-693a8417-7e9a-41c2-8f5b-6e9239c46d71.jpg)

after 
![IMG_20220807_104333](https://user-images.githubusercontent.com/78879425/183272741-cf2d24f5-7eed-4e7c-b40f-0d0e5b0cbd81.jpg)

invizible pro version: 1.7.1 Beta
VIVO y12, Android 11

**Comment by Gedsh** [comment]
InviZible can't do anything with the icons in the notification bar. This is an undocumented unofficial Android feature of some roms. So there is nothing I can do to fix it.
