### ISSUE TITLE
Have they just copied your app?

### ISSUE THREAD

**Issue by 0xFFFFFFFFFFFFFFFFFFFFF** [Gedsh/InviZible#149]
https://play.google.com/store/apps/details?id=com.fulldive.extension.tordnscrypt

**Comment by Gedsh** [comment]
Thank you. I know. This is an outdated fork. I don't know why they do it. And what they add to the source code. In this way, they copied several popular open source applications. You can check out their other apps on the play market.

**Comment by Gedsh** [comment]
In recent commits, they added subscriptions, ads, and analytics...
