### ISSUE TITLE
High Battery Usage in F-Droid version 5.8.0

### ISSUE THREAD

**Issue by AntonyNderitu** [Gedsh/InviZible#150]
After upgrading from version 5.7.0 to 5.8.0, my phone lost its charge considerably faster. Since it was the only app to have updated, I decided to uninstall the update and revert to version 5.7.0.

My battery stabilised and has continued to work well since. Please look into this issue.

**Comment by Gedsh** [comment]
There are no changes related to battery consumption in the new version.

Look into this https://github.com/Gedsh/InviZible/issues/139
