### ISSUE TITLE
Auto on/off possible. 

### ISSUE THREAD

**Issue by Pranab009** [Gedsh/InviZible#152]
Hi, your app tooo good but, is it possible that when I tern off internet/wifi then it also 
turn off and, when I tern on internet/wifi then it also turn on automatically.

Why I request for this feature, you know how much time you turn on and off your internet in a day. 

When I don't use internet or offline then it is not needed and if it is turn on all the time then it consumed battery.

I know notification tile and widgets are available but many time I forgot to turn it on.If it was on and off automatically like (Netspeed Indicator App) then it save battery and easy to use.

I know for this feature need to access "App Usage Permission." and it is optional feature.

Think about it. If possible then add this feature.

![Screenshot_20220730-155135_1-](https://user-images.githubusercontent.com/65340361/185207407-6840ebd5-7b38-4c53-8b60-cf83dcf43abd.png)

**Comment by Gedsh** [comment]
Hi, Thank you!

This feature can potentially leak an IP address when the Internet is already available but InviZible is still starting.

I do not plan to add features that can affect privacy or anonymity.

InviZible consumes quite a bit of battery power when the internet is turned off.

**Comment by Pranab009** [comment]
Yes you are right but 
"Automatic Stop" is possible? because it is stop after internet off and there is no privacy issue with it.
Think about it.

**Comment by Gedsh** [comment]
> because it is stop after internet off and there is no privacy issue with it.

Sure. The only issue will be with the start.

> Think about it.

I'm sorry. I don't like this kind of features.
