### ISSUE TITLE
Question about Wireguard

### ISSUE THREAD

**Issue by hairy-tortoise** [Gedsh/InviZible#153]
Hi,
I really need a VPN instead of Tor, because I need to connect to my Home Network from everywhere to access things in there and I want to use this with a firewall. Is it possible at all to add Wireguard or OpenVPN or something like that?

**Comment by Gedsh** [comment]
Hi,
I have no plans to add a VPN to InviZible. But you can use InviZible with VPNs https://github.com/Gedsh/InviZible/wiki/Using-InviZible-alongside-with-VPN

**Comment by Rexadev** [comment]
> Hi, I have no plans to add a VPN to InviZible. But you can use InviZible with VPNs https://github.com/Gedsh/InviZible/wiki/Using-InviZible-alongside-with-VPN

Would you consider it in future?
