### ISSUE TITLE
[Bug] multiuser support 

### ISSUE THREAD

**Issue by nahuhh** [Gedsh/InviZible#154]
Doesn't appear to work

1. Using shelter + bromite in work profile
2. Invizible on main profile, multiuser enabled, vpn mode
3. Inviz > settings > fast > [tor]select apps >select bromite(M)
4. Using work profile bromite, navigate to check.torproject.org or an onion address
5. Fails because its using system dns

Android 10
Beta + fdroid version

**Comment by Gedsh** [comment]
This feature definitely only works in Root mode. In VPN mode, it depends on your rom. I can't do anything about it from my side. I can only completely disable this feature for VPN mode.

**Comment by nahuhh** [comment]
> This feature definitely only works in Root mode. In VPN mode, it depends on your rom. I can't do anything about it from my side. I can only completely disable this feature for VPN mode.


Perhaps a warning etc that it might not work without root.
Also, I wasn't able to find info about this feature in the documentation.

Either of those (warning or documentation) may have prevented me from opening an issue.

Thanks

**Comment by Gedsh** [comment]
Fixed via 515d62bdb1c7e22d03fd464a2c21913db85571e4
