### ISSUE TITLE
App switching back to VPN mode automatically from proxy mode

### ISSUE THREAD

**Issue by koshyviv** [Gedsh/InviZible#155]
So I want to run the app on proxy mode, I do set it up and  also enable the child lock.

I am using Tracker Control to route the traffic to it.

It works fine till here.
<img src="https://user-images.githubusercontent.com/32818583/190059043-e5f4fd0b-8d52-4beb-969a-f8ee9b1a75ce.png" width="30%" height="30%">

if I open the Invizible Pro app again it switches back to the VPN mode
<img src="https://user-images.githubusercontent.com/32818583/190058999-75338b83-cb26-4af7-b6c6-f73eaa3559c8.png" width="30%" height="30%">

Can you please tell me how to stop it from auto switching to VPN mode, I want it on the Proxy mode only.
I've read the wiki and did search for it, but couldn't find much help.
Would really appreciate any info!

Device Details
Poco M3
Custom ROM (non root)
Android 12L

**Comment by Gedsh** [comment]
I cannot reproduce your issue.
Try reinstalling InviZible. If this does not help, please reproduce the problem on your phone and send me the logs: Menu -> Logs -> Collect Logs.
