### ISSUE TITLE
[DNSCrypt - resolvers and relays]: Choose only port 443

### ISSUE THREAD

**Issue by Horizonbli** [Gedsh/InviZible#159]
Hello,

Could it be possible to have your app to give the option only to choose resolvers and relays running on port 443?

Thanks

**Comment by Gedsh** [comment]
Hello,

InviZible has no information about which port resolvers and relays are running on. Only DNSCrypt itself has it. And it can only be implemented as part of DNSCrypt.

So it's best to ask the DNSCrypt developer.
