### ISSUE TITLE
dnscrypt proxy port issue

### ISSUE THREAD

**Issue by SamuelP1111** [Gedsh/InviZible#16]
Hi,

I start to use you ARM64 apk on Huawei P10 android 9.0 stock (without root or unlock).
The phone is up to date.
The app version is beta v0.6.0.
Internet connection is WIFI, static ip and high speed without any problems.

I inform when trying to edit the dnscrypt port, it gives a "dnscrypt module failed" and app force close.
I'd to set back to default 5354.

Regards

Samuel P

**Comment by Gedsh** [comment]
You cannot use ports up to 1024 without root.

**Comment by SamuelP1111** [comment]
Hi and thanks for answer.

I understand but set the dnscrypt proxy port give an error message "android has kill the app".
![Screenshot_20200214_132958_pan alexander tordnscrypt](https://user-images.githubusercontent.com/60618485/74534049-39362e80-4f33-11ea-8dfb-91c2fa1b9dd1.jpg)

Regards

SamuelP

**Comment by Gedsh** [comment]
> I understand but set the dnscrypt proxy port give an error message "android has kill the app".

What port number are you using?
