### ISSUE TITLE
No connection with Video Doorbell app while on LAN

### ISSUE THREAD

**Issue by user8446** [Gedsh/InviZible#160]
Hi,

I have a video doorbell app (SkyBell) in which I cannot connect to my video doorbell while on WiFi on the same LAN as the doorbell. However, if I turn off InviZible or I am on the cell network it works as expected.

I am using DNSCrypt only, no firewall, and I have "Bypass LAN addresses" toggled ON even though I'm not using Tor.

I have also added `10.in-addr.arpa X.X.X.X` and `lan X.X.X.X` (my LAN) to the DNSCrypt forwarding rules.

This appears similar to https://github.com/Gedsh/InviZible/issues/119 and https://github.com/Gedsh/InviZible/issues/124 due to it being a LAN only issue.

Any hints or direction to debug?

**Comment by user8446** [comment]
I did try a different DoH app ([Intra](https://f-droid.org/en/packages/app.intra/)) and have the same issue until I whitelist it in the app. Possibly some apps do not work if it detects a VPN?

Maybe an app whitelist might be best for InviZible as well?

**Comment by Gedsh** [comment]
Hi,

>  I cannot connect to my video doorbell while on WiFi on the same LAN

If an app requires local DNS to function, it will not work with InviZible. InviZible intercepts all DNS and there is no way to change this behavior.

>  I have also added 10.in-addr.arpa X.X.X.X and lan X.X.X.X (my LAN) to the DNSCrypt forwarding rules.

Forwarding rules work correctly only in Proxy mode. In Root or VPN mode, InviZible enforces security rules to avoid data leaks. These rules interfere with forwarding rules.

>  This appears similar to https://github.com/Gedsh/InviZible/issues/119 and https://github.com/Gedsh/InviZible/issues/124 due to it being a LAN only issue.

It looks like it. But, from my point of view, the most important thing is to prevent data leaks.

> Maybe an app whitelist might be best for InviZible as well?

As I mentioned above, there is no way to bypass DNS in InviZible. This is the issue. InviZible works differently than Intra or other VPN apps. This is good for privacy and security, but causes such problems with some apps on the same local network. Currently, I have not found a good solution to keep privacy and fix this issue.
