### ISSUE TITLE
Aleatory restarts while using f-droid InviZible

### ISSUE THREAD

**Issue by rimugu** [Gedsh/InviZible#161]
BRAND Ulefone
MODEL Armor X8
MANUFACTURER Ulefone
PRODUCT Armor_X8
DEVICE Armor_X8
BOARD Gotron-GQ3093SH1
HARDWARE mt6762
SUPPORTED_ABIS [arm64-v8a, armeabi-v7a, armeabi]
SUPPORTED_32_BIT_ABIS [armeabi-v7a, armeabi]
SUPPORTED_64_BIT_ABIS [arm64-v8a]
SDK_INT 29
APP_VERSION_CODE 2170
APP_VERSION_NAME 5.8.0
APP_PROC_VERSION armv7a
CAN_FILTER false
APP_VERSION fd
DNSCRYPT_INTERNAL_VERSION 2.1.1
TOR_INTERNAL_VERSION 0.4.7.8-dev
I2PD_INTERNAL_VERSION 2.42.1
SIGN_VERSION PLqJkfckBUDkgQ+5E9VPSQ==

**Comment by rimugu** [comment]
Does anyone have a place to upload the log to give the link as github won't allow attaching the log file directly?

**Comment by Gedsh** [comment]
Hello. Please describe your issue.

**Comment by rimugu** [comment]
Issue description: Aleatory restarts while using f-droid InviZible

**Comment by Gedsh** [comment]
InviZible is unable to restart the phone. It doesn't have that feature. It might be your rom's bug.
