### ISSUE TITLE
not stable in China

### ISSUE THREAD

**Issue by ghost** [Gedsh/InviZible#162]
The meek-lite and vanilla bridges are censored in China. Invizible can't request bridges, because the official site of Torproject is blocked in China, but Invizible connects to Torproject to request bridges.

**Comment by Gedsh** [comment]
If you want to use InviZible in China, the best solution is to use Tor over VPN (and DNSCrypt over VPN).

https://github.com/Gedsh/InviZible/wiki/Tor-over-VPN
