### ISSUE TITLE
Ability to bypass blacklist

### ISSUE THREAD

**Issue by gvijayakumar-16** [Gedsh/InviZible#166]
Is there a way to bypass an application from completely using the blacklist under DNSCrypt settings?

**Comment by Gedsh** [comment]
Menu -> DNSCrypt Settings -> Whitelist.

**Comment by gvijayakumar-16** [comment]
Whitelist under DNSCrypt settings is pattern based right? 
What if I wanted to whitelist all the requests from an application? 

_**Reason**: An application am using is making multiple calls for authorization and a few of these are getting blocked by blocklists that I have imported. Instead of adding the failing requests to whitelist manually, I am looking for a way to bypass this app as a whole_
