### ISSUE TITLE
It doesn't provide VPN mode for I2P

### ISSUE THREAD

**Issue by ghost** [Gedsh/InviZible#167]
It only provides proxy mode for I2P. Reasons to provide VPN mode for I2P: The 1st is that someone probably hosts malicious I2P site that runs WebRTC to leak users' IP addresses. The 2nd is that sites on regular Internet may use WebRTC to leak our IP addresses, I2P provides an outproxy called "false.i2p", and 3rd-party also provides outproxies for I2P. It's possible to access regular Internet through an outproxy.

**Comment by Gedsh** [comment]
For ability to visit i2p websites in any browser you should start DNSCrypt. So VPN will be enabled.

If you want the browser to only visit i2p websites, enable the firewall and only allow LAN. In this case, the browser will only be able to visit local LAN resources, onion and i2p sites.

I don't know how WebRTC and VPN mode are related. You should disable WebRTC in your browser. This is not the responsibility of InviZible.
