### ISSUE TITLE
Multiple abi in F-Droid

### ISSUE THREAD

**Issue by linsui** [Gedsh/InviZible#168]
We can autoupdate multiple abi apps now. But we can't handle the version code scheme used in InviZible. We only keep the apks with highest version code but the armv7 apks always have lower version code than armv8 ones. So they'll be moved to archive. Could you please change the scheme so that the abi version code is a suffix? Thanks!

**Comment by Gedsh** [comment]
Please provide an example. I will check if I can implement this in InviZible.

In any case, there is a universal version of InviZible with both armv7a and arm64 binaries. You can use it if you think it's a good idea.

**Comment by linsui** [comment]
Changing this line https://github.com/Gedsh/InviZible/blob/8da27f15910f2758b074e192e0463bb4289eb930/tordnscrypt/build.gradle#L122 to

```
 output.versionCodeOverride = abiVersion + defaultConfig.versionCode  * 100
```

is enough. Then the version codes will be 17502, 17503.

**Comment by Gedsh** [comment]
Thank you!

The new scheme will be used in the next stable release.

**Comment by linsui** [comment]
Thanks! I'll update the build metadata when the next version available.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12622 Done!
