### ISSUE TITLE
set proxy when VPN mode is off

### ISSUE THREAD

**Issue by auts2022** [Gedsh/InviZible#169]
It seems unable to set Socks5 proxy when VPN mode is off.

**Comment by Gedsh** [comment]
This feature is only available in VPN mode, as a VPN is required to redirect internet traffic to the socks proxy. It cannot work with other modes by design.

**Comment by auts2022** [comment]
> This feature is only available in VPN mode, as a VPN is required to redirect internet traffic to the socks proxy. It cannot work with other modes by design.

It seems you misunderstood me. In my case, click the button (the 3 horizontal lines) in top left corner, click "Common Settings", and in that page, "Use socks5 proxy" is only available in VPN mode.

**Comment by Gedsh** [comment]
I understood. This is the option I was talking about above.
