### ISSUE TITLE
How or where to send logs to dev?

### ISSUE THREAD

**Issue by ghost** [Gedsh/InviZible#17]
Hi

Can you give a way to send you logs in MP?

Thanks

ARM64 apk on Huawei P10 android 9.0 stock (without root or unlock).
The phone is up to date.
The app version is beta v0.6.0.
Internet connection is Wifi, static ip and high speed without any problems.

Tor is working well. IP is really modified. Internet speed stay correct. I cannot know if encryption is ok.

Some issues with dnscrypt proxy , i've made some feedback for this.

I think it's a really good project.

I don't understand why you want to keep two ways for vpn or proxy and check Tor or dnscrypt proxy.

Regards

Samuel P

**Comment by Gedsh** [comment]
Can you give a way to send you logs in MP?

You can use the Telegram group https://t.me/InviZiblePro_Group or mail: invizible.soft@gmail.com

> I don't understand why you want to keep two ways for vpn or proxy and check Tor or dnscrypt proxy.

Actually there are 3 ways. Please read [wiki](https://github.com/Gedsh/InviZible/wiki).

**Comment by SamuelP1111** [comment]
Hi,

I just sent all logs i can by mail.
Regards

SamuelP
