### ISSUE TITLE
[FEATURE REQUEST] A user-friendly way of white/blacklisting blocked domains

### ISSUE THREAD

**Issue by 0xlne** [Gedsh/InviZible#171]
I currently need to copy a domain I want unblocked to a text file, import it into inviZible whitelists, & powercycle inviZible.
Is there an easier way to do this, like pDNSf, where you rightclick in the DNS log with an toggle to enable/disable a domain?

**Comment by Gedsh** [comment]
InviZible is not an ad blocker. It's just an auxiliary feature. I have no plans to make another ad blocker. I'm sorry.

Maybe over time I will implement it. But it has the lowest priority.
