### ISSUE TITLE
Add http proxy setting.

### ISSUE THREAD

**Issue by ghost** [Gedsh/InviZible#172]
In Common Settings, there's a socks5 proxy option, could you please add http proxy option?

**Comment by Gedsh** [comment]
Unfortunately, I have no plans for this. It will require development from scratch of many things, including C-code. Which is very hard. And I don't see any advantage in http proxy.

In any case, you should not use remote proxies. They are transparent to the provider's DPI equipment. Use local proxies like shadowsocks that can encrypt traffic to remote servers.
