### ISSUE TITLE
Stuck on executing root command

### ISSUE THREAD

**Issue by gvijayakumar-16** [Gedsh/InviZible#177]
Application was given proper root privileges and I am able to see toast messages that root privileges was granted. But I see the execution message hung in the notification area. Because of this if I make any changes in the firewall, it does not reflect until I reboot the phone.

It occurs around 2-3 hours after a reboot and persists until the phone is restarted again.

_Device details: Raphael, Evolution X (Android 13), Magisk delta (happens with Magisk as well)_

<img width="958" alt="image" src="https://user-images.githubusercontent.com/12172731/206963679-08193d50-9387-4a08-b429-7b4cd7ba6df6.png">

**Comment by Gedsh** [comment]
This is the problem of the new Magisk. It doesn't give InviZible root privileges correctly. Currently I don't know how to make the new Magisk friendly to InviZible. You can use older versions of Magisk which works great.
