### ISSUE TITLE
One app to Control access to WiFi/Data/ VPN/VPN bypass, Domain/IP Block, VPN , DNS, Tor Client that works using VPN service.. 

### ISSUE THREAD

**Issue by Rexadev** [Gedsh/InviZible#178]
1. 

AFWall - Blocking apps from internet and control connection to LAN, WiFi, Data, VPN
2. AdAway - Domain Block
3. IP Blocklist8.
4. DNS - DoT10.
5. VPN - OpenVPN, WireGuard Client12.
6. Tor Clients

**Comment by Gedsh** [comment]
>  1. AFWall - Blocking apps from internet and control connection to LAN, WiFi, Data, VPN

Already exists in InviZible as a firewall feature.

> 2. AdAway - Domain Block

Already exists in InviZible as DNSCrypt blacklist.

> 3. IP Blocklist8.

Already exists in InviZible as DNSCrypt IP blacklist.

> 4. DNS - DoT10.

Not planned as it has no advantages over existing DNSCrypt and DOH protocols.

> 5. VPN - OpenVPN, WireGuard Client12.

Not planned as there can't be all VPN protocols in one app. It will be extremely difficult to develop and use.

> 6. Tor Clients

Already exists in InviZible.
