### ISSUE TITLE
VoWifi not working in root mode

### ISSUE THREAD

**Issue by gvijayakumar-16** [Gedsh/InviZible#179]
VoWifi is not working in root mode. It gets enabled when I stop InviZible, but doesn't work as soon as I re-enable it.

VoLTE was also the same, but looks like blocking certain system apps was causing the issue. I got VoLTE working again, but not VoWifi. Tried giving all access to all system apps and disabling firewall altogether as well, but still VoWifi was not working as long as InviZible was enabled

**Comment by Gedsh** [comment]
Unfortunately, I don't think the problem can be solved. VoWifi requires some addresses to bypass InviZible. These addresses depend on the network provider.

In any case, I can't test this problem as my network doesn't have VoWifi and VoLTE functionality.
