### ISSUE TITLE
Dnscrypt resolvers list update issue

### ISSUE THREAD

**Issue by SamuelP1111** [Gedsh/InviZible#18]
Hi,

I start to use you ARM64 apk on Huawei P10 android 9.0 stock (without root or unlock).
The phone is up to date.
The app version is beta v0.6.0.
Internet connection is WIFI, static ip and high speed without any problems.

I inform, if i select servers on the original list without using first time app (without list update),
after run the app first time, some servers have disapeared from list.
But if before update i have choosen a server not allow in new list, the server stay used, but not appear in list. So i can't uncheck or made any modification for relay.

I inform after first run and update, all the criptostorm servers arent allow anymore and some other ones.

Thanks

regards

Samuel P

* Sorry i don't speak well English, i'm French.

**Comment by Gedsh** [comment]
> But if before update i have choosen a server not allow in new list, the server stay used, but not appear in list. So i can't uncheck or made any modification for relay.

These servers should disappear from the used servers after you open and then close the list of DNSCrypt servers.

> I inform after first run and update, all the criptostorm servers arent allow anymore and some other ones.

This is OK. The list of servers changes from time to time.
