### ISSUE TITLE
Add Geph support

### ISSUE THREAD

**Issue by oilel** [Gedsh/InviZible#180]
https://github.com/geph-official 
Tor is decentralized, which means Tor project cannot ensure every node in Tor network is trustable, there may be malicious nodes; but Geph can ensure every node is trustable, that project is registered in Estonia. If they found that backdoor access is possible in Estonia, they will move to another jurisdiction.

**Comment by Gedsh** [comment]
> Add Geph support

I have no plans to add new networks to InviZible.

> Tor is decentralized, which means Tor project cannot ensure every node in Tor network is trustable, there may be malicious nodes; but Geph can ensure every node is trustable

Sounds funny. So they are centralized and we have to trust them that they don't track users?

Tor has many tools for checking nodes.
