### ISSUE TITLE
Encrypted voice/video calls not connecting

### ISSUE THREAD

**Issue by 3n2pS3P5kG23S96yxRbUHAZajuH2F** [Gedsh/InviZible#181]
Hello,

I hope I'm not posting in the wrong place. I'm currently connecting through InviZible Pro as VPN on LineageOS (Android 11). Everything seems to be working fine (browsing, text messaging, file transfers, etc.), except for encrypted voice/video calls. When I disable the VPN settings, the calls work as normal. The messenger apps I've tried that exhibit this behavior are:

Element 
Session F-Droid
SimpleX Chat (tried both P2P and "via relay")

Is there a way to configure so that calls work through InviZible Pro?

Thank you.

**Comment by Gedsh** [comment]
Hello,

If you want to use calls, you should exclude these applications from Tor in the Fast settings. Calls usually require UDP, but Tor only supports TCP.
