### ISSUE TITLE
To change Tor circuit without restarting Tor

### ISSUE THREAD

**Issue by oilel** [Gedsh/InviZible#182]
It seems that the user must restart Tor to change circuit for a specific site, can it change circuit without restarting?

**Comment by Gedsh** [comment]
You can press the round arrow in the top right corner of the InviZible main window. It's called a new identity. It will restart Tor automatically.

**Comment by oilel** [comment]
> It will restart Tor automatically.

Does the desktop version (e.g., Windows version) Tor browser restart after changing identity?

**Comment by Gedsh** [comment]
Nope. There is another method that was previously used by InviZible. With this method, Tor does not restart, but usually only changes the middle node of its circuit, which is not as good as a complete rebuild of the Tor circuit. The Tor Browser uses the specified method to change identity.

**Comment by oilel** [comment]
> You can press the round arrow in the top right corner of the InviZible main window.

Sometimes the round arrow doesn't appear, I press the three dots (will show VPN mode and Proxy Mode options) then the round arrow will appear.

**Comment by Gedsh** [comment]
This is a problem with android libraries. There is nothing I can do about it.
