### ISSUE TITLE
[Question] How to use fowarding_rules?

### ISSUE THREAD

**Issue by TalOrenshtein** [Gedsh/InviZible#183]
How can I use this tool correctly? Can I use forwarding_rules to reroute links from one domain to another? Let's say, when I go to google.com/search?q=someQuery it'll redirect it to searx.be/search?q=someQuery.

Maybe I just didn't understand it's purpose well...
Thanks :)

**Comment by Gedsh** [comment]
> Can I use forwarding_rules to reroute links from one domain to another? Let's say, when I go to google.com/search?q=someQuery it'll redirect it to searx.be/search?q=someQuery.

No.

> Maybe I just didn't understand it's purpose well...

https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Forwarding
