### ISSUE TITLE
support transparent proxy

### ISSUE THREAD

**Issue by oilel** [Gedsh/InviZible#184]
Transparent proxy is not http or socks proxy, e.g., Tor's 9040 port doesn't accept http or socks connections.

**Comment by Gedsh** [comment]
Please clarify your issue. You can use port 9040 as transparent proxy, 9050 as socks5 proxy and 8118 as http proxy. All of them are active when Tor is running with the default configuration.

**Comment by oilel** [comment]
> Please clarify your issue.

I want Invizible to connect to a transparent proxy, then through that transparent proxy, Invizible connects to DNSCrypt, Tor, and/or I2P.

**Comment by Gedsh** [comment]
Unfortunately, this is impossible due to the app design.

**Comment by oilel** [comment]
> Unfortunately, this is impossible due to the app design.

Could you explain why the app design doesn't support transparent proxy?
