### ISSUE TITLE
Blacklist on per-app basis

### ISSUE THREAD

**Issue by maninthemiddle01** [Gedsh/InviZible#187]
I blacklisted `*google*`, which works pretty well. But on the other hand I have installed NewPipe for Youtube, which is the only app I would like to allow to connect with google*-Domains. Is it possible to do blacklists on a per-app basis? Then I could block google and only alow it for NewPipe.

**Comment by Gedsh** [comment]
> Is it possible to do blacklists on a per-app basis?

Unfortunately it is impossible. This is a limitation of the Android system. There is nothing I can do about it.

**Comment by nahuhh** [comment]
@maninthemiddle01  you can try to use invizible in conjunctions with rethinkdns

**Comment by maninthemiddle01** [comment]
@nahuhh Thank you very much, I twisted my head around how to do this but didn't come to an answer yet. How could I do this? Because I didn't find an option in RethinkDNS to only set a rule for a specific app...

**Comment by nahuhh** [comment]
@maninthemiddle01  you can try to use invizible in conjunctions with rethinkdns

the firewall settings allow setting global rules and also allow bypassing said rulea for specific applications.

![q00s71ikela05iyo.jpg](https://user-images.githubusercontent.com/50635951/224363049-2808903f-edb8-4d7f-852c-9042531832b0.jpg)

exclude newpipe, forward everything else to invizible 

or use ip and port rules to block google ips, or yse the firewall (left) to configure newpipe manually 
example:
![ywqcr8c7v3ny5y0j.jpg](https://user-images.githubusercontent.com/50635951/224364041-20f4b7fa-642f-431c-a678-9493e5773aad.jpg)

**Comment by nahuhh** [comment]
@Universalizer feel free to

**Comment by nahuhh** [comment]
> > Is it possible to do blacklists on a per-app basis?
> 
> Unfortunately it is impossible. This is a limitation of the Android system. There is nothing I can do about it.

@Gedsh  might be worth looking at rethinkdns' latest release. They just added proper support for blocking domains on a per app basis
![5b1gv2w09xbinet8.jpg](https://user-images.githubusercontent.com/50635951/228935193-a88975cd-cef3-4987-bb3e-c2da73d792b8.jpg)

**Comment by nahuhh** [comment]
> One clarification ; my all previous comments `'for app's FUNCTIONALITY ONLY.'`

The bottom option in screenshot i posted, is this the desired behavior? to block a domain onky when accessed by an specific app
