### ISSUE TITLE
Is it possible to support the DNS-over-QUIC protocol?

### ISSUE THREAD

**Issue by maninthemiddle01** [Gedsh/InviZible#188]
Would be a nice feature :)

**Comment by Gedsh** [comment]
InviZible uses DNSCrypt to handle DNS queries. DNSCrypt supports HTTP/3 (DoH3, HTTP over QUIC) https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

You can enable this feature in the DNSCrypt settings.

In any case, I'm not developing DNSCrypt, so I can't add new features to it.
