### ISSUE TITLE
How do i turn it on...

### ISSUE THREAD

**Issue by yant0** [Gedsh/InviZible#189]
![IMG_2023-02-26-15-19-40-236](https://user-images.githubusercontent.com/80298071/221399845-ebf77e27-a9b1-4e52-85cb-dd1cba278208.jpg)
Bruh

**Comment by Gedsh** [comment]
Funny device. I don't think it will work on such a device anyway.

**Comment by nahuhh** [comment]
Menu, fast settings, start on boot, the restart the phone 

@Gedsh does this sound like it may work?

**Comment by yant0** [comment]
> Menu, fast settings, start on boot, the restart the phone

Have used the app like this for a week. Dev can close this but it still have some ui problems for a small phone.

**Comment by Gedsh** [comment]
>  it still have some ui problems for a small phone

It's too small. It is difficult to make a ui suitable for both ordinary phones and very small ones. At least in the case of the current InviZible interface.
