### ISSUE TITLE
dnscrypt server cert issue

### ISSUE THREAD

**Issue by SamuelP1111** [Gedsh/InviZible#19]
Hi,

I start to use you ARM64 apk on Huawei P10 android 9.0 stock (without root or unlock).
The phone is up to date.
The app version is beta v0.6.0.
Internet connection is WIFI, static ip and high speed without any problems.

I inform some dnscrypt servers i use on other platforms cause cert issue with your app.

If needed i can send logs.

Thanks

regards

Samuel P

**Comment by Gedsh** [comment]
> I inform some dnscrypt servers i use on other platforms cause cert issue with your app.

InviZible uses DNSCrypt to work with DNS. So this could be a DNSCrypt issue. But first send me a log.

**Comment by SamuelP1111** [comment]
Hi,

I havent this issue actually using now the 0.6.2 arm64 version.
But i have only try original servers setting and cs-ch and cs-swe.
