### ISSUE TITLE
Google Pixel 7

### ISSUE THREAD

**Issue by smilzo05** [Gedsh/InviZible#190]
Hi, I can't install invizible pro on my google pixel 7 pro graphene os. The message says it is not compatible with my device.thank you

**Comment by smilzo05** [comment]
> Hi,
> 
> InviZible can be incompatible if your phone is not equipped with an ARM processor. In other cases, it's your phone's problem.
> 
> Heard about this problem when installing from f-droid. You can use other sources.
> 
> In any case, this is not an InviZible issue.

on the google pixel 6 it works, on the pixel7 it doesn't, this is strange.  i didn't use fdroid ,i downloaded from github

**Comment by Gedsh** [comment]
But unfortunately there is nothing I can do about it. The Android system installs the app. Not the app itself. So it doesn't depend on InviZible.

**Comment by Gedsh** [comment]
Also make sure you are installing the arm64 version. Because of this https://discuss.grapheneos.org/d/1985-app-not-compatible-with-your-phone
