### ISSUE TITLE
Please add XMR donation address

### ISSUE THREAD

**Issue by nahuhh** [Gedsh/InviZible#191]
Add an XMR (monero) donation address.
Edit: I see that you already have an xmr address listed on the site, but not on github.
Note: you link to freewallet for monero. Freewallet is a scam. Recommended wallets at the bottom of this post. Feel free to choose one of those.

Also, would be nice if you could add a donation menu item to the app, which lead to a page with links to the various crypto addresses. (Should use URI address)

Example:

``` 
monero:8AFCaKMr2QT6XW5TwcczAcTr8ELFkyhXuGAGdjx8rFfrU2mdKEwVu2511rX1npsYNeND2muvWpMJe7AGYzEaQzDwA5oaNyV
```
 
Wallets: There are a few good options. 
- (3rd party) Cake Wallet / Monero.com for mobile
- if using desktop, the official Monero GUI from getmonero.org
- Feather Wallet is a very good 3rd party wallet for desktop with some more advanced features
- Stack Wallet and Cake Wallet also have betas for desktop

Feather Wallet, Cake Wallet/Monero.com, and Stack Wallet are all trusted 3rd party wallets.

**Comment by Gedsh** [comment]
Thanks for the tips! They really are scammers!
