### ISSUE TITLE
Purpose of binaries 

### ISSUE THREAD

**Issue by nahuhh** [Gedsh/InviZible#192]
https://github.com/Gedsh/InviZible/tree/master/tordnscrypt%2Fsrc%2Fmain%2Fassets

the files listed here. Please explain hy you chose to use them like this?

mp3 format, should be text files. 

App is GPL? where is source code for these files

**Comment by Gedsh** [comment]
> mp3 format, should be text files

Change the extension to zip.

> Please explain hy you chose to use them like this?

Some stupid antiviruses think that if the apk contains a zip file it can be dangerous.

> App is GPL?

Yes.

> where is source code for these files

After changing the extension to zip, I hope you find everything you need.

**Comment by nahuhh** [comment]
Thank you for clarifying!
