### ISSUE TITLE
[Feature request] Add UI support multiple bootstrap DNS addresses

### ISSUE THREAD

**Issue by Searinox** [Gedsh/InviZible#194]
The DnsCrypt TOML bootstrap address setting is a list but the UI treats it as a string. It isn't possible to set multiple bootstrap DNSs.

Editing the TOML file directly is only ever worth it via root and an external editor and then you have to avoid ever going into the InviZible UI because if you try to save any settings - including TOML changes - from there it enforces the UI's stance on the field and reverts it to a single IP address(for example, an edit of "['1.1.1.1:53', '9.9.9.9:53']" is reverted to "['1.1.1.1:53']").

Can you please allow the InviZible UI to treat this field as a list?

**Comment by Gedsh** [comment]
I am adding this to my plans.

**Comment by Gedsh** [comment]
This has been implemented in 24a0d84afbd9aecfddd052d4533c007520f2d3c7
