### ISSUE TITLE
[Help] How to use custom DoH server ?

### ISSUE THREAD

**Issue by Rexadev** [Gedsh/InviZible#195]
I tried adding it to DNSCrypt thinking since the app uses the work interchangebly with DNS but it says SDNS is wrong.

**Comment by Gedsh** [comment]
You should be using SDNS.

https://invizible.net/en/add-custom-dnscrypt-server/

https://dnscrypt.info/stamps

**Comment by Rexadev** [comment]
> https://invizible.net/en/add-custom-dnscrypt-server/

1. What is sdns ?
2. How to use DoH in format `https://dns.nextdns.io/xxx`

**Comment by Gedsh** [comment]
Please follow the links first and then ask questions.

**Comment by Rexadev** [comment]
Thanks @Gedsh
