### ISSUE TITLE
[Discussion - Networking] How does InviZible bypass censorship so good ?

### ISSUE THREAD

**Issue by Rexadev** [Gedsh/InviZible#196]
I use DNAT on router to enforce DNS53 and NextDNS to block rogue DoT and DoH.
Doesn't DNSCrypt need to resolve domain to start using DNS with IP ?

**Comment by Gedsh** [comment]
> Doesn't DNSCrypt need to resolve domain to start using DNS with IP ?

It needs to use plaintext DNS to download the resolvers during the first start. Then it should use its own encrypted connection.

**Comment by Rexadev** [comment]
> It needs to use plaintext DNS to download the resolvers during the first start. Then it should use its own encrypted connection.

Why it doesn't show up in my DNS logs ?

Update - the default 6 DNS servers (adguard-dns, dnscrypt-de-blahdns-ipv4, dnsforge.de, libredns-noads, oszx, sfw.scalway.fr) also when I select only "doh_servers" (dnsforge.de, libredns-noads) are able to bypass DNAT and DNS restrictions without leaving a DNS resolver trace some others i tried aren't able to bypass.

**Comment by Gedsh** [comment]
> Why it doesn't show up in my DNS logs ?

I have no idea.

> able to bypass DNAT and DNS restrictions without leaving a DNS resolver trace

DNSCrypt uses an encrypted connection, so it bypasses all your restrictions.

**Comment by Rexadev** [comment]
> DNSCrypt uses an encrypted connection, so it bypasses all your restrictions.

But it needs to resolve first and have to use the DNS53

**Comment by Gedsh** [comment]
> But it needs to resolve first and have to use the DNS53

This is impossible with DNSCrypt. DNS queries are encrypted and cannot be intercepted or spoofed.

**Comment by Rexadev** [comment]
> This is impossible with DNSCrypt. DNS queries are encrypted and cannot be intercepted or spoofed.

You didn't understand.

I use DNAT that redirects all DNS requests to my NextDNS account and NextDNS blocks and logs rogue DNS.
Unless DNSCrypt has server IP specified (Which pre installed InviZible DNS servers aren't) it needs to resolve the domain before it can be use.  And I should be notified about the domain being resloved on NextDNS logs

**Comment by Gedsh** [comment]
I can't help you with your logs. DNSCrypt uses a cache to avoid using plaintext DNS. You can ask DNSCrypt developer to lower the security and use plaintext DNS.
