### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by PHPoenX** [Gedsh/InviZible#2]
tordnscrypt/build.gradle contains path to your own keystore

While anybody try build it, gradle returns
```Illegal character in opaque part at index 2: C:\KStore\keystore.properties``` on linux; on windows, I think, will be "not found" error.

I suggest add bash script, that will remove some strings from build.gradle or remove strings from config directly

**Comment by Gedsh** [comment]
This is necessary to keep my password and signature in safe place.
But I will try to find a solution with git.

**Comment by Gedsh** [comment]
I hope a solution is found. Please try again with a new config.

**Comment by PHPoenX** [comment]
> keep my password and signature in safe place

i dont demand your signature, but without correctings build failes

**Comment by Gedsh** [comment]
> I hope a solution is found. Please try again with a new config.

You tried?

**Comment by PHPoenX** [comment]
@Gedsh Now all working!
