### ISSUE TITLE
dnscrypt issue with leak test

### ISSUE THREAD

**Issue by SamuelP1111** [Gedsh/InviZible#20]
Hi,

I start to use you ARM64 apk on Huawei P10 android 9.0 stock (without root or unlock).
The phone is up to date.
The app version is beta v0.6.0.
Internet connection is Wifi, static ip and high speed without any problems.

I use Wifi and, when i'm using wifi, i've to set a dns. The dns i use is cloudflare (1.1.1.1).

I use ipleak test or dns leak test on net for verify the servers i connect too.

I inform this is a curious issue.

The dnscrypt servers i select are working and i see there ip and localizations but, the cloudflare servers appear too...
If i start the test 2 or three times, there is less and less cloudlfare servers and last time, there are only dnscrypt servers.

Thanks for your app.

regards

Samuel P

**Comment by Gedsh** [comment]
Have you disabled the built-in DNS-over-HTTPS feature in Android settings? Did you clear your browser cache before the test? Which browser are you using?

**Comment by SamuelP1111** [comment]
Hi Gedsh,

I don't know how to disabled the doh feature in Android... I don't use it in firefox.
I clear cache each time i leave firefox (i've setted it for this).

I have made a try today with 0.6.2 arm64 beta.
I use only two resolver with relays.
cs-ch and cs-cse using cs-ch anon and cs-swe anon.

I use wifi and i've try too with LTE.

There are unknown servers, not dnscrypt not google (lte) and not cloudflare(the dns i must set for WIFI).

Screenshot

WIFI:
![Screenshot_20200214_132854_org mozilla firefox](https://user-images.githubusercontent.com/60618485/74533564-2cfda180-4f32-11ea-9c38-5af16ce5da09.jpg)
![Screenshot_20200214_132918_pan alexander tordnscrypt](https://user-images.githubusercontent.com/60618485/74533577-325aec00-4f32-11ea-88f5-371d074bb907.jpg)

LTE:
![Screenshot_20200214_133330_org mozilla firefox](https://user-images.githubusercontent.com/60618485/74533616-44d52580-4f32-11ea-8ce4-c71e9390946f.jpg)

regards

SamuelP
