### ISSUE TITLE
App is tripping up IpReachabilityMonitor with LOST_PROVISIONING

### ISSUE THREAD

**Issue by Searinox** [Gedsh/InviZible#204]
This issue is not new. It's persisted on my Moto G100 with LineageOS across a factory reset. It is intermittent and causes periodic WiFi dropouts. For a while I went without the app until I decided I need it more than I don't. I only use DNScrypt. But whenever it's active this happens with my device.

The error in the bug title appears in the logs every few minutes. It will never stop unless I stop the app altogether. I've tried many things but only avoiding InviZible altogether ever worked. Either way I just kept using it and made peace with the problem.

From what I gather that component can't reach the default gateway or something. I also see some reports that it may have affected some version or another of LOS. Afirewall+ does not trigger this. In fact I've not seen another app that does this.

Absent a decisive fix, would it be possible for you to include a workaround that one can enable/disable in the settings please? I would appreciate it so much. I'm not sure what that workaround would be, maybe disabling IpReachabilityMonitor or whatever, I tried to do that myself but didn't find enough info to do so. Clearly the component doesn't like or understand something about InviZible's MO so best it would just shut up and not get involved in assessing the network in the first place.

**Comment by Gedsh** [comment]
> The error in the bug title appears in the logs every few minutes.

What error? Please better send screenshots.

> From what I gather that component can't reach the default gateway or something.

What component? Are you using a third party firewall or firewall in InviZible?

**Comment by Searinox** [comment]
The firewall was the one included with InviZible, no third party. And the component I'm referring to is the IpReachabilityMonitor, that comes with the OS.

Regrettably I can no longer provide info as I have uninstalled InviZible and found a working solution in the form of a DnsCrypt Magisk module. So I guess it's up to you whether you want to leave this issue open or not.
