### ISSUE TITLE
dns and tor disable incoming ports

### ISSUE THREAD

**Issue by nahuhh** [Gedsh/InviZible#207]
Use case: running a node in termux, need incoming connections
(should be able to reproduce with something like ssh)

1. Enable tor i2p and dns
2. Try to telnet to the ip port
3. Fail
4. Disable tor and dns, leave i2p enabled 
5. Success
6. Disable just tor, or just dns 
7. Fail

Android 10 
inviz version 1.8.2

**Comment by nahuhh** [comment]
Update: 
disabling "block ipv6" fixed it. 

not sure if intended behavior. I am using ipv4 binds (192.168.x.x)

**Comment by Gedsh** [comment]
> running a node in termux, need incoming connections

This is due to the Android VPN service, which is used to redirect device traffic to DNSCrypt, Tor, and I2P. It usually cannot let incoming connections through. When only I2P is enabled, the VPN service is disabled. That's why you have a successful connection.

> disabling "block ipv6" fixed it

It is very strange. This feature just blocks ipv6. Nothing more.

**Comment by nahuhh** [comment]
I can still reproduce
ipv4 incoming connections are indeed working as long as keep ipv6 enabled. (and not working with `block ipv6` enabled)

ive only tested on wifi btw

**Comment by Gedsh** [comment]
In the latest beta 1.8.3 is the same behavior?

**Comment by nahuhh** [comment]
will test over the next 24-48hrs and let you know. 
Thanks!

**Comment by Gedsh** [comment]
> ipv4 incoming is blocked regardless of ipv6 setting

Actually this is the correct behavior. And the problem is related to Android VPN service. It does not allow incoming connections. Version 1.8.3 routes all android traffic through the VPN service. Version 1.8.2 routes all ipv4 traffic and only ipv6 unicast. Most likely it helped.

**Comment by Gedsh** [comment]
>  is therr anyway to preserve the behavior from 1.8.2 

Unfortunately no. This can lead to leaks through ipv6.

> not having ipv4 incoming connections is heartbreaking for all of my use cases

Currently I don't know how to prevent leaks and allow incoming connections. Probably it's impossible.

**Comment by nahuhh** [comment]
another update - incoming available seems like an android bug perhaps.

while incoming is disabled with the latest invizible update, i am able to perform a workaround to get it working again.

1. Go to phone settings > connections > vpn
2. tap + hold on the vpn or press the gear button (depending on os)
3. Set vpn to "always on"
4. Leave the setting and reopen it
5. Disable "always on"
6. Incoming available again.

Not sure if this is good or bad (leaking?), but works for my use case

**Comment by nahuhh** [comment]
> > running a node in termux, need incoming connections
> 
> This is due to the Android VPN service, which is used to redirect device traffic to DNSCrypt, Tor, and I2P. It usually cannot let incoming connections through. When only I2P is enabled, the VPN service is disabled. That's why you have a successful connection.
> 
> > disabling "block ipv6" fixed it
> 
> It is very strange. This feature just blocks ipv6. Nothing more.


update: 
running v2.0.0 and v6.1.0
in vpn mode with _only_ dnscrypt enabled, incoming is working. 

Example use case is the app kdeconnect or syncthing

enabling tor or i2p cause incoming to fail
