### ISSUE TITLE
[Question] What is "nextdns-ultralow" server ?

### ISSUE THREAD

**Issue by Rexadev** [Gedsh/InviZible#208]

**Comment by Gedsh** [comment]
I have no idea. InviZible uses servers provided by the upstream dnscrypt project. Try asking there https://github.com/DNSCrypt/dnscrypt-resolvers

**Comment by Rexadev** [comment]
@Gedsh What about DoT ?

**Comment by Gedsh** [comment]
@Rexadev https://github.com/Gedsh/InviZible/issues/15
