### ISSUE TITLE
Define tunnels for i2pd

### ISSUE THREAD

**Issue by xp499** [Gedsh/InviZible#21]
Hello, sorry if i'm dumb and this is an easy option and is already implemented and or available but, how we can define tunnels for i2pd in Invizible Pro? Thank you for your time and again I beg your pardon if this is stupid.

Greetings.

**Comment by Gedsh** [comment]
Hello. 
There is no such option in the GUI currently. It is planned.

**Comment by xp499** [comment]
Thanks.
You can close this issue then, if you consider.

**Comment by Gedsh** [comment]
This feature is planned. I leave it open so as not to forget.

**Comment by Gedsh** [comment]
Added options for editing configuration files, including tunnels.conf
