### ISSUE TITLE
omWeather cannot access internet

### ISSUE THREAD

**Issue by takiainen** [Gedsh/InviZible#210]
App named omWeather (from F-Droid) cannot access internet unless I allow internet access for it AND "kernel" from firewall settings. 

 I am using latest invizible from F-Droid on microg lineage 20. I am using VPN mode. From dns log you can see that "kernel" tries to connect to weather api as well as omWeather.

Kernel -> 202.61.229.161
omWeather -> 202.61.229.161

**Comment by Gedsh** [comment]
"Kernel" is traffic without owner's uid. It has to do with the kernel of your phone. Unfortunately, there is nothing I can do about it. InviZible uses data provided by the Android API, which is provided by the kernel.
