### ISSUE TITLE
The excluded app's VPN can't access Internet.

### ISSUE THREAD

**Issue by oilel** [Gedsh/InviZible#212]
Tor and I2P are blocked in some countries, and require a V2Ray or Clash proxy to connect to. I let Invizible to exclude the proxy app, and let Invizible use VPN mode, but the excluded app supports both proxy mode and VPN mode too (I used proxy mode of that app, so Invizible can use VPN mode). After some days, I tried to use the excluded app directly by its VPN mode, but Android cannot access Internet; I restored the app setting to use its proxy mode, then use Invizible's VPN mode, Android will be able to access Internet. Which means the excluded app cannot function standalone. Furthermore, [Termux](https://github.com/termux/termux-app) is a terminal emulator for Android, it cannot ping any sites, e.g.,
```
ping -c 3 github.com
```
But the browser can access GitHub.

**Comment by oilel** [comment]
I bought a VPS and ping it, the administrator of VPS told me that it responded the ping. So the excluded app can send messages to Internet, but while I use excluded app's proxy mode and Invizible's VPN mode, it can't receive ping responses.

**Comment by Gedsh** [comment]
> Tor and I2P are blocked in some countries, and require a V2Ray or Clash proxy to connect to.

You can use Tor bridges https://github.com/Gedsh/InviZible/wiki/Adding-new-bridges

Or you can use Tor over VPN https://github.com/Gedsh/InviZible/wiki/Tor-over-VPN

> I tried to use the excluded app directly by its VPN mode

You cannot use two VPN apps on android at the same time. This is a system limitation.

**Comment by oilel** [comment]
> You cannot use two VPN apps

I used the excluded app's VPN mode without running Invizible.

**Comment by Gedsh** [comment]
> I used the excluded app's VPN mode without running Invizible (so only one app is running),

If inviZible is not running, it cannot affect the network connection.

> started Invizible's VPN mode, it immediately can receive websites' responses

Check if you have "Always on VPN" and "Block connections without VPN" enabled in your phone settings.

**Comment by oilel** [comment]
> Check if you have "Always on VPN" and "Block connections without VPN" enabled in your phone settings.

Even if I deleted Invizible's VPN setting, the web browser cannot receive responses with excluded app's VPN mode. I use [SagerNet](https://f-droid.org/en/packages/io.nekohasekai.sagernet/) as the excluded app. The browser can receive responses when Invizible's VPN mode is enabled.

**Comment by Gedsh** [comment]
In any case, the problem is not with InviZible. It is in your phone's rom or in your phone's settings. InviZible cannot affect the connection if it is stopped. And I can't help you with that.

**Comment by oilel** [comment]
@Gedsh I excluded Termux, which is a terminal emulator for Android, from Invizible's VPN mode, so Termux won't go through Invizible. But it cannot receive ping packets,
```
ping -c 3 distrowatch.com
PING distrowatch.com (82.103.129.71) 56(84) bytes of data.

--- distrowatch.com ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2000ms
```
Curl can receive response:
```
curl distrowatch.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>                                               <title>302 Found</title>                                   </head><body>                                              <h1>Found</h1>                                             <p>The document has moved <a href="https://distrowatch.com/">here</a>.</p>                                            </body></html>
```
I did not enable "Block connections without VPN", while Termux can use curl to receive responses, it cannot use ping to receive responses.
