### ISSUE TITLE
Simultaneous testing of DNS-servers' latency

### ISSUE THREAD

**Issue by Korb** [Gedsh/InviZible#213]
... like [DNS Benchmark](https://www.grc.com/dns/benchmark.htm). This will significantly speed up the connection to the Internet when you select several DNS services in the application settings.

**Comment by Gedsh** [comment]
I am not developing DNSCrypt itself. You should better submit this issue to the upstream DNSCrypt project https://github.com/DNSCrypt/dnscrypt-proxy
