### ISSUE TITLE
Google Play not working when using DNSCrypt

### ISSUE THREAD

**Issue by Korb** [Gedsh/InviZible#214]
After successfully connecting to various DNS servers, the Google Play app reports a connection error "Something went wrong. Try again" / "No Internet connection. Make sure Wi-Fi or mobile data is turned on, then try again". When trying to update apps installed via Google Play, I get the error "Pending downloads. Couldn't update". At the same time, in other applications, Internet functions work flawlessly. After disabling DNSCrypt, Google Play works fine.

I've tried different DNS servers and Google Play doesn't work with any of the ones I've tested.

InviZible Pro 1.8.3 from F-Droid.

```
OS version: Funtouch OS 13 Global
Model: V2153 (Vivo T1 4G)
Hardware version: MP_0.1
Build number: PD2201OF_EX_A_13.1.14.5.W20.V000L1
Baseband version: MPSS.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.99
Kernel version: 4.19.157-perf+ #1 Tue Mar 7 11:06:28 CST 2023
Compile time: 7 Mar 2023 05:55:18
Android security update: 1 March 2023
Google Play system update: 1 March 2023
```

**Comment by Gedsh** [comment]
Go to Menu -> DNSCrypt Settings and press Erase blacklist, Erase IP blacklist.

Go to Menu -> Fast Settings and select only non-filtering DNSCrypt servers.

If this does not help, the problem is in your phone. The Google Play app may not see an internet connection when a local VPN is active.

**Comment by Korb** [comment]
> Go to Menu -> DNSCrypt Settings and press Erase blacklist, Erase IP blacklist.
> 
> Go to Menu -> Fast Settings and select only non-filtering DNSCrypt servers.

Done.

> Disable the firewall if you are using it.

I do not use a firewall on smartphone.

> If this does not help, the problem is in your phone. The Google Play app may not see an internet connection when a local VPN is active.

Apparently it is. When DNSCrypt is enabled, the Google Play application itself works, it searches for applications, it displays application descriptions, but when I try to download updates for installed applications, an error consistently appears. The problem disappears by stopping DNSCrypt.

Can I close this ticket as _not planned_?

**Comment by Gedsh** [comment]
> Can I close this ticket as not planned?

Of course.
