### ISSUE TITLE
[Bug] InviZible cannot be included in backup

### ISSUE THREAD

**Issue by A-7666** [Gedsh/InviZible#216]
Hello, and thank you very much for the software :-) 

There is a bug that doesn't allow backup.

After I run Seedvault, I can see InviZible present in the "programs that do not allow backup" list.

This is very unfortunate. Could you fix this?

**Comment by Gedsh** [comment]
> Hello, and thank you very much for the software :-)

Hello. You are welcome.

> There is a bug that doesn't allow backup.

It's not a bug. It's a feature )

You can use InviZible's built-in backup. A regular android backup cannot save all the necessary settings, since most of them are stored in configuration files, and not in the android shared preferences. Restoring only shared preferences without configuration files may cause the app to failure.

**Comment by A-7666** [comment]
> You can use InviZible's built-in backup

Ya it's great it's possible to do it this way, but it's very inconvenient,
imagine if all programs were like that, and then it would be backuping 100s of programs.
System backup is made for this. :slightly_smiling_face: 

> A regular android backup cannot save all the necessary settings

Does this apply to the built-in Seedvault backup?
Because as far as I've seen, it should be ok as it includes system settings, calls/sms/contacts program settings and programs (akps) themselves in its backups

**Comment by Gedsh** [comment]
> System backup is made for this.

It will not work for InviZible correctly as I mentioned above.

> Does this apply to the built-in Seedvault backup?

Without root, you can't save all the necessary app files, no matter what app you're using.

**Comment by A-7666** [comment]
Ook, thanks

Hope some solution for this could be found one day

**Comment by Gedsh** [comment]
I don't think so. Use root or use the built-in InviZible backup.
