### ISSUE TITLE
Snapchat not working 

### ISSUE THREAD

**Issue by mxwmnn** [Gedsh/InviZible#217]
If I enable Dnscrypt and TOR. Snapchat can't send any snap it always fail. I can't even send messages. I only get notifications. 

Thought I don't need a VPN anymore but is snapchat Tor traffic blocking. Without tor it works

**Comment by Gedsh** [comment]
> Without tor it works

Looks like Snapchat is blocking Tor users. The only reason is that they want to track you.

The only solution is VPN over Tor https://invizible.net/en/vpn-over-tor-proxy-mode/

**Comment by mxwmnn** [comment]
Okay thanks
