### ISSUE TITLE
Quick question about dnscrypt and app exclusion

### ISSUE THREAD

**Issue by pedrom34** [Gedsh/InviZible#218]
Hi!
I really like invizible, but I'm facing an issue related to my setup.
I use adguard-home at home, I have generated a dns-stamp for adguard.mydomain.tld. I also have other services that are self-hosted. In particular a vpn server that I reach with mydomain.tld. In order to connect from my home to my services, I have a dns rewrite in adguard-home that returns mydomain.tld to the LAN address of my server.

When Invizible is launched, OpenVPN cannot reach my VPN server. I guess this is because Adguard-Home responds with a LAN address to the domain.tld request.

So my question is: Is it possible to create an exclusion for OpenVPN so that it does not use DNSCrypt? Kind of the same way there are application exclusions for Tor.

Thanks!

**Comment by Gedsh** [comment]
Hi,

Thanks for your nice words!

> Is it possible to create an exclusion for OpenVPN so that it does not use DNSCrypt?

Unfortunately it is impossible. All apps use DNSCrypt DNS when it is running.

It is impossible to separate DNS traffic from different apps on android.

**Comment by pedrom34** [comment]
That's what I thought... Well, anyway. I'll look for another solution to use InviZible with my current configuration :)

Thanks for your answer!

**Comment by Gedsh** [comment]
You are welcome.
