### ISSUE TITLE
[Question] Is there possible to use i2p with tor? 

### ISSUE THREAD

**Issue by Mishasama** [Gedsh/InviZible#219]
The I2P protocol seems to be severely blocked in some areas, but TOR can still connect at this time. I wonder if it is possible to let I2P connect through TOR?

**Comment by Gedsh** [comment]
It is possible!

Go to Menu -> I2P settings and disable ssu2 as Tor does not support UDP. Then enable ntcpproxy. Ntcpproxy address should be http://127.0.0.1:8118 to use the local Tor http proxy.
