### ISSUE TITLE
obfs4proxy fails for some AOSP Q 10/Lineage OS 17/17.1 builds

### ISSUE THREAD

**Issue by xp499** [Gedsh/InviZible#22]
Reports a warning and tor don't get pass bootstrapped more than of 0%:

Managed proxy at '/data/app/pan.alexander.tordnscrypt-a_n6lXtuoQDHhtNwim5iaA==/lib/arm64/libobfs4proxy.so' reported: error: executable's TLS segment is underaligned: alignement is 4, needs to be at least 32 for ARM Bionic

Now i'm pretty sure this is an issue of early developments of LOS/AOSP Q builds as it talks about ARM Bionic library but i'm not certain and i'm just reporting for you to know.

Greetings.

**Comment by Gedsh** [comment]
This is issue of obfs4proxy (in fact, this is a common problem for all projects written in Golang) on android 10. We are waiting for a solution. https://trac.torproject.org/projects/tor/ticket/32303

**Comment by xp499** [comment]
Oh, didn't know.

Thanks for the info.

May you get this issue open until is solved, for reference?

**Comment by Gedsh** [comment]
No problem.  I often answer this question in the Telegram group.

**Comment by Gedsh** [comment]
It seems like required to build the arm64 binary to solve the issue.

**InviZible Pro 0.7.0 already has it.**

For those who want to do this on their own.

I used this source code: https://github.com/Yawning/obfs4

Requires android NDK and the latest Go compiler. This is currently 1.14.

I used Windows with PowerShell and the built-in Android Studio NDK.

Example commands for compiling your own file:

$env:GOPATH=c:\Go\bin\go.exe
$env:GOOS='android'
$env:GOARCH='arm64'
$NDK="C:\Users\Alexander\AppData\Local\Android\Sdk\ndk-bundle"
$env:Path += ";$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin"
$env:CCX="$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android29-clang++"
$env:CC="$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android29-clang"
$env:CGO_ENABLED=1

cd C:\Go\My\obfs4-obfs4proxy-0.0.11\obfs4proxy
go clean
go build -ldflags="-s -w" -o $env:GOPATH/android-armv64/obfs4proxy
