### ISSUE TITLE
Invizible Pro showing DNSCrypt and other modules not installed

### ISSUE THREAD

**Issue by notahomosapien** [Gedsh/InviZible#224]
Hi,
I just installed the latest version of Invizible Pro from Github (1.9.0, Beta) and Invizible pro is showing that DNScrypt and other modules are not installed
![Screenshot_2023-07-13-13-47-51-41](https://github.com/Gedsh/InviZible/assets/139213261/3b8797c4-b44d-4a22-8888-a29e4c9cb07f)

**Comment by notahomosapien** [comment]
Update: Clearing app data of Invizible Pro immediately fixed the problem.

**Comment by Gedsh** [comment]
I hope it is fixed in 1.9.2 beta. If not, please re-open the issue.
