### ISSUE TITLE
Add lyrebird PT

### ISSUE THREAD

**Issue by A-Shahbazi** [Gedsh/InviZible#226]
The project supports obfs3,obfs4 and meek bridges but uses alternative ways to obfuscate traffic. I compiled the project for the desktop and many previously non-working bridges started working for me.

Here's the link: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird

**Comment by Gedsh** [comment]
Thank you. You made my day!

Lyrebird is a fork of obfs4proxy already used in InviZible. But this fork is reimplementing utls support for meek_lite. This is what I planned to do today. So it's just in time.

The 1.9.2 beta uses a lyrebird.

**Comment by A-Shahbazi** [comment]
Wow!
What a nice coincidence!

So, let me draw your attention to a project I encountered recently which uses a clever way for defeating HTTPS traffic inspection. It uses Client Hello fragmentation and DOH(which is already implemented in InviZible).

Here's the link to the project: https://github.com/GFW-knocker/gfw_resist_HTTPS_proxy
It is written in python, though, and I'm not sure if it can be implemented in Invizible.

**Comment by Gedsh** [comment]
> It is written in python, though, and I'm not sure if it can be implemented in Invizible.

Unfortunately not.
