### ISSUE TITLE
same crypto address for usd pax & ether?; paypal & patreon missing 

### ISSUE THREAD

**Issue by ghost** [Gedsh/InviZible#228]
@Gedsh
* ```0xdA1Dd53FE6501140E3Dcd5134323dfccF20aD536``` is same for **USD PAX** & **Ether** @ https://github.com/Gedsh/InviZible#donations
* **paypal** & **patreon** given @ https://invizible.net/en/donate/ are still valid?

**Comment by Gedsh** [comment]
> 0xdA1Dd53FE6501140E3Dcd5134323dfccF20aD536 is same for USD PAX & Ether

Yes.

> paypal & patreon given @ https://invizible.net/en/donate/ are still valid?

Certainly!
