### ISSUE TITLE
Snowflake PT support

### ISSUE THREAD

**Issue by xp499** [Gedsh/InviZible#23]
Is it factible to deploy/enable some option for using an alpha/dev version of Tor in order to support/provide Snowflake's PT (as client, of course)?

Some related links:
https://snowflake.torproject.org/
https://trac.torproject.org/projects/tor/wiki/doc/Snowflake
https://gitweb.torproject.org/pluggable-transports/snowflake.git/tree/client/README.md

Greetings.

**Comment by Gedsh** [comment]
This will increase the size of the Invizible. I think it's better to wait for the official release of the beta version at least. And if Snowflake uses WebRTC, it may be unsafe.

**Comment by xp499** [comment]
You can always override binaries. Or download them from remote location.

It's not unsafe. It just uses WebRTC traffic as obfs4proxy uses obfs4 to avoid DPIs and traffic analysis and censhorship. Under WebRTC goes tor traffic (with its consequent ciphering).

Also the WebRTC relays are donated by volunteers. You are only a WebRTC client. You don't run any WebRTC software except for that part. I don't think WebRTC clients are insecure if Tor project decided to use them.

**Comment by Gedsh** [comment]
> You can always override binaries. Or download them from remote location.

No. Starting with android 10, it is no possible to execute binary files from app data folder. InviZible is already prepared for this and executes binary files from application native library folder, where is quite difficult to replace files and only with root.

> It's not unsafe... 

Thanks for the info.

**Comment by xp499** [comment]
Ok, np.

Althought apps that get root support normally offer more advanced options to their users. At least to start getting and testing tor builds to check how snowflake's PT behaves.

**Comment by Gedsh** [comment]
If you have root and knowledge, you can directly modify tor.conf in /data/data/pan.alexander.tordnscrypt/app_data/tor/tor.conf and replace tor binary in /data/app/pan.alexander.tordnscrypt/lib/.../libtor.so

**Comment by xp499** [comment]
Ok, thanks for pointing me in the right direction.

My pleasure.

**Comment by Gedsh** [comment]
Implemented.
