### ISSUE TITLE
Add "MiddleNodes" option to Tor Settings

### ISSUE THREAD

**Issue by ike08** [Gedsh/InviZible#230]
It would be nice to specify MiddleNodes in Tor Settings with an Android preference. Or, it would be nice to edit the torrc file from the app to customize client options without needing a dedicated Android preference for each option.

**Comment by Gedsh** [comment]
> It would be nice to specify MiddleNodes in Tor Settings with an Android preference.

I have no plans in implementing this. I don't see any benefit in this option. Tor provides the best anonymity when it can use any nodes.

> it would be nice to edit the torrc file

Menu -> Tor Settings -> Edit tor.conf directly. This feature is not available in the Play Store version.
