### ISSUE TITLE
How to use personalDNSfilter with Invizible on root mode?

### ISSUE THREAD

**Issue by Murilogs1910** [Gedsh/InviZible#235]
I want to use personalDNSfilter to filter the DNS requests, but I just can't get it to work while using Invizible on root mode. Is there any guide for that?

**Comment by Gedsh** [comment]
You can only use proxy mode with personalDNSfilter.

https://github.com/Gedsh/InviZible/wiki/InviZible-and-personalDNSfilter

**Comment by Gedsh** [comment]
> Then I don't get to use the firewall, and not all apps can be routed through Tor.

This is true.

> If there was an option for Invizible to not get the DNS requests

Unfortunately, there is no such option in InviZible. For your use case, I can suggest using InviZible on its own, without pDNSf.
