### ISSUE TITLE
И тут можно ускорить билд

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [Gedsh/InviZible#236]
https://github.com/Gedsh/InviZible/blob/master/tordnscrypt/libs/build#L173

`make -j$(nproc)`

**Comment by Gedsh** [comment]
Спасибо за предложение. Этот скрипт писала команда f-droid. Они же и пользуются им. Лучше его не трогать. У них и так постоянно проблемы с копиляцией.

Я лично компилю локально и использую все процессоры конечно же.
