### ISSUE TITLE
Versions?

### ISSUE THREAD

**Issue by JonnyTech** [Gedsh/InviZible#237]
There are multiple versions which is confusing. Can someone please explain the difference?
```
Latest release: InviZible Pro Stable v6.4.0
- Invizible_Lite_ver.6.4.0.apk
- Invizible_Lite_ver.6.4.0_arm64.apk

InviZible Pro Beta v2.0.1
- Invizible_Pro__beta_ver.2.0.1.apk
- Invizible_Pro__beta_ver.2.0.1_arm64.apk 
```
Why the big difference in version numbers?
How is lite version different?
Can one upgrade between types?
Do the Google Store / GitHub / Izzy / FDroid builds offer different features?

**Comment by Gedsh** [comment]
There is a beta version and a stable version of InviZible Pro. The beta version is intended to test new features. The stable version is intended for everyday use. Currently beta version is 2.0.1. The stable version is 6.4.0.

There are two types of stable version. Lite is free stable version. The premium stable version is a gift for those who support the project. The premium version has a built-in auto-update feature and has no project support reminder compared to the Lite version. The beta version is always free.

The arm64 version is for arm64 processors only. The other version is armv7a and can be installed on both arm64 and armv7a devices.

> Can one upgrade between types?

Nope.

> Do the Google Store / GitHub / Izzy / FDroid builds offer different features?

The Play Store and the main F-Droid repository contain a stable version. Ad blocking is not available in the Play Store version as it is not allowed there. The Izzy repository contains a beta version. Github contains both stable and beta versions. There are no differences in the versions, except for the Play Store version, as already mentioned.
