### ISSUE TITLE
Cannot exclude termux from Tor

### ISSUE THREAD

**Issue by detectingdragon77** [Gedsh/InviZible#238]
Hello, I cannot seem to update my repo list on termux whenever Invizible VPN is turned on. I went to fast settings to try to exclude it, but its not listed in the exclude app toggler page. Using latest invisizible beta (v2.0.2)

**Comment by Gedsh** [comment]
Hello, If an app is not listed, this means that particular app does not have internet permission and cannot access the internet directly.

But Termux has this permission, so you can find it in the list. Check the list carefully.

**Comment by detectingdragon77** [comment]
> Hello, If an app is not listed, this means that particular app does not have internet permission and cannot access the internet directly.
> 
> But Termux has this permission, so you can find it in the list. Check the list carefully.

Termux does show an internet permission, I looked manually on the invisible exclude list, as well as searching for termux in the search field. I tried the stable and beta versions of invisible and received the same issue.

**Comment by Gedsh** [comment]
I can't confirm your issue on my phones.

![Screenshot_1_InviZible Pro](https://github.com/Gedsh/InviZible/assets/48843569/834ea8b9-8941-4fd3-a01d-d936786206b6)

**Comment by detectingdragon77** [comment]
> I can't confirm your issue on my phones.
> 
> ![Screenshot_1_InviZible Pro](https://private-user-images.githubusercontent.com/48843569/294495020-834ea8b9-8941-4fd3-a01d-d936786206b6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzE2MTMsIm5iZiI6MTcwNDQ3MTMxMywicGF0aCI6Ii80ODg0MzU2OS8yOTQ0OTUwMjAtODM0ZWE4YjktODk0MS00ZmQzLWEwMWQtZDkzNjc4NjIwNmI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE2MTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NDBlMGZhYTdiNzZiZDAzOWU1MzU0ODhjMWM0ZDFiODkwOTBjMTAxYTM4N2NmNGRhMmVkOTc2N2MyY2VkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8F0Zj-LpJXp1I-oX-N2lv1SPGOGtulEGv71PHdZzyt4)

Interesting, I am running a custom rom, which is probably the problem if its working for everyone else. I will close the ticket.
