### ISSUE TITLE
local VPN mode: TCP forwarding to UDP

### ISSUE THREAD

**Issue by Pantyhose-X** [Gedsh/InviZible#239]
Forwarding all tcp forwarding to udp.
local VPN Redirecting traffic to UDP outgoing 
UDP can avoid some network censorship. Tor and I2P not enabled
Nowadays, browsers have also implemented http3 , which is based on udp.

### Proposed solution
an option: Enable and disable “TCP forwarding to UDP ”

**Comment by Gedsh** [comment]
>  “TCP forwarding to UDP ”

TCP cannot be forwarded to UDP without remote server support. Tor also does not support UDP.

> UDP can avoid some network censorship.

This is usually not true.
