### ISSUE TITLE
Hidden Service v3 support

### ISSUE THREAD

**Issue by xp499** [Gedsh/InviZible#24]
Is there any plans of supporting hidden service v3 host addresses?

Just to knoe ab.

Thanks for your time, support and dedication.
We really appreciate it.

Greetings

**Comment by Gedsh** [comment]
But it already works. Test with this link:
http://lldan5gahapx5k7iafb3s4ikijc4ni7gx5iywdflkba5y2ezyg6sjgyd.onion
