### ISSUE TITLE
separate exclude option

### ISSUE THREAD

**Issue by GreenArchiveForever** [Gedsh/InviZible#241]
hi pls consider to allow user to exclude app or website from only TOR or Dnscrpypt

bcs sometime while i do self troubleshooting one of invizible pro module can causing problem and it's impossible to excluded app from one of them

thanks 🙏

**Comment by Gedsh** [comment]
Hi,

>  allow user to exclude app or website from only TOR

Menu -> Fast settings -> Exclude Apps

> or Dnscrpypt

It is impossible to separate DNS traffic from different apps on Android.
