### ISSUE TITLE
[Request/Suggestion] Option to hide disabled Apps and Icons from Firewall/Tor Routing List

### ISSUE THREAD

**Issue by TotallyAvailable** [Gedsh/InviZible#242]
Not exactly sure what it comes down to besides the lack of necessity or demand but besides Droid-ify telling me to keep updating disabled (by choice/currently unused) apps, AFWall keeps listing disabled Apps as well. AppManager does appear to lack the option to hide them (by wish/active decision) as well (which does make sense).

The Play Store on the other hand doesn't appear to have any issues with correctly filtering out disabled (via System, root or systemless debloat) Apps.

Does it actually require a bit more work than I think or is it something easily implementable if there's demand shown ?

Additionally:
- an option to hide App Icons (Firewall/Tor Routing)
- caching of the previously loaded (within the session at least) App List/State.

Just thoughts on possibly useful enhancements.

(Looking at the "Invizible Pro uses" section, Netguard does indeed allow for the hiding of Disabled Apps, not the hiding of Icons unfortunately which AFWall does...)

**Comment by Gedsh** [comment]
> Option to hide disabled Apps and Icons

I don't think this is a good idea as the user might forget to make the right choice for these apps. And then enable them accidentally or if it is a system app, the phone may enable it on its own. Especially on roms like MIUI.
