### ISSUE TITLE
Spotify is not working

### ISSUE THREAD

**Issue by K4Z3R0** [Gedsh/InviZible#250]
As the title states both spotify and spotify lite are not working and kept saying spotify is offline when using InviZible

**Comment by Gedsh** [comment]
Spotify can block Tor users because it wants to track them. You can try excluding it from Tor in Fast settings.

**Comment by Gedsh** [comment]
> I'm not even using Tor

This means two things. Or DNSCrypt blocks some trackers needed for Spotify to work. Or Spotify just doesn't want to work when the VPN is turned on.

Which DNSCrypt servers do you use?

**Comment by Gedsh** [comment]
Try using only non-filtering servers. If it doesn't help, then the only reason is that Spotify detects the local VPN and doesn't allow you to use it. There's nothing I can do about it.
