### ISSUE TITLE
Icon in fastlane needs update

### ISSUE THREAD

**Issue by linsui** [Gedsh/InviZible#251]
The icon is changed, please also update https://github.com/Gedsh/InviZible/blob/master/fastlane/metadata/android/en-US/images/icon.png. Thanks!

**Comment by Gedsh** [comment]
Thank you for reminding. https://github.com/Gedsh/InviZible/commit/2c76b276324a3025131bc71646ae1808485aa1fa

**Comment by linsui** [comment]
Thanks!
