### ISSUE TITLE
Integrate Wireguard

### ISSUE THREAD

**Issue by Brajesh3** [Gedsh/InviZible#254]
How about integrating wireguard as alternative to *tor*.
Using Tor module makes everything slow & have to experience captcha hell so we can't always use tor for every application & when split tunneling our connection for some app to wireguard will help to mask real ip for the remaining apps that not using tor

It is possible or not i don't know but in [Rethinkdns](https://github.com/celzero/rethink-app) app you can use many different configuration or *wireguard tunnel* for many different app.
Like 1 config for some no. of apps
Other config for remaining apps or just like

**Comment by Gedsh** [comment]
No VPN can provide the same level of privacy and anonymity as Tor. If you need privacy and anonymity, use Tor with the app. If not, exclude this app from Tor and use a direct connection. DNSCrypt is used for all apps if enabled and provides security.

You can also use InviZible with a VPN https://github.com/Gedsh/InviZible/wiki/Using-InviZible-alongside-with-VPN

So I don't see the point in adding any VPN.
