### ISSUE TITLE
WebTunnel bridge line formatting issue

### ISSUE THREAD

**Issue by gusgustavo** [Gedsh/InviZible#256]
Hi, some users reported that they can only use WebTunnel bridges in Invizible-pro after removing the version (`ver=0.0.1`) of the bridge line.

The WebTunnel bridge format is:

```webtunnel [fake-IPv6]:443 bridgefingerprint url=https://some/domain/secret ver=0.0.1```

Could you fix this? :)

**Comment by Gedsh** [comment]
Hi. Already fixed and will be available in the next version. https://github.com/Gedsh/InviZible/commit/6619c52ed3611db02d0b99dde6f035e5aa4f1cf4

It's funny, I fix issues before they are opened :)
