### ISSUE TITLE
[Feature request] Yggdrasil access

### ISSUE THREAD

**Issue by anedroid** [Gedsh/InviZible#257]
Yggdrasil is an overlay network like I2P, providing global-routable 200::/7 IPv6 pool. It's able to forward any kind of IP packets and all traffic to destination host is e2e encrypted with its IP being derrived from public key. And it's faster than I2P or TOR.

Due to that annoying Android VPN policy, I'm seeking for a way to access Yggdrasil from my phone and stay anonymous to my ISP. Not sure where is the right place discuss this issue or alternatives there are.

**Comment by Gedsh** [comment]
> Yggdrasil is an overlay network like I2P

But it's not designed for anonymity.

> Due to that annoying Android VPN policy, I'm seeking for a way to access Yggdrasil from my phone

Unfortunately, this network is not on par with security and anonymity oriented software as Tor, DNSCrypt, and I2P. I have no plans to add this network to InviZible.
