### ISSUE TITLE
Don't route DNS queries for Tor-disabled apps through Tor

### ISSUE THREAD

**Issue by kanji-deshi** [Gedsh/InviZible#258]
I'm using Tor without DNSCrypt and have excluded a few apps from using Tor. However, InviZible Pro sends all DNS queries through Tor. This has two drawbacks:

- Those apps get slow.
- Those DNS queries could get associated with both you and the Tor traffic, e.g. by a malicious exit node, resulting in all your Tor traffic being deanonymized.

Orbot seperates DNS queries, which is about the only thing that app gets right, and it should be common for VpnServices to have different DNS, so I'd expect separation to be the default behavior (prove me wrong).

**Comment by Gedsh** [comment]
> I'd expect separation to be the default behavior (prove me wrong).

You're wrong. On Android, you can't separate DNS traffic from different apps. You can only bypass the VPN completely using the Android API, which is what Orbot does. So in the case of InviZible, this app will completely bypass InviZible.

This feature is available in the latest beta version and will be available in the stable version soon. Note that this will not work with the "Block connections without VPN" feature. Just like in Orbot.

**Comment by Gedsh** [comment]
Fixed via 9befd505233f093b384e50f2a53f0156485786e6
