### ISSUE TITLE
implement DPITunnel

### ISSUE THREAD

**Issue by DI555** [Gedsh/InviZible#26]
since some other tools are windows binary only yet , i would like to ask about implementing great 4th module of IZ,- it's DPITunnel:
github.com/zhenyolka/DPITunnel
I hope it will be kept developing and it's finaly great news for android users ;) - we was waiting it so much !!!
i hope it can work the same way as others IZ moduls - console executable + config file , am i right ?
  but i'm not sure of it uses modified console proxy code , does it ?

**Comment by Gedsh** [comment]
This is the same as _Possible to implement GoodbyeDPI? #14_ Thus, the answer is the same - not yet.

**Comment by DI555** [comment]
yes, but GoodbyeDPI is only for Windows only and doesn't have any plans to port to Android...;((
but DPITunnel is android native and imho doesn't take too much resources to inject it to IZ..., but DPITunnel strongly needs in root rights :((((.  (or it doesn't work with my local vpn... or i didn't tune it right...)

**Comment by DI555** [comment]
there's bad and good news..., DPITunnel is only on java, so not possible integrating it like IZ module...
but if it's all on java imo lets the possibility to integrate it to IZ like a service-part of IZ (for now if we will waiting for GoodbyDPI android port)...

**Comment by Gedsh** [comment]
InviZible is written in Java. So this is not a problem. The main problem is that InviZible gets too complicated after implementing things like DPITunnel.

**Comment by DI555** [comment]
i forgot to say that the core in DPITunnel is in c#, so it may be useful!
about complication..., imo the tool kind of that must be complicated just because to be able to fight aganst ivil !

**Comment by PHPoenX** [comment]
@DI555 GoodbyeDPI is suitable only for using on Windows.
We can use [zapret](https://github.com/bol-van/zapret) on Android

**Comment by DI555** [comment]
@Gedsh  , could you please take your attention to implementation DPITunnel in IZ !!!
it won't be hard for IZ, but will be opportunity to use DPITunnel under local vpn without root easilly(now isn't possible normally(( ).
