### ISSUE TITLE
More convenient way to start/stop and kill/restart.

### ISSUE THREAD

**Issue by kemzops** [Gedsh/InviZible#260]
First thing, I really appreciate the project and the effort you put on it.

I think adding more convenient way in the UI to control the services other than the start button, adding start/stop/kill/restart buttons will really make it more "convenient".

Just an enhancement request, Thanks!.

**Comment by Gedsh** [comment]
> First thing, I really appreciate the project and the effort you put on it.

Thank you!

> adding start/stop/kill/restart buttons will really make it more "convenient"

I don't think so. But can you provide a sketch of the UI so I can better understand what you mean.

**Comment by kemzops** [comment]
> > may be only for my own use case
> 
> I don't know why you need to restart services all the time, but I think it's a very rare case. And I don't want to add such graphics to InviZible. Sorry.

No problem !! as i said im just suggesting this to see your reply, i have odd use case for the app and i dont think you will find anyone using it like me, but yeah !! thanks, and keep up the good work.
