### ISSUE TITLE
[Enhancement] Block when DNS is bypassed

### ISSUE THREAD

**Issue by 8itlew7r** [Gedsh/InviZible#264]

**Comment by Gedsh** [comment]
This feature doesn't make sense since most messengers and many other apps don't use plaintext DNS and will therefore be blocked.

**Comment by 8itlew7r** [comment]
I'm referring to the ability to block connections that directly connect to an IP address, bypassing the use of DNS filtering, especially if I don't have an IP blacklist.

**Comment by Gedsh** [comment]
I get it and answered above about messengers.

**Comment by 8itlew7r** [comment]
> I get it and answered above about messengers.

Not enabling it by default is a potential solution to the messengers problem. However, I understand if you're still not convinced.
