### ISSUE TITLE
Automatically disable and enable private DNS when using VPN Mode

### ISSUE THREAD

**Issue by kaafir786** [Gedsh/InviZible#265]
Basically I use NextDNS as my Private DNS on Android.
And I use VPN mode for Tor, etc.
So, Whenever I try to make connection I need to disable DNS and then Re-enable it after closing connection. So, can app itself ignore private dns and setup connection and then resume NextDNS after all connections are closed.

**I do not know anything about networking.**

**Comment by Gedsh** [comment]
> Basically I use NextDNS as my Private DNS on Android.

You can use it with DNSCrypt, so you don't need to use private DNS.

https://github.com/Gedsh/InviZible/wiki/Add-custom-DNSCrypt-server

> can app itself ignore private dns and setup connection and then resume NextDNS after all connections are closed

Unfortunately, this is impossible on Android without special permission, which only system apps have.

**Comment by kaafir786** [comment]
> You can use it with DNSCrypt, so you don't need to use private DNS.

Still I need to switch private DNS manually cause I don't use dnscrypt all the time.

**Comment by Gedsh** [comment]
> I don't use dnscrypt all the time.

Why? It's more reliable, predictable and open source compared to an unknown implementation of the phone manufacturer.

**Comment by kaafir786** [comment]
Actually I never thought of using it all time.
Probably because of memory usage.
Going to try i now.
