### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by JCaris94** [Gedsh/InviZible#268]
How can I contribute to the project? It would be a blessing to help and translate to Portuguese (Brazilian Portuguese, of course). 

Let me know how can I help!

**Comment by Gedsh** [comment]
You can use [POEditor](https://poeditor.com/join/project/h6ulNL9gEd) or [Hosted Weblate](https://hosted.weblate.org/engage/invizible/) for translation. Just let me know when you're finished, as I need to add the translation manually to the app.

**Comment by JCaris94** [comment]
Finished! 99,85% done :D

**Comment by Gedsh** [comment]
Thanks! What did you use: POEditor or Hosted Weblate?

**Comment by JCaris94** [comment]
I've used the POEditor. :)
