### ISSUE TITLE
No priority regarding updates for Premium version.

### ISSUE THREAD

**Issue by emtreulapollaguera** [Gedsh/InviZible#269]
I have seen that while non premium users are benefit for earlier updates, premium users have not received the latest updates yet.

One of the benefits of being donator/premium is, and I quote from the official website:

"Automatic Updates – Use the latest versions of InviZible Pro, and its modules such as DNSCrypt , Tor, and Purple I2P."

**Comment by Gedsh** [comment]
> I have seen that while non premium users are benefit for earlier updates, premium users have not received the latest updates yet.

You got it wrong. Premium users get an update when the stable version gets an update. This usually happens once every month or two. This is enough to have the latest versions of DNSCrypt, Tor and Purple I2P.

There is a beta version intended for testing new features. It is updated frequently and may be unstable.

**Comment by Gedsh** [comment]
Sometimes there are no significant changes in the upstream projects. The stable version is still up to date. The beta version contains a slightly newer version of Tor, but there are no critical changes. New features in InviZible itself are being tested.
