### ISSUE TITLE
[FEATURE REQUEST] Import blacklist file

### ISSUE THREAD

**Issue by pc-v2** [Gedsh/InviZible#27]
so, i have list of porn domain, it's 9MB, i'd like to have option to import it

**Comment by Gedsh** [comment]
Thanks for the suggestion. This feature is planned.

**Comment by magixtruct** [comment]
maybe a way to import energized lists/packs? they have a pack for unbound, afaik it's the predecessor on linux of dnscrypt-proxy.
https://energized.pro/

**Comment by Gedsh** [comment]
I am working on this feature. But there will be some delay.

**Comment by Gedsh** [comment]
Import of DNSCrypt filter files was added in version 0.7.9
