### ISSUE TITLE
Allow null (or other invalid configuration) in dnscrypt-proxy settings 

### ISSUE THREAD

**Issue by mvevitsis** [Gedsh/InviZible#270]
If I try and delete bootstrap resolvers, or set them to 0.0.0.0 or 127.0.0.1, it forces it back to the default settings. 

I don't need them because I am using a custom stamp.
On desktop I usually leave it empty (like this [ ])
I realize I can edit the toml and delete them, but the problem is if you then subsequently change any setting in the GUI (e.g. to add an item to your blocklist) it will reinsert them.

This problem also applies to any other settings with a non-removable default value (e.g. sources). You can remove them using the toml, but they will come back the next time you do something in the GUI.

**Comment by Gedsh** [comment]
> If I try and delete bootstrap resolvers, or set them to 0.0.0.0 or 127.0.0.1, it forces it back to the default settings.

This is the correct behavior. They are used for both DNSCrypt and the functionality of InviZible itself, and cannot be removed or bypassed in any other way. If you want to be able to disable bootstrap resolvers, you should ask the upstream DNSCrypt project to do so. But you have a very rare case, so there is little chance of implementation.

https://github.com/Gedsh/InviZible/wiki/DNSCrypt-bootstrap_resolvers

**Comment by mvevitsis** [comment]
> > If I try and delete bootstrap resolvers, or set them to 0.0.0.0 or 127.0.0.1, it forces it back to the default settings.
> 
> This is the correct behavior. They are used for both DNSCrypt and the functionality of InviZible itself, and cannot be removed or bypassed in any other way. If you want to be able to disable bootstrap resolvers, you should ask the upstream DNSCrypt project to do so. But you have a very rare case, so there is little chance of implementation.
> 
> https://github.com/Gedsh/InviZible/wiki/DNSCrypt-bootstrap_resolvers

Bootstrap resolvers are not required by dnscrypt.
If you have an IP address in your stamp, you can remove them. I do this in every installation of dnscrypt-proxy.

It works in invizible also (I edited the toml and removed them, then started dnscrypt-proxy).

The issue is that invizible's GUI likes to reset  any changes made to the toml if you do anything else from the GUI. I want it to stop doing that.

**Comment by Gedsh** [comment]
> Bootstrap resolvers are not required by dnscrypt.

If you have not configured bootstrap resolvers in DNSCrypt, it uses the default resolver.

https://github.com/DNSCrypt/dnscrypt-proxy/blob/de16f22c0cea8606d0a270481633824f175e38a3/dnscrypt-proxy/xtransport.go#L34

> The issue isn't really about bootstrap resolvers specifically, it's just that invizible's GUI likes to reset any changes made to the toml if you do something else from the GUI.

This "issue" is intended to prevent incorrect user configuration. Bootstrap resolvers are mandatory for both DNSCrypt and InviZible itself to work properly.

**Comment by mvevitsis** [comment]
> > Bootstrap resolvers are not required by dnscrypt.
> 
> If you have not configured bootstrap resolvers in DNSCrypt, it uses the default resolver.
> 
> https://github.com/DNSCrypt/dnscrypt-proxy/blob/de16f22c0cea8606d0a270481633824f175e38a3/dnscrypt-proxy/xtransport.go#L34
> 
> > The issue isn't really about bootstrap resolvers specifically, it's just that invizible's GUI likes to reset any changes made to the toml if you do something else from the GUI.
> 
> This "issue" is intended to prevent incorrect user configuration. Bootstrap resolvers are mandatory for both DNSCrypt and InviZible itself to work properly.
> 
> > I must have some good reason for it and already know what I'm doing.
> 
> You can know it if you are a developer. Please check the source code for both DNSCrypt and InviZible to understand how they are used and why they are required.
> 
> > thanks for porting dnscrypt to android
> 
> You are welcome!

I have port 53, 853, and 443 for most common resolvers blocked at the router :)

Here is my config, try it. I promise it will connect:
1. Block port 53 on your router. 
2. Set bootstrap resolver to [ ], 0.0.0.0:0, 127.0.0.1:53, or any other completely invalid address of your choice. 
3. Select a server that uses a stamp with an IP. So any dnscrypt server is fine, or most DoH servers, or you can make your own stamp.
4. Watch it connect.

You can verify with traffic monitoring that the only connection made is to your DoH server on port 443. No other requests are ever sent, not even ones that would be blocked by the firewall rule.

**Comment by Gedsh** [comment]
> Here is my config, try it. I promise it will connect:

I don't see the point in doing such a test. Bootstrap resolver is probably not required for DNSCrypt in your particular case. But it is not explicitly defined and could change with any DNSCrypt update. You could ask the DNSCrypt developer to implement this as an option so I can check if I can workaround this and not use these resolvers in InviZible.

**Comment by mvevitsis** [comment]
> > Here is my config, try it. I promise it will connect:
> 
> I don't see the point in doing such a test. Bootstrap resolver is probably not required for DNSCrypt in your particular case. But it is not explicitly defined and could change with any DNSCrypt update. You could ask the DNSCrypt developer to implement this as an option so I can check if I can workaround this and not use these resolvers in InviZible.

Dnscrypt is explicitly designed to work like this. Please read the comments in the default .toml file.

**Comment by Gedsh** [comment]
>  ...**put valid standard resolver addresses here**. Your actual queries will
not be sent there. If you're using DNSCrypt or Anonymized DNS and your
lists are up to date, these resolvers will not even be used.

**Comment by mvevitsis** [comment]
You quoted the second time it says they won't be used.

**Comment by Gedsh** [comment]
If they are not used, this does not change the previous statement that they should be configured.

**Comment by mvevitsis** [comment]
> If they are not used, this does not change the previous statement that they should be configured.

Sure. Leave them configured by default.

But I should be able to change them to whatever I want.

**Comment by Gedsh** [comment]
> I should be able to change them to whatever I want.

You can't because "put **valid** standard resolver addresses here"

**Comment by mvevitsis** [comment]
> > I should be able to change them to whatever I want.
> 
> You can't because "put **valid** standard resolver addresses here"

Sure you can. I'm typing this from a computer connected using dnscrypt-proxy with the bootstrap resolver in my .toml set to 127.0.0.1:53.

Like I said, try it yourself.

**Comment by Gedsh** [comment]
> Sure you can

You can do whatever you want. But this is not officially supported by DNSCrypt. The statement in the manual is clear. These must be valid resolvers.

**Comment by mvevitsis** [comment]
> > Sure you can
> 
> You can do whatever you want. But this is not officially supported by DNSCrypt. The statement in the manual is clear. These must be valid resolvers.

Only if you are not using a stamp that includes the IP address. 

![Screenshot 2024-07-28 at 03.30.16.png](https://github.com/user-attachments/assets/2323d26d-24fc-4071-ab18-e4cb9fba697a)

Anyway, I'm not saying you should change the default behavior. I'm just saying that if I edit the toml to change this setting, and then use the GUI to change something else, it shouldn't try to reset the bootstrap again when I didn't ask it to. 
I think that's pretty reasonable.

**Comment by Gedsh** [comment]
> Only if you are not using a stamp that includes the IP address.

> this is not officially supported by DNSCrypt

The only way I would consider changing the behaviour of InviZible is to implement this feature officially. I don't have anything else to say.

**Comment by mvevitsis** [comment]
Then why let me edit the toml at all, if you are going to reset it? 

Just to be clear, I only want it to not revert changes made to the toml. 

I am not suggesting you change the default behavior in the GUI (which doesn't allow entering invalid addresses directly)..
