### ISSUE TITLE
System UIDs showing in user apps

### ISSUE THREAD

**Issue by mvevitsis** [Gedsh/InviZible#272]
Seems like a bug

![Screenshot_20240728-012654_InviZible Pro.png](https://github.com/user-attachments/assets/2b37efc8-04b6-4779-80f4-9cbc0abc42b5)

>

**Comment by Gedsh** [comment]
If apps with a Shared UID are present in both user and system apps, they are placed in the user apps. That's how it was intended. I thought it would be convenient.

**Comment by Gedsh** [comment]
I decided to change this behavior as it seems a bit odd. In the next beta version, it will be made so that if apps with a Shared UID are present in both user and system apps, they will be placed in system apps.
