### ISSUE TITLE
Proxy authentication with user/password broken

### ISSUE THREAD

**Issue by mvevitsis** [Gedsh/InviZible#273]
SOCKS5 proxy works correctly without a user/password, however if you set a user/password it does not work. 

It seems that regardless of the strings you enter, the app attempts to send something else.

For example, I set the user to 'invizible' with a password of 'test', but my logs show the app attempts to send the user 'root' with a blank password.

![Screenshot_20240728-121139_InviZible Pro.png](https://github.com/user-attachments/assets/8816a216-d792-475b-99af-0f035b93e07b)

![Screenshot_20240728-121125_sing-box.png](https://github.com/user-attachments/assets/8c929be6-b86b-469c-969b-df33a5e00ed9)

![Screenshot_20240728-120821_sing-box.png](https://github.com/user-attachments/assets/58aa2d72-27b3-4bcd-b189-4173ac29c0df)

**Comment by Gedsh** [comment]
Thanks. I don't think anyone has tested this feature before. It should work in the next beta.
