### ISSUE TITLE
Allow DNS requests on invizible interface from other interfaces to enable loopback from work profile when in VPN mode

### ISSUE THREAD

**Issue by mvevitsis** [Gedsh/InviZible#276]
Because interfaces' loopback addresses are isolated in Android, a VPN installed in the work profile cannot use invizible as its DNS server by specifying 127.0.0.1.

As a workaround, to allow apps installed in the work profile to use invizible for DNS lookups,
invizible can listen for DNS requests on an IP in the range of its interface's address e.g. 10.1.10.3:53 
(I don't think it's possible to use the actual interface IP of 10.1.10.1 for this purpose).

**Comment by mvevitsis** [comment]
I am using wireguard in the work profile, so it's not possible. I would need a local IP to specify as the wireguard DNS server, and then exclude that IP from allowed IPs in wireguard config.

**Comment by Gedsh** [comment]
Use InviZible in proxy mode in a work profile.

**Comment by mvevitsis** [comment]
> Use InviZible in proxy mode in a work profile.

Ok so you mean replace sing-box with a second copy of inviZible. Okay I will try this, thanks.

**Comment by mvevitsis** [comment]
I tried it, and it sort of works, but it doesn't allow all apps in the work profile to use invizible. 

Here's my setup:

Main profile:
Invizible in VPN mode, socks 5 proxy enabled. 

Work profile: 
Invizible in proxy mode
Wireguard using VPN 

In this scenario:
1. All apps in the main profile can use invizible for DNS lookups
2. Most apps in the work profile cannot use invizible for DNS lookups. Only apps that include a manual proxy setting can work around this. 

As for potential solutions:
1. Integrate wireguard upstreams into invizible. In this case, the work profile/proxy workaround is no longer necessary. 
2. My original suggestion, give invizible a private IP (e.g. 10.1.10.3:53) it can listen for DNS requests on. Then it can be specified as the DNS server in wireguard.

**Comment by Gedsh** [comment]
> I tried doing this in the toml but it would not start.

Because you can't use ports below 1024 without root.

**Comment by mvevitsis** [comment]
> > I tried doing this in the toml but it would not start.
> 
> Because you can't use ports below 1024 without root.

Right. I think it would be possible for it to listen on its own interface's range though, because rethinkdns listens on 10.111.222.3:53 (where the interface tun* for rethink DNS is 10.111.222.1)
