### ISSUE TITLE
Support for Ouinet

### ISSUE THREAD

**Issue by atlantis451** [Gedsh/InviZible#278]
> Bypass internet shutdowns with Ouinet
Ouinet is a collection of software tools and support infrastructure that provide access to web resources when access to the unrestricted internet is unreliable or unavailable, tailored for scenarios of limited internet connectivity and selective network traffic filtering.

> Ouinet is a collection of open source software libraries that create a
decentralized network of cooperating peers for sharing and propagating web
content. A Ouinet deployment requires supporting infrastructure - run by a
trusted network operator - and the integration of its client libraries into
third-party applications for requesting and receiving desired content.
Ouinet clients collectively form a distributed cache that is global in nature,
but also functional on a local or national network. Peer-to-peer transports
are used for communications.
Ouinet's primary integration and its initial raison d'etre is to power the
Ceno Browser - utilized for accessing web content
behind national firewalls. Supporting infrastructure on this project is
provided by eQualitie, offering injection and
authentication of web content into a decentralized p2p network, using the
BitTorrent DHT for addressing and routing. Coupled with sneakernet technology
operated by eQualitie, Ceno users can access
cached website replicas from heavily limited
or entirely isolated network environments.
https://gitlab.com/equalitie/ouinet/
https://ouinet.work/

**Comment by Gedsh** [comment]
InviZible uses only the most robust privacy and security solutions that have been proven over time. I have no plans to add any other networks to the app at this time.
