### ISSUE TITLE
config backup error

### ISSUE THREAD

**Issue by magixtruct** [Gedsh/InviZible#28]
got still the config backup error when trying to save backup to internal sd. gave permissions and all. latest iz 0.7.0, armv7, non-ps version. android 8.1.0, samsung

**Comment by Gedsh** [comment]
Please send me the logs right after the error occurs. Menu -> Logs -> Save Logs

**Comment by magixtruct** [comment]
here the logs, that I also couldn't save in iz. therefore the 2nd log.
[Log_2020-03-06_19-49-33.zip](https://github.com/Gedsh/InviZible/files/4299936/Log_2020-03-06_19-49-33.zip)
[Log_2020-03-06_19-46-22.zip](https://github.com/Gedsh/InviZible/files/4299943/Log_2020-03-06_19-46-22.zip)

**Comment by Gedsh** [comment]
Do you have root permissions? What mode (VPN, proxy, root) do you use?

**Comment by magixtruct** [comment]
at time being, root mode with modules run as root.

**Comment by Gedsh** [comment]
Thank you. It looks like the problem with "Run modules with root" option. I think this issue will be solved in the next beta.

**Comment by Gedsh** [comment]
This should be fixed in beta 0.7.1.
