### ISSUE TITLE
Tor is not working  work on TV android

### ISSUE THREAD

**Issue by JustOne94** [Gedsh/InviZible#280]
Tor is not working on TV android 6.0 / proxy mode /
i all tried bridges , multiple bridges , i got maximum 40% connecting  
 i'm in russia 
the app worked on mobile phone and BlueStacks without problems .

![a](https://github.com/user-attachments/assets/e7600900-f8e4-437f-b1ae-4888788bc496)
![aa](https://github.com/user-attachments/assets/74ef48e4-098b-41fc-ad47-1cbc52b06ff5)

**Comment by Gedsh** [comment]
Please read the Tor logs carefully. It complains that your android TV is set to the wrong time. Fix it.

**Comment by JustOne94** [comment]
> Please read the Tor logs carefully. It complains that your android TV is set to the wrong time. Fix it.

You are right , i fixed it and it's working.. thanks alot 👌👍
