### ISSUE TITLE
[Wiki] : Add instructions on how to configure RDNS 

### ISSUE THREAD

**Issue by shuvashish76** [Gedsh/InviZible#281]
> https://github.com/Gedsh/InviZible/wiki/Proxy-mode-(no-root-required)

In additioln to Netguard and personalDNSfilter, request update the wiki with instructions on how to configure [RethinkDNS](https://f-droid.org/en/packages/com.celzero.bravedns/) for this.

Ping @ignoramous (_form RDNS team_) for help.

PS: I know how to configure...it's for official documentation only

**Comment by Gedsh** [comment]
What is the reason for using InviZible with RethinkDNS? They do pretty much the same things.

**Comment by shuvashish76** [comment]
Honestly for me it's about Logs, App specific domain/ip rules etc. which are presented in an user friendly UI. RethinkDNS shows app specific domains/ips nicely which check when testing new apps. I know InviZible has Firewall option but it's not ad configurable as RDNS.

To some extent InviZible already offers some/most of the features we've in Netguard and personalDNSfilter as well. So it's not about comparison vs RDNS, IMO it's about having the choice of freedom. I don't think it's a bad idea to add guide for RDNS especially as it's a FOSS project which actively promotes InviZible Pro_(in their Telegram group bot configured to suggest "how to configure with InviZible")_ 🙂

**Comment by Gedsh** [comment]
> So it's not about comparison vs RDNS

I'm just wondering about real use cases. When people prefer to use these two apps together.

**Comment by SevenFactors** [comment]
> > So it's not about comparison vs RDNS
> 
> I'm just wondering about real use cases. When people prefer to use these two apps together.

Has me wondering too. The only thing I can think of is adding I2P functionality and/or TOR while keeping a more powerful firewall and VPN support (proxied wireguard) via the RethinkApp.

**Comment by ignoramous** [comment]
Thanks 🙏

> hope everything's correct?

Yes.

A note that Rethink won't connect to InviZible if VPN is in *lockdown mode* (ie, *Block connections without VPN* is turned ON) could be added for completeness.

**Comment by ignoramous** [comment]
btw, is there a way to programmatically setup InviZible (Tor / I2P), then connect to it (Rethink has a similar integration with Orbot using plain *Intents*)?

**Comment by shuvashish76** [comment]
> > in their Telegram group bot configured to suggest "how to configure with InviZible"
> 
> Unfortunately, I couldn't find the manual mentioned. Perhaps I was looking in the wrong place.

There used to be a bot for common user queries back in 2022/23. Sorry, I'm not active on active on their Telegram/Matrix so not sure :(

**Comment by Gedsh** [comment]
> A note that Rethink won't connect to InviZible if VPN is in lockdown mode

This is a common situation for such a setup, because in lockdown mode, excluded apps cannot connect to the internet. And you need to exclude InviZible.

> could be added for completeness

Added.

> is there a way to programmatically setup InviZible (Tor / I2P), then connect to it

You can also start and stop modules using intents. See Enable script control in Common Settings. You can also monitor the state of modules when this option is enabled via broadcasts. But I don't have a tutorial on this as no one has been interested in this before. https://github.com/Gedsh/InviZible/blob/master/tordnscrypt/src/main/java/pan/alexander/tordnscrypt/modules/ModulesStatusBroadcaster.kt
