### ISSUE TITLE
Can dnscrypt be exchanged?

### ISSUE THREAD

**Issue by biange200** [Gedsh/InviZible#284]
![Screenshot_20240825_183538.jpg](https://github.com/user-attachments/assets/35d58b5c-8cfa-4593-a592-4e3dbc073d00)

Invizible can replace dnscrypt files?

**Comment by Gedsh** [comment]
You can edit dnscrypt-proxy.toml directly from the UI of the app for all versions except the Google Play version. Menu -> DNSCrypt Settings -> Edit dnscrypt-proxy.toml directly. But you can change settings and add new ones. If you delete any parameter, the app will crash.
