### ISSUE TITLE
Feedback question:The latency of private dns is high

### ISSUE THREAD

**Issue by biange200** [Gedsh/InviZible#285]
![Screenshot_20240824_234239.jpg](https://github.com/user-attachments/assets/71922361-db8a-4e97-a510-3f7e1ccb3d2e)

The latency of trli's dns is very low on adguard and rethinkdns, but very high on invizible. What is this, please solve it

Official website：https://dns-cdn-tx.trli.club/

**Comment by Gedsh** [comment]
The difference cannot be significant. The only difference may be in the method of measuring the latency. In any case, I am not developing DNSCrypt itself. If you are sure that this is a DNSCrypt problem, you should leave the issue to the upstream project https://github.com/DNSCrypt/dnscrypt-proxy

**Comment by ignoramous** [comment]
> The only difference may be in the method of measuring the latency. 

Not really. Rethink employs a bunch of optimization such as a long-term cache which (on-demand) refreshes newer answers in the background, coalesces multiple request in to one request, employs a connection pool, & prefers UDP (I believe InviZible Pro prefers TCP for DNSCrypt v3?). Unsure if upstream dnscrypt-proxy does this out-of-the-box, but there must exist configuration options ("plugins" as dnscrypt-proxy labels them) to achieve the same.
