### ISSUE TITLE
Firewall leak in Root mode. Edge case when turning off third-party VPN.

### ISSUE THREAD

**Issue by 3xp10its** [Gedsh/InviZible#287]
there is a leak when running root commands notification take place 

1. turn on firewall from the app
2. choose let's say chrome and keep vpn traffic allowed only
3. run dnscrypt or tor 
4. run any vpn
5. open chrome and load ipinfo.io for example 
6. turn off vpn and then immediately reload the page

you will see the chrome will successfully connect to the Internet without vpn

**Comment by Gedsh** [comment]
It takes time to react to the network changes. In any case it can't be immediate. It mostly depends on the android system. I can't do anything about it.

**Comment by emtreulapollaguera** [comment]
https://x.com/GrapheneOS/status/1841236289263116381

**Comment by Gedsh** [comment]
@emtreulapollaguera This issue is about the firewall operating in root mode when using a third-party VPN.
