### ISSUE TITLE
Android System leaks connection and blocked TOR & dnscrypt-proxy?

### ISSUE THREAD

**Issue by cone-del** [Gedsh/InviZible#289]
I always had problem connection blocked by ISP even i changes my devices/phone, and also when bridge, 
does my phone carrier is tracking me by blocking these TOR connection or just the android system? 

Log : "SOCKS client attempted to connect 'address:port' etc" 
I use SOCKS5 and HTTPS only with android 8+ 

I used outbound proxies, dnssec, no-filter, and no-log, they still somehow able to block my invizible 
possible rootkit remote authorization?, idk how's not working just by using my phone number or ISP network
in any ways of attempt to changes the value and parameters would will unable to connect

The thing I2p router only work in such matter

**Comment by Gedsh** [comment]
> I always had problem connection blocked by ISP even i changes my devices/phone

Your connection does not depend on your phone. It depends on your ISP and how it implements censorship.

> does my phone carrier is tracking me by blocking these TOR connection or just the android system?

Your ISP just blocks Tor, so you should use Tor bridges. You should find a working ones. https://github.com/Gedsh/InviZible/wiki/Tor-Bridges

> Log : "SOCKS client attempted to connect 'address:port' etc"

This means that your bridges are not working. You should find other bridges.

> I used outbound proxies, dnssec, no-filter, and no-log, they still somehow able to block my invizible
possible rootkit remote authorization?

It's just a series of words with no meaning. You need to improve your knowledge of the network basics.

> The thing I2p router only work in such matter

You should read what I2P is for and how to use it.
