### ISSUE TITLE
ipv6 🙏🏼

### ISSUE THREAD

**Issue by magixtruct** [Gedsh/InviZible#29]
will you add ipv6 support in the future? I believe I understand why ipv6 has been left aside for now.
but maybe you're able to address these security issues in the future. cause much of the traffic relies on ipv6 these days, it's faster & more secure (correct me if I'm wrong). and if I secure my hotspot on my android with iz & connect my pc to it, my pc's ipv6 traffic theoretically is still unencrypted, right? I know how to avoid this, but it seems easier for me if iz had ipv6 support, too. btw can I edit the toml config file, tor/i2p config files to use ipv6 with iz if I want?

**Comment by Gedsh** [comment]
> will you add ipv6 support in the future?

It has security issues, especially in Root mode. These issues related to restrictions in the android kernel.  Maybe later I will add ipv6 for VPN mode. But this requires an investigation.

> more secure

No.

> ipv6 traffic theoretically is still unencrypted, right?

No. InviZible blocks ipv6 traffic with a few methods. Especially in Root mode.

> can I edit the toml config file, tor/i2p config files to use ipv6 with iz

This is a bad idea.

**Comment by magixtruct** [comment]
ok, thank you for making things clear for me.
maybe in future versions✨

**Comment by SamuelP1111** [comment]
Hi
We dont all have ipv6 with isp and modem hardware (Wifi).
But we have ipv6 with many phone providers.

I can use openvpn with ivp4, v6 and combined tunnel as well.

android 9

**Comment by Gedsh** [comment]
> With 4G et 4G+, I can use openvpn with ivp4, v6 and combined tunnel as well.

You can. But using ipv6 in root mode is unsafe due to limitations in the Android kernel. With VPN mode, this is possible. But first I need to check if this is really safe.

**Comment by magixtruct** [comment]
hi ghost, I hope you read this here! 
thank you for bringing on the fact that most smartphones' internet connection consists to a large extent of ipv6.
and from my side: thank you for participating here in this issue!
I just looked in here yesterday, so I didn't read your post before, I'm sorry!
IMO: please come back to github! or show/tell me where I can find you. to my understanding you're an instance here on github for many years, I've read a few guides & comments from you years ago & they helped me! I'm very sorry to see you go.

**Comment by Gedsh** [comment]
IPv6 support was added in version 0.8.2-beta for VPN mode.

**Comment by magixtruct** [comment]
just want to say thank you for this! 👍🏼
