### ISSUE TITLE
Inconsistency of socks5 proxy settings

### ISSUE THREAD

**Issue by mvevitsis** [Gedsh/InviZible#290]
I have the socks5 proxy under "common settings" enabled. Use proxy for dnscrypt is checked.

I have the proxy under "dnscrypt settings" disabled

I would expect all traffic from invizible to go through the specified socks5 proxy, however, my upstream DoH server's log is showing my actual IP address, and not that of the proxy. 

Am I doing something wrong with this setup?

**Comment by Gedsh** [comment]
> I have the socks5 proxy under "common settings" enabled. Use proxy for dnscrypt is checked.
I have the proxy under "dnscrypt settings" disabled

It's actually one option that is controlled from those two places for convenience. How did you manage to deactivate it in one place and activate it in the other?

**Comment by mvevitsis** [comment]
> > I have the socks5 proxy under "common settings" enabled. Use proxy for dnscrypt is checked.
> I have the proxy under "dnscrypt settings" disabled
> 
> It's actually one option that is controlled from those two places for convenience. How did you manage to deactivate it in one place and activate it in the other?

I am not sure. It must have been some sort of bug, because after reading your message I tried disabling the proxy under "common settings" and then re-enabling it.

After that I checked the dnscrypt settings and both the proxy setting and "force TCP" had been automatically enabled.

I am sorry I cannot provide a more detailed explanation of the cause since I don't know myself how the settings got out of sync.
