### ISSUE TITLE
Cannot update to v6.8.0

### ISSUE THREAD

**Issue by grm34** [Gedsh/InviZible#291]
What happened to latest stable, updating fails (looks like signature changed) need to uninstall first and app renamed to `InviZible Lite` ?

From Obtainium :
![Screenshot_20240910-011526_Obtainium](https://github.com/user-attachments/assets/c062f988-9544-4fba-875c-7b9dc25fab9d)

From android Package Installer :
![Screenshot_20240910-011428_Package installer](https://github.com/user-attachments/assets/9ca23823-cbd1-433c-b745-6dc7a99d8472)

**Comment by Gedsh** [comment]
There are Beta, Lite, Play Market and F-Droid versions of InviZible Pro. You cannot update one version to another. You have to wait for F-Droid to update its version, or uninstall it and install the Lite version.
