### ISSUE TITLE
DNS rules

### ISSUE THREAD

**Issue by Mishasama** [Gedsh/InviZible#296]
Is InviZible support setup DNS rules?

e.g.
Google.com use Google DNS
Cloudflare.com use Cloudflare DNS

**Comment by Gedsh** [comment]
I think that's what you're asking for https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Forwarding

Menu -> DNSCrypt settings -> Forwarding rules

**Comment by Mishasama** [comment]
> Forwarding rules

No, I need sending queries to encrypted servers. Something like [YogaDNS](https://www.yogadns.com/) on PC.
![Rules](https://www.yogadns.com/screen2.png)
Or let me put it bluntly, I want the YogaDNS features on Android.

**Comment by Gedsh** [comment]
InviZible can only support this feature if the upstream DNSCrypt project implements it. https://github.com/DNSCrypt/dnscrypt-proxy
