### ISSUE TITLE
Please add these dns.

### ISSUE THREAD

**Issue by biange200** [Gedsh/InviZible#298]
https://ipv4dns.com/

https://dns.dns1.top/

http://go.18bit.cn/

**Comment by Gedsh** [comment]
I do not maintain a list of DNS servers. You should leave your issue there https://github.com/DNSCrypt/dnscrypt-resolvers

**Comment by biange200** [comment]
Put it over there, will they add it to me?

**Comment by Gedsh** [comment]
> will they add it to me?

Give it a try.
