### ISSUE TITLE
Refresh Interval for Excluded Sites

### ISSUE THREAD

**Issue by uultimaa7** [Gedsh/InviZible#299]
Any way to reduce this down to less than one hour?

I get captcha'd a lot on excluded sites within the one hour refresh. Unless I go in and force the value to update.

Awesome app and thank you for it.

**Comment by Gedsh** [comment]
> Any way to reduce this down to less than one hour?

Most probably you are trying to use this feature for sites behind a CDN. It will not work properly for these sites, as they change IPs based on different circumstances, not time. This feature only works well for sites with a static IP.

> Awesome app and thank you for it.

Thank you.

**Comment by uultimaa7** [comment]
'google.com' for example will captcha and display a tor IP, but if I go in to the app, refresh the excluded address, switch back to the browser and refresh it will load. If there was a way to reduce the refresh down to 1 minute it might solve the issue.

I'll try and work around with tasker.

**Comment by Gedsh** [comment]
> it might solve the issue

This feature is intended for sites with a static IP. It will not work reliably for sites with a dynamic IP, even if you update it every second.
