### ISSUE TITLE
donations thru playstore

### ISSUE THREAD

**Issue by magixtruct** [Gedsh/InviZible#30]
will you add a donation app to the playstore for people who'd like to donate this way?

**Comment by Gedsh** [comment]
Thanks. Yes, I can try. But I think that the Play Market may ban such an application.

If you want to make a donation, you can buy the Play Market version. Send me payment details and I will send you the code for the developer stable version without Play Market restrictions.

Or just use bitcoin. Details on the official site.

**Comment by magixtruct** [comment]
I will do that. thank you! 🙂

**Comment by Gedsh** [comment]
You are welcome.

**Comment by magixtruct** [comment]
I find the system: purchasing premium in the playstore app, sending evidence, getting a code by email, load the unrestricted stable developer lite version, enter the code, unlock & get the pro version of the same, perfect.
should we close this issue?

**Comment by Gedsh** [comment]
I don’t know what's better to leave this issue if someone wants to ask the same thing or just close it, because this information is on the official website.

**Comment by magixtruct** [comment]
yeah, maybe someone has another payment idea...
