### ISSUE TITLE
about the settings conflict

### ISSUE THREAD

**Issue by follyfall** [Gedsh/InviZible#301]
After activating the "kill switch" option in the _COMMON SETTINGS_ and selecting the "applications that use Tor" under the _FAST SETTINGS_ > _TOR SETTINGS_, when Invizible is stopped, the internet connection of all applications on the device is cut off. However, the "kill switch" is not supposed to cut off the internet connection of all applications, but only "Tor-using applications".

**Comment by Gedsh** [comment]
> However, the "kill switch" is not supposed to cut off the internet connection of all applications

It's just your thoughts. The kill switch is working as intended.

Thanks for the suggestion, but I don't like your idea.
