### ISSUE TITLE
connect to Tor via adb

### ISSUE THREAD

**Issue by NeverL4nd2** [Gedsh/InviZible#303]
Is it possible to connect to Tor on a rooted device/emulator, after installing it via adb?

I have adb root access, and I would like to route all traffic through Tor, the problem is that I have no UI access, it's CI like env.

If not possible, what other options I have?

**Comment by Gedsh** [comment]
Are you talking about InviZible or pure Tor? It looks like you don't need InviZible in your case.

**Comment by NeverL4nd2** [comment]
> Are you talking about InviZible or pure Tor? It looks like you don't need InviZible in your case.

if I can do it with pure Tor would be great, but I was unable to do so,

**Comment by Gedsh** [comment]
> I was unable to do so

If you need Tor in CI like env, you definitely don't need InviZible. I suggest you use Tor binary and iptables if you have root access. Unfortunately, I don't provide support for this sort of thing as it doesn't relate to InviZible. You can try asking on the Tor Project forum https://forum.torproject.org/
