### ISSUE TITLE
IP Blacklist

### ISSUE THREAD

**Issue by smexyy** [Gedsh/InviZible#304]
Hello, I added 1 ip only in ip blacklist, but still accessible, in the log its green.

![Screenshot_20241016-042747](https://github.com/user-attachments/assets/08a7f18d-ab68-4069-af1b-cc4371e13808)

**Comment by Gedsh** [comment]
Hello, this is one of Google's general purpose servers which is also used for captive portals detection and connectivity checking. Blocking this address may cause loss of internet connection at random times. Therefore, it cannot be blocked as easily as other addresses. But if you are sure about what you are doing, you can try disabling captive portal detection in DNSCrypt.

Go to Menu -> DNSCrypt Settings -> Edit dnscrypt-proxy.toml and comment out or delete the line map_file = 'captive-portals.txt' under the [captive_portals] header.

**Comment by smexyy** [comment]
> Hello, this is one of Google's general purpose servers which is also used for captive portals detection and connectivity checking. Blocking this address may cause loss of internet connection at random times. Therefore, it cannot be blocked as easily as other addresses. But if you are sure about what you are doing, you can try disabling captive portal detection in DNSCrypt.
> 
> Go to Menu -> DNSCrypt Settings -> Edit dnscrypt-proxy.toml and comment out or delete the line map_file = 'captive-portals.txt' under the [captive_portals] header.

Hello, Line deleted but gave this error when connect.
![Screenshot_20241016-220440~2](https://github.com/user-attachments/assets/1f42a204-e17e-4167-8600-f66cf2589f78)

**Comment by smexyy** [comment]
My concern is total control of blocking.

**Comment by Gedsh** [comment]
> gave this error when connect

You have broken the configuration. Press reset, and then comment out the line as follows 
`
#map_file = 'captive-portals.txt'
`

> My concern is total control of blocking.

You'll just make your internet unstable and your device unusable. If you see this address, you probably have google services installed. Therefore, you can start using a device without google services or flash a custom rom without google services.

**Comment by smexyy** [comment]
> > gave this error when connect
> 
> You have broken the configuration. Press reset, and then comment out the line as follows `#map_file = 'captive-portals.txt'`
> 
> > My concern is total control of blocking.
> 
> You'll just make your internet unstable and your device unusable. If you see this address, you probably have google services installed. Therefore, you can start using a device without google services or flash a custom rom without google services.

Error message disappeared, and conected, but the issue still persist. Comment the line or delete it not affected to block the ip, I tried many times.

**Comment by Gedsh** [comment]
> but the issue still persist

Please show me a screenshot of the DNS tab and describe exactly how you are performing the test.

**Comment by smexyy** [comment]
> > but the issue still persist
> 
> Please show me a screenshot of the DNS tab and describe exactly how you are performing the test.

I copy and paste the ip in browser url and directed to google page, also ilI cleared cache from dnscrypt setting and app cache.

![Screenshot_20241017-002101~2](https://github.com/user-attachments/assets/447fa8e5-231d-4698-9708-811f02d1a042)

**Comment by Gedsh** [comment]
> I copy and paste the ip in browser

DNSCrypt is not a firewall. It does not block direct connection to IPs. It blocks DNSs that point to blacklisted IPs. If you are blocking 142.250.184.138, you should check sof02s43-in-f10.1e100.net in your browser.

**Comment by smexyy** [comment]
> > I copy and paste the ip in browser
> 
> DNSCrypt is not a firewall. It does not block direct connection to IPs. It blocks DNSs that point to blacklisted IPs. If you are blocking 142.250.184.138, you should check sof02s43-in-f10.1e100.net in your browser.

What about to block this ip 200.239.129.69, how it will implemnet?

**Comment by Gedsh** [comment]
Blocking a connection to an IP address directly is usually the responsibility of the firewall. But the firewall in InviZible does not have this capability yet. You can only block the app completely. You can consider using other firewall apps.

**Comment by smexyy** [comment]
> Blocking a connection to an IP address directly is usually the responsibility of the firewall. But the firewall in InviZible does not have this capability yet. You can only block the app completely. You can consider using other firewall apps.
Thank you.

**Comment by smexyy** [comment]
Thanks

**Comment by Gedsh** [comment]
You are welcome.
