### ISSUE TITLE
Unable to add remote IP Blackist

### ISSUE THREAD

**Issue by jamesta696** [Gedsh/InviZible#306]
Unable to load remote IP blacklist, also there's no place that shows the format of how the IP blacklist should look like? 

Unable to view the current IP blacklist, there's no button to show a preview. 

Current version v2. 3.4 beta

**Comment by Gedsh** [comment]
> Unable to load remote IP blacklist

Please provide a link so I can test it out.

>  there's no place that shows the format of how the IP blacklist should look like?

https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters

> Unable to view the current IP blacklist

There is no such option in the current interface. But you can see the size and number of rules, which is usually enough.
