### ISSUE TITLE
Confusing Version Numbers (F-Droid/Beta/Changelog)

### ISSUE THREAD

**Issue by GfEW** [Gedsh/InviZible#307]
### What's The Problem
The sections in the [changelog](https://github.com/Gedsh/InviZible/blob/HEAD/ChangeLog.md) linked to in the F-Droid details of InviZible Pro have these headers: 

_(start)_
**InviZible Pro 2.0.1 (beta 0.2.9)**
InviZible Pro beta 0.3 
InviZible Pro beta 0.3.1 
InviZible Pro beta 0.3.2
_[...]_
InviZible Pro beta 1.9.9
InviZible Pro beta 2.0.0
**InviZible Pro beta 2.0.1**
InviZible Pro beta 2.0.2
_[...]_
InviZible Pro beta 2.3.2
InviZible Pro beta 2.3.3
InviZible Pro beta 2.3.4
_(end)_

So, there's a "Pro 2.0.1" at the top and a "Pro beta 2.0.1" far down below. Without explanation or skilled guesswork, that's already confusing on its own. Is e. g. Pro beta 1.9.9 more recent than Pro 2.0.1?
**Why doesn't the "Pro" (without beta) version align with the "Pro beta" it is based on?**

It only gets worse with the versions shown **in F-Droid**, suggesting to

**update InviZible Pro "from 6.7.1 to 6.8.0"**.

Well, at least, they match the version numbering scheme in InviZible Pro's `Burger Menu` --> `About`.
**Where are the changes regarding _that particular_ update?**

**The confusion is aggravated by the fact that all three types of version numbers follow the same pattern, differing only by their digits (0.x.x vs 2.x.x vs. 6.x.x).**

### What should happen instead?
Even if folks who are closely familiar with the peculiarities of software development and versioning may manage to deal with that bewildering zoo of version numbers, checking the changelog when updating an important app is good practice for everyone who is able to perform manual updates in F-Droid at all.

**In any case, opening the changelog URL in F-Droid should allow you to see the changes to the _particular version_ you're about to install. Whilst it wouldn't make sense for everyone to check them at the source level, the most basic version info needs to be presented in a way that can be made sense of by the general userbase.**

Moreover, you might consider a switch to **using the same version numbers for all four InviZible Pro variants, distinguishing them by an articulate postfix** that becomes a part of the version string. 

E. g. 
* 6.8.0-beta (or 6.8.0-beta-001 etc. for subversions)
* 6.8.0-fdroid
* 6.8.0-google
* 6.8.0-lite.

Consistent, unified versioning would **vastly simplify and generally improve understanding** of any version/variant related information or discussion.

**Comment by Gedsh** [comment]
> Why doesn't the "Pro" (without beta) version align with the Pro Betas?

Why should it be? A beta version is intended for testing new features and in the first place should be convenient for the developer, but not for the user.

> switch to using the same version numbers for all four InviZible Pro variants

It's not planned.

> Where are the changes regarding that particular update?

I can make a separate changelog for the stable version. This is not a problem as I already publish it on github releases and play store. Is this a solution to your issue?

**Comment by GfEW** [comment]
> I can make a separate changelog for the stable version. _[...]_ Is this a solution to your issue?

With three different numbering schemes, the core confusion would remain. But if F-Droid linked to a dedicated stable changelog, the practical impact of this issue would be reduced by allowing F-Droid users to look up stable changes without forcibly running into confusing, look-alike variant versions.

> beta version is intended for testing new features and in the first place should be convenient for the developer, but not for the user.

I'm (obviously) aware of the purpose of betas. However, users and devs/testers aren't distinct groups, there's lots of overlap. I bet I'm not the only one who can't tell immediately _which is more recent, Pro beta 1.9.9 or Pro 2.0.1_, or who fails to grasp the _relation between those Pro 2.x.x and Pro 6.x.x numbers_. Is the former an extinct ancestor of the latter, or a separate up-to-date product? 

Whilst finding answers to such questions is certainly feasible given enough time, it would only take the blink of an eye if variant version numbers followed a unified scheme. 

Why not make everything consistent and thereby more accessible to everyone's understanding? It's trivial for _-google_, _-fdroid_ or _-lite_ variants (for suggestions, see OP), but there are also various possibilities, including the likes of 
* _6.8.0b-0172_ 
* _6.8.0b-17.2_
* _6.8.0-beta-17.2_

to make _beta_ versioning **fully consistent and fully granular at the same time**.

**Comment by Gedsh** [comment]
> I'm not the only one who can't tell immediately which is more recent, Pro beta 1.9.9 or Pro 2.0.1

How often do you use ancient versions of InviZible? Why do you use them? Why don't you just use the latest version so you don't have to find answers to such questions?

> make beta versioning fully consistent and fully granular at the same time

This would break the built-in update of the beta version, so it would require extra action and effort. I like to increment the beta and stable versions separately, using different schemes, which will be impossible. This change will cause a lot of questions from users wondering why this happened. I can spend my time more productively if I don't have to deal with the aforementioned issues.

> With different look-alike numbering schemes, the core confusion would remain.

So it's not something I'm going to fix. Thanks for the suggestion!
