### ISSUE TITLE
[Feature request] Show fastest DNS servers

### ISSUE THREAD

**Issue by be4zad** [Gedsh/InviZible#308]
In my country common HTTPS/TLS DNS servers are blocked and others are often slow. It would be great if InviZible could ping and show fastest DNS servers.

**Comment by Gedsh** [comment]
This feature is already available. Select the servers you want to test Menu -> Fast Settings -> Select DNSCrypt servers. Run DNSCrypt and wait for it to measure the pings. You can see them on the DNS tab.
