### ISSUE TITLE
dnscrypt time not correct

### ISSUE THREAD

**Issue by magixtruct** [Gedsh/InviZible#31]
dnscrypt doesn't sync the time with the system's. tor does correctly.
dnscrypt is always 1h back.
have the issue since weeks.
don't know if it affects functionality or not.

**Comment by magixtruct** [comment]
sent screenshots, but broken.
unable to re-upload.
tell me if you want to have screenshots again.

**Comment by magixtruct** [comment]
screenshots 8/3/20 10:18
[Screenshots.zip](https://github.com/Gedsh/InviZible/files/4303474/Screenshots.zip)

**Comment by Gedsh** [comment]
> dnscrypt is always 1h back

I think it uses UTC time.

> don't know if it affects functionality or not.

Does not affect. The logs in your screenshot show that everything is fine.

**Comment by magixtruct** [comment]
thank you.
