### ISSUE TITLE
Проблема с формой настройки subscriptions для i2pd

### ISSUE THREAD

**Issue by uap4** [Gedsh/InviZible#310]
Если в форме настройки subscriptions для i2pd введён только один адрес, то в i2pd.conf он будет внесён, но при повторном открытии формы там будет пусто.
Если в форме с несколькими записями какие-то записи были пустые, то эта пустота тоже будет перечислена через запятые в i2pd.conf. В при повторном открытии в форме пустых записей больше не будет.

У меня создалось впечатление, что в обоих случаях имело место только скрытие единственной или пустых записей, но они сами сохраняются и в настройках программы, а не только в i2pd.conf.

Проверил сейчас это на последней версии beta (странно, в логе написано 2235 2.3.5 , а в системе версия 2236 2.3.6), но сталкивался и намного раньше, насколько помню.

Во первых, попадание пустых адресов в i2pd.conf приводит к неминуемому вылету i2pd, когда дело доходит до обращения к таким. Разработчикам сообщено, исправление ожидается.

Во вторых, пропадание из формы записи с адресом в случае с единственной записью  явно неправильно.

Я считаю, что для правильной работы только пустые поля должны исключаться, причём до попадания в ту или иную конфигурацию.

**Comment by Gedsh** [comment]
Спасибо. Там был древний код, который давно никто не проверял. Этой фичей редко пользуются. Переписал его нормально. В следующей бете должно работать правильно.

> в логе написано 2235 2.3.5 , а в системе версия 2236 2.3.6

Хорошо подметили. Спасибо! Это глюк новой версии системы сборки проекта gradle. Откатился на прошлую версию.
