### ISSUE TITLE
AntiDPI, OpenVPN, Yggdrasil

### ISSUE THREAD

**Issue by Fenrir-0xFF** [Gedsh/InviZible#315]
Есть желание сие добавить? Просто удобнее когда всё в одном приложении, да и тотже i2pd иногда игдрасильские ip использует.  
Бинарики под arm7 найти не сложно, для обхода DPI на андроиде написал [скрипт](https://github.com/bol-van/zapret/issues/714) использующий zapret/nfqws но не у всех хватает интеллекта пользоваться консолью. 
OpenVPN и Tor можно будет использовать без мостов если их адреса блокируются через DPI а не через фаирвол, по крайней мере к udp портам пробиться удаётся.

**Comment by Gedsh** [comment]
Не может быть все в одном приложении. Я уже добавил максимум. Если добавить еще, приложение будет чрезвычайно сложно разрабатывать и пользоваться, а размер apk станет совсем неприличным.

**Comment by Fenrir-0xFF** [comment]
> приложение будет чрезвычайно сложно разрабатывать и пользоваться, а размер apk станет совсем неприличным.

Насчёт разработки тут основная сложность будет скорее всего в маршрутизации всего этого в одну кучю. 
А насчёт размера можно к примеру snowflake удалить, он больше всего весит, а мостов под него нормальных нет.
