### ISSUE TITLE
Exclude Tor-over-Tor apps

### ISSUE THREAD

**Issue by SkewedZeppelin** [Gedsh/InviZible#316]
See the list here https://github.com/guardianproject/orbot/pull/1204/files#diff-8f9719f61e572f2477bcd6194a494ff63e48a74334dace9b60b77836884444b9R173

**Comment by Gedsh** [comment]
Thanks. But I see no reason to exclude these apps without user consent. Unlike most other apps, InviZible allows to explicitly exclude these apps from Tor and still use Always On VPN and Block connections without VPN.

**Comment by SkewedZeppelin** [comment]
They won't work is why.
Since Tor won't let another Tor client bootstrap over it.

**Comment by Gedsh** [comment]
> They won't work is why.

They should work fine with bridges, even though it's not recommended.
