### ISSUE TITLE
[Q] Setup for GoodbyeAds possible ?

### ISSUE THREAD

**Issue by jerryn70** [Gedsh/InviZible#317]
Is it possible to setup GoodbyeAds in invisible pro ? 
We have this DNS setups;

DNS-over-HTTPS
1) https://sky.rethinkdns.com/1:gAAAAQ==
2) https://max.rethinkdns.com/1:gAAAAQ==
3) https://freedns.controld.com/x-goodbyeads
4) https://blitz.ahadns.com/1:17

DNS-over-TLS/QUIC
1) 1-qaaaaai.max.rethinkdns.com
2) x-goodbyeads.freedns.controld.com

**Comment by Gedsh** [comment]
> DNS-over-HTTPS

You can add custom DNSCrypt servers https://github.com/Gedsh/InviZible/wiki/Add-custom-DNSCrypt-server

> DNS-over-TLS/QUIC

This type is not supported by DNSCrypt.

If you would like to add these servers to the list of other DNSCrypt servers, which can be found in Menu -> Fast Settings -> Select DNSCrypt Servers, you need to contact the upstream DNSCrypt project https://github.com/DNSCrypt/dnscrypt-resolvers. I do not maintain a list of servers.
