### ISSUE TITLE
implement OpenVPN. feature.

### ISSUE THREAD

**Issue by DI555** [Gedsh/InviZible#32]
please, forgive me ;) , but due to inconvinience with local_vpn only one instance and great kind of IZ to rule of console apps with its config files , - i'd like to ask about very useful feature -
it's OpenVPN implementation ! (OpenVPN for now, but may be lately it could be a better VPN app wich will support more VPN protocols)
it's easier, i'd like to suggest to fork this project:
github.com/MaxSmile/EasyVPN-Free
it's sources, sadly, was not updated for couple years, but project is alive:
play.google.com/store/apps/details?id=com.vasilkoff.easyvpnfree

**Comment by DI555** [comment]
it parces www.vpngate.net site for a huge .csv list. as it's said there're about 10000 free vpns points by volunteers.
imo in a future could be possible to parce some other places for other vpns with a different and  better protocols, but about it better to talk later ;).

**Comment by SamuelP1111** [comment]
Hi,

I don't think it's very interesting to add openvpn. There is TOR yet, and it does same thing.

Openvpn has already some very good and.

We don't need "factory" but simple functions very stable and strong.

**Comment by DI555** [comment]
@SamuelP1111 , you never use any proxy_vpn, bro, do you ;) ?
so, i see , the difference beetween them is very small for you..., it's sad... .

About  OpenVPN Android existent one, it's not bad, but unusefull without handle many vpns... , only one vpn address, typed by hands...
And, please, don't tell 'we', say only me...

**Comment by Gedsh** [comment]
I thought about that. To use VPN over Tor with one click. But it is not easy. Maybe in the future.

**Comment by SamuelP1111** [comment]
.. Yes i use vpn too...and i know vpn over tor too..and i think again we really don't need openvpn in this kind of application.

Maybe i misunderstood.

openvpn is obsolete, do you know wiregard and others app?

**Comment by SamuelP1111** [comment]
I just realize, i really don't need to send logs during month and feedback and suggestions and concept and others here.
And you don't need me, and i think you need absolutely nobody ...bro.

I'm sorry to disturb you.

I will try to delete my account definitely.

Good luck for all.

Very nice place and guys....

**Comment by Gedsh** [comment]
Maybe I don’t understand something, but someone needs to sleep ...

**Comment by DI555** [comment]
@Gedsh , thank you for answer ! I thought if sources are exist,- it could be very easier to integrate OpenVPN to IZ...
and the goal of connecting to many SoftEatherVPN servers is not bad, what do you think?
did you see the code of 'github.com/MaxSmile/EasyVPN-Free' ?

**Comment by Gedsh** [comment]
> I thought if sources are exist,- it could be very easier to integrate OpenVPN to IZ...

No. But a little easier than without sources.

> and the goal of connecting to many SoftEtherVPN servers is not bad, what do you think?

Sure.

> did you see the code of 'github.com/MaxSmile/EasyVPN-Free' ?

Not yet.

**Comment by magixtruct** [comment]
hi ghost! I'm very sorry to see you go & that a post of just one user here has made you so angry. I want to tell you, I think that this project doesn't reflect the opinion of this 1 user. and again, I'm very sorry to see you go. IMO you'd be an enrichment to this project with all your experience.
and yes, it is well known, that tunneling tor through vpn & vice versa has more disadvantages than advantages. and it makes the already mostly slow tor connection even slower.
there is protonvpn that does this well. but they have a bunch of money & the best scientists behind them.
if such a thing should be realized with iz it has to be better than everything before, and I could only imagine it with a stealth vpn connection, what brings us back to the point that the vpn connection will be even more slow.
I myself, am not a developer, can't do much more than a few lines of code, some knowledge & a little hacking, am still learning.
so I believe, people like ghost with deeper knowledge are important to this project.
and I've read some real useful comments & guides here on github in the past, written by ghost, that helped me much.
so from my side: ghost, please come back here, with your account deleted, some valuable knowledge is lost here on github. we need you.
and I think, we all shouldn't be too rude with each other. when ghost says 'we', I understand it as that what is known in the internet community. furthermore, I find, we shouldn't fight each other with our egos, there's something else to fight.

**Comment by DI555** [comment]
@Gedsh , that guy is just a bot imho))
but anyways, may be are the plans to make a separate app, using that sources from (github.com/MaxSmile/EasyVPN-Free) ?
