### ISSUE TITLE
build timestamps break reproducible builds

### ISSUE THREAD

**Issue by eighthave** [Gedsh/InviZible#321]
https://github.com/Gedsh/InviZible/blob/d86b99fb4f356396953140317c55c6062e12244e/tordnscrypt/build.gradle#L72

I recommend using the `SOURCE_DATE_EPOCH` standard for build timestamps. The build timestamp is set based on the current commit that is being built. This is the widely implemented:
https://reproducible-builds.org/docs/source-date-epoch/

It could look something like this:
```diff
-        buildConfigField "java.util.Date", "BUILD_TIME", "new java.util.Date(" + System.currentTimeMillis() + "L)"
+ def buildDate = System.getenv("SOURCE_DATE_EPOCH") == null ?
+  new java.util.Date() :
+  new java.util.Date(1000 * Long.parseLong(System.getenv("SOURCE_DATE_EPOCH")))
+        buildConfigField "java.util.Date", "BUILD_TIME", "new java.util.Date(" + buildDate + ")"
```

## example diffs

```diff
- vcs.time=2024-07-26T11:38:39Z
+ vcs.time=2024-12-07T21:58:45Z
```

```diff
- 2024-06-06
+ 2024-10-24
```

* https://verification.f-droid.org/pan.alexander.tordnscrypt.stable_23203.apk.diffoscope.html#classes.dex---classes.jar---P--l.class
* https://verification.f-droid.org/pan.alexander.tordnscrypt.stable_23203.apk.diffoscope.html#lib-arm---v-a-libtor.so---strings---all---bytes-----

Also, it looks like the tor build is using a branch rather than a fixed commit ID or tag.  So builds in the future get newer tor commits.

**Comment by Gedsh** [comment]
Fixed via https://github.com/Gedsh/InviZible/commit/2377e28a77802b46626e8925051576820557018a

> Also, it looks like the tor build is using a branch rather than a fixed commit ID or tag.

I use my own forks for DNSCrypt, Tor, and all Tor pluggable transports that contain small but important changes for better use on mobile devices. I keep these forks up to date with upstream repositories. I can't use tags, as I prefer to have the latest fixes than wait a year sometimes for a new tag. And I don't want to use commit IDs, as it would be very annoying to have to update them every time for all my forks.

**Comment by eighthave** [comment]
2377e28a77802b46626e8925051576820557018a looks good!

Unless you use commit IDs, then your app won't be reliably reproducible.  But that's up to you.  For an app like yours, I think it is definitely worth the minor annoyance of using commit IDs.
