### ISSUE TITLE
[Help Support] Detect update system service

### ISSUE THREAD

**Issue by Erz3** [Gedsh/InviZible#322]
Hi, everyone.

I bought my new Google Pixel 7 recently, It's the first time with this brand and I don't know what service or application need network permission in IZ-Firewall to update Android 15. Actually I am working with the minimum amount of permission, It's granted to Google Play Services and work great to update Google Play apps and Google Play system itself (System settings > Security and Privacy > System and Updates) without connectivity errors. However, The opposite happens with Android updates because IZ-Firewall is blocking something needed.

I have enabled some services/apps in "system" section on IZ-Firewall that It make me think are needed but nothing work. I have tried detect the required dependency with DNS queries registry on IZ-Firewall but no new entries are created by the update's process.

Have someone solved this with the same smartphone? Do someone have any idea to detect witch service/app/dependencies need network permisión in IZ-Firewall?

Thanks you in advance and merry Christmas.

**Comment by Gedsh** [comment]
Hi,

I think you'll faster get an answer on telegram or matrix as I don't have such a phone. But I can suggest allowing internet connection for Android system (UID 1000). https://github.com/Gedsh/InviZible/wiki/Firewall

What services are you using exactly, Tor, DNSCrypt?

Merry Christmas!

**Comment by Erz3** [comment]
At the end, It was "root" with UID 0. I found It with "Real-time logs" (IZ Pro's functionality), so now everything go fine.

Thanks you for your time, I get your advice and I will join community groups to ask about this kind of questions.

You are doing a great job, keep going!

**Comment by Gedsh** [comment]
> At the end, It was "root" with UID 0.

Great to know you've found a solution

> You are doing a great job, keep going!

Thank you!
