### ISSUE TITLE
features request 

### ISSUE THREAD

**Issue by allmightyasian** [Gedsh/InviZible#327]
First option for excluding apps from firewall,
Second option for whitelist apps from running logs,
Third domain based blocking and unblocking

**Comment by Gedsh** [comment]
> First option for excluding apps from firewall
> Second option for whitelist apps from running logs

Menu -> Fast Settings -> Exclude applications -> Exclude entirely
https://github.com/Gedsh/InviZible/wiki/Quick-Guide-in-Pictures-(VPN-mode,-Root-mode)

> Third domain based blocking and unblocking

Menu -> DNSCrypt Settings -> Blacklist
