### ISSUE TITLE
Notification Off Vs Disconnecting 

### ISSUE THREAD

**Issue by smexyy** [Gedsh/InviZible#328]
Hello, if I toogle off all InviZible pro notifications, it will disconnect, and reconnect.

Info: Android 14 - google pixel
InviZible 2.4.2
Always on vpn + block connection is enabled.

Screen record https://streamable.com/e/m31duz

**Comment by Gedsh** [comment]
> Hello, if I toogle off all InviZible pro notifications, it will disconnect, and reconnect.

Hello, this behavior depends only on the android. InviZible cannot do anything about it.

> Always on vpn + block connection is enabled.

This way you don't have any leaks, and you only need to start InviZible again. But keep in mind that on some phones, disabling all notifications will cause battery saver to kill InviZible in the background at any time.
