### ISSUE TITLE
Allow natively and by default non-Tor and IANA environments

### ISSUE THREAD

**Issue by xp499** [Gedsh/InviZible#33]
Non-tor and IANA reserved IP blocks are being routed by default from apps and another system connections through Tor when they shouldn't. I didn't checked the source code but i can guess by the behaviour that you're applying different filters to handle apps and hostnames differently, even if some of the blocks are already being treated by your default iptables ruleset.

Those filters seems to take higher priority than iptables ruleset as when you add them manually to Invizible IP/app whitelist config they start working as they should.

In my Ansible playbook for deploying Tor to any Linux i have these blocks, taken from Tor Trac Wiki:

non_tor_env:
  - "127.0.0.0/8"
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"

IANA_reserved_blocks:
  - "0.0.0.0/8"
  - "100.64.0.0/10"
  - "169.254.0.0/16"
  - "192.0.0.0/24"
  - "192.0.2.0/24"
  - "192.88.99.0/24"
  - "198.18.0.0/15"
  - "198.51.100.0/24"
  - "203.0.113.0/24"
  - "224.0.0.0/3"

Also commands/orders to apply them:

- name: Disabling NAT for loopback and for local network
        become: true
        become_user: root
        iptables:
          chain: OUTPUT
          out_interface: "lo"
          table: nat
          jump: RETURN

- name: Allow access TO non tor environments
        become: true
        become_user: root
        iptables:
          chain: OUTPUT
          destination: "{{item}}"
          table: nat
          jump: RETURN
        with_items:
          - "{{non_tor_env}}"
          - "{{IANA_reserved_blocks}}"

Reference: [https://trac.torproject.org/projects/tor/wiki/doc/TransparentProxy](https://trac.torproject.org/projects/tor/wiki/doc/TransparentProxy)

**Comment by Gedsh** [comment]
Thank you. I will add this as an option. This will increase the time that iptables rules are applied and may cause problems on some devices.

**Comment by xp499** [comment]
If performance will be affected and also could cause malfunctions, preferrebly we have to discuss alternatives.

For example, add these hosts, if and when possible, to IP whitelist easy feature already provided by Invizible if this causes less conflicts with current app logic.

You just have to add support for entire network blocks to it for applying correctly.

Althought i would think this won't be the proper solution, I'm just making proposals to hear from you which one would fit best for your app.

**Comment by Gedsh** [comment]
I know that it is correct to add these addresses. But in real life, we have android limitations. Therefore, I think that the corresponding option will be a compromise.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
this requires chaning "`10.0.0.0/8`" by `VirtualAddrNetwork` of tor.conf
consider adding 
```
VirtualAddrNetworkIPv6
PreferIPv6Automap
```

**Comment by Gedsh** [comment]
> VirtualAddrNetworkIPv6
PreferIPv6Automap

InviZible blocks ipv6 due to security issues in Root mode. It is possible to allow ipv6 in VPN mode, but investigation is required.

**Comment by xp499** [comment]
> this requires chaning "`10.0.0.0/8`" by `VirtualAddrNetwork` of tor.conf
> consider adding
> 
> ```
> VirtualAddrNetworkIPv6
> PreferIPv6Automap
> ```

Networks like 10.0.0.0/8 should never be routed under Tor. Those are strictly defined as non-Tor environments.

By defining `VirtualAddrNetwork` under 10.0.0.0/8 makes sense as this is made for resolving and stablishing a "virtual local environment" in order to easily enroute requests to special .onion hidden services which otherwise would be impossible to map outside of Tor network logic.

**Comment by Gedsh** [comment]
Added in 1.0.8 beta
