### ISSUE TITLE
autonome socks5 proxy

### ISSUE THREAD

**Issue by magixtruct** [Gedsh/InviZible#34]
hi @Gedsh,
what about implementing a socks5 proxy service, that doesn't route through tor? I'd like to see that, cause it'd be great to encrypt my dns requests with dnscrypt-proxy & route my traffic then to a socks5 proxy server of my choice... . any chance?

greetings 🐱‍🚀

**Comment by Gedsh** [comment]
Perhaps in the future I will implement OpenVPN or ShadowSocks or Socks5. But perhaps it will be a separate application with DNSCrypt and socks5 proxy, for example.

**Comment by magixtruct** [comment]
thad't be great!

**Comment by Gedsh** [comment]
Implemented in beta 1.0.3
20227132531a3734bd03c865b267b6d8367b149f
