### ISSUE TITLE
Quick toggle switch (and optionally captive portal detection)

### ISSUE THREAD

**Issue by darylrobert** [Gedsh/InviZible#35]
- implement a quick toggle switch to stop and start service
- optionally disable service when connecting to a network with captive portal or handling it gracefully allowing authentication without disabling service

**Comment by Gedsh** [comment]
> implement a quick toggle switch to stop and start service

For what purpose?

> optionally disable service when connecting to a network with captive portal or handling it gracefully allowing authentication without disabling service

I don’t like options that can automatically affect privacy. Just stop InviZible manually. It's very fast.

**Comment by darylrobert** [comment]
Quick toggle switch for logging into captive portal

**Comment by magixtruct** [comment]
afaik you can whitelist captive portal in iz/it's whitelisted by default. so this should address this purpose?
