### ISSUE TITLE
x86 and x86_64 support

### ISSUE THREAD

**Issue by st0rmr1der1994** [Gedsh/InviZible#39]
Hello, I have noticed that libdnscrypt-proxy.so is present only for arm and arm64 (according to lib directories).
Do you have any plans to extend architectures support and include x86 and x86_64 too?
If no, can you please suggest how to build dnscrypt-proxy *.so libs for this architectures?
I'm searching for non-Root DNSCrypt support and it will be nice to have all architectures covered

**Comment by Gedsh** [comment]
> Do you have any plans to extend architectures support and include x86 and x86_64 too?

Unfortunately no.

> can you please suggest how to build dnscrypt-proxy *.so libs for this architectures?

These are not really libs. These are executable files from the official DNSCrpyt website, renamed to * .so

**Comment by st0rmr1der1994** [comment]
Thank you for response
