### ISSUE TITLE
Allowed domain as request to bypass firewall.

### ISSUE THREAD

**Issue by ingnelson** [Gedsh/InviZible#40]
Hello sir.
Is there a way you can add a option to add a allowed domain or website for the request ?
I explain : 
ISP firewall let us visit free some websites , 
Example 1 http:
we use those websites as a http request (http injection) and we create a tunnel via shadowsocks or ssh or vpn etc to bypass the firewall.
Example 2 TLS:
For TLS tunnel we use "fake SNI " se add the allowed website for the firewall.

Is there a way to add a domain as request to bypass our firewall using your inviZible app ?
This way the firewall let the tunnel go through.

By the way , I know it is possible to bypass my Firewall using a " binary proxy  (convert request to binary ) + shadowsocks" or "fragment proxy (fragment request ) + shadowsocks".

I will wait your answer.

**Comment by Gedsh** [comment]
Hello. This feature is not yet planned.
