### ISSUE TITLE
DNSCrypt - Download and update blacklists

### ISSUE THREAD

**Issue by pkejval** [Gedsh/InviZible#41]
Hello, just suggestion for new feature. Can you add feature to manage and update blacklists?

You can use DNSCrypts utility https://github.com/DNSCrypt/dnscrypt-proxy/tree/master/utils/generate-domains-blacklists and make GUI and scheduled task for it.

**Comment by Gedsh** [comment]
Thank you for the suggestion. This feature is planned. You can use local import of DNSCrypt blacklist files until I add it.

**Comment by Gedsh** [comment]
This is fixed via https://github.com/Gedsh/InviZible/commit/f475d8a497dc00722b5f899fc76be93856e1a495
