### ISSUE TITLE
[Feature Request] Tiles & Widgets

### ISSUE THREAD

**Issue by dhammel** [Gedsh/InviZible#44]
Hello,

Would you consider adding tiles in notification bar as well as widgets for quickly starting/stopping service, for the 3 modules?

**Comment by Pranab009** [comment]
Yeah this is an important feature. Please work on it.

**Comment by Gedsh** [comment]
Tiles added in InviZible Pro beta 1.3.8

**Comment by infectedw** [comment]
Widgets are greate idea, with graph KB/s IN and KB/s OUT.
