### ISSUE TITLE
Add Compile scripts for libs

### ISSUE THREAD

**Issue by 6543** [Gedsh/InviZible#45]
this would make #5 mouch easyer ...

In short: create single scripts who compile lib's found in [tordnscrypt/libs](https://github.com/Gedsh/InviZible/tree/master/tordnscrypt/libs) on demand ...

**Comment by Gedsh** [comment]
Add script for building Tor for Android from source using Gitlab CI / CD https://github.com/Gedsh/Tor-Android-build-script

**Comment by Gedsh** [comment]
Added script for building Purple I2P from source using Gitlab CI / CD https://github.com/Gedsh/Purple-I2P-Android-build-script

**Comment by Gedsh** [comment]
Done #46
