### ISSUE TITLE
InviZible without Tor and I2P

### ISSUE THREAD

**Issue by NT20** [Gedsh/InviZible#49]
Hi!

Do you have any plan to release a "lighter version" of InviZible without Tor and I2P? That would be perfect for users who want to encrypt their DNS requests and nothing else.

Thanks!

**Comment by Gedsh** [comment]
Hi,

I see no point in such an application. There are many applications that can simply encrypt DNS. You can take a look at personalDNSfilter https://zenz-solutions.de/personaldnsfilter/

**Comment by NT20** [comment]
Hi

I just tested pDNSf. it's buggy and it leaks DNS requests.

**Comment by Gedsh** [comment]
This is strange. It usually works well and is very lightweight.

**Comment by NT20** [comment]
Unfortunately I found the leak in my NextDNS logs, It was only one domain and a single request.




> 
> 
> Hi,
> 
> I see no point in such an application.

Well then, please feel free to close the issue, Thanks for your hard work @Gedsh .

**Comment by Gedsh** [comment]
Thank you for testing the beta!
