### ISSUE TITLE
[Feature Request]Lokinet and Firewall feature like Netguard

### ISSUE THREAD

**Issue by o700** [Gedsh/InviZible#51]
Hi.Thank you so much for make this great app.
Can you implement per app firewall like Netguard?

https://github.com/M66B/NetGuard
Here is app and source code.

And lokinet is anonymizing and anticensorship tool that similar to tor.
It available only for Desktop at now.
https://lokinet.org/

**Comment by o700** [comment]
I found proxy mode can use Invizible and netguard.
https://github.com/Gedsh/InviZible/wiki/InviZible-and-NetGuard-firewall

Please ignore about netguard.
Is it able to implement lokinet?

**Comment by Gedsh** [comment]
Hi. Thank you!

I have no plans to add additional anonymous networks. It will be very difficult to set up and use InviZible with more than 3 modules. But for now I am implementing a firewall feature for use in Root and VPN modes.

**Comment by DI555** [comment]
oh, great, finally !!! i hope the firewall not worse than from ancle Marcel ;) ?! so can i easily skip to IZ-firewall from NG ? ui is almost the same ?

**Comment by Gedsh** [comment]
> i hope the IZ-firewall not worse than from ancle Marcel

The principle is the same, so it should be just as effective.

> so can i easily skip to IZ-firewall from NG ?

If you are not using the advanced features of NG.

> is ui almost the same ?

More like AfWall, but with material design.
