### ISSUE TITLE
misprint "Испоьзовать"

### ISSUE THREAD

**Issue by uap4** [Gedsh/InviZible#52]
Missing letter "л" - "Использовать".
https://github.com/Gedsh/InviZible/blob/3bdcb40ad3d729ce31c0bdef31dd235fac2bea76/tordnscrypt/src/main/res/values-ru-rRU/strings.xml#L426-L427
https://github.com/Gedsh/InviZible/blob/3bdcb40ad3d729ce31c0bdef31dd235fac2bea76/tordnscrypt/src/main/res/values-ru-rUA/strings.xml#L427-L428

**Comment by Gedsh** [comment]
Спасибо! В следующей версии будет исправлено.

**Comment by uap4** [comment]
Version 1.1.3 does not have this problem.
