### ISSUE TITLE
Does InviZible Pro support Host filter list ?

### ISSUE THREAD

**Issue by Moxville** [Gedsh/InviZible#53]
Hi,

Thanks for the nice Application

How to add Ad host filter lists like...
adaway.org
energized.pro
github.com/StevenBlack or StevenBlack Unified
DuckDuckGo Tracker Radar
MVPS
Dan Pollock’s hosts file
Peter Lowe’s hosts file
Phishing Army Blocklist
Goodbye Ads by Jerryn70
YouTube ad blocker by Jerryn70

**Comment by Gedsh** [comment]
Hi,

MENU -> DNSCrypt Settings -> Import blacklist

This feature is not available in the Play Market version.

**Comment by chris-tian78** [comment]
Is it also possible to enter the http address directly here? Also, then an autoupdate function would not be bad.

**Comment by Yquas** [comment]
@chris-tian78 As of now, it is not possible to add links to host filter lists, you have to download and import them manually, and you need to redownload them to get the update and import them again.. Maybe it's an idea to add this too, @Gedsh? Like NetGuard does it, but maybe with more than just one adress too.

**Comment by Gedsh** [comment]
Hello, @Universalizer 

Auto-updating of filters is planned. But this task has no priority, since InviZible is not an ad blocker. It is usually enough to update the DNSCrypt blocklist once every few months to ensure reliable protection.

**Comment by BRBsoup** [comment]
> Hello, @Universalizer 
> 
> Auto-updating of filters is planned. But this task has no priority, since InviZible is not an ad blocker. It is usually enough to update the DNSCrypt blocklist once every few months to ensure reliable protection.


Any progress on auto-updating subscription lists? Bleeding-edge filter lists seem to be a security and privacy consideration as well:

Especially mobile app Android trackers, which are today widespread ND nefarious enough to phone home all sorts of sensor data and operating environment variables and will synchronize advertising IDs with local cookies, network data, etc... so if not sufficiently blocked, essentially could render the entire InviZible Pro app as moot... and as we all know this is not isolated or theoretical behavior - just take a look at DNSCrypt log and the app trackers getting through as possibly complete identity leaks updating your corporate advertising dossier in real-time. 

Thankfully there now exist several mobile-specific lists around, with the most promising being DuckDuckGo's Android Trackers research list and the Blokada implementation of it which is a whitelisting stack to restore app and website broken functionality (considering the effort and scope of that "collaboration" one could imagine how remote-DNS-based tracker protections are currently extremely lacking in both actual blocking and trustworthiness - the one Android specific filtering DNS server included in the InviZible Pro server list is even unfortunately flagged as "possible lying resolver" in red in the log when being bootstrapped!)

So I don't have the answers but I thought these might be important aspects to consider on the + side for implementing subscription lists (would even be nice addition for the DNS server list + PING ms delays etc. - just another thought!)

Either way, true, it's more than functional as is and InviZible Pro is somewhat of a best-kept-secret Swiss army knife of Android privacy, so thanks!

TL;DR: 
While InviZible Pro is very capable as is, the ubiquity and threat of advertising trackers and overflow of apps big and small abusing OS permissions, etc., in the mobile and specifically Android ecosystem (with even the most popular manufacturers baking analytics and advertising into their Android products), is a glaring security/privacy leak and blindspot which if not specifically and carefully solved for already likely makes many privacy/proxy/anonymizing configurations of all sorts completely ineffectual - so while subscription blacklist/whitelist filters, etc., would be a great bonus in this regard, the lack of properly utilizing and updating them even as-is to minimize these vulnerabilities, is an even greater failure of privacy!

**Comment by Gedsh** [comment]
This is fixed via https://github.com/Gedsh/InviZible/commit/f475d8a497dc00722b5f899fc76be93856e1a495
