### ISSUE TITLE
[Feqture Request]Arm64 on F-Doid

### ISSUE THREAD

**Issue by Raul1198** [Gedsh/InviZible#54]
I was using Auror Droid ( F-Droid's client ) and when sesrched for InviZibrl there it shows only arm7a. But here in release we get arm64 .

**Comment by Gedsh** [comment]
Sorry, I am not uploading InviZible in Aurora Droid. I can not help you.

**Comment by Raul1198** [comment]
> Sorry, I am not uploading InviZible in Aurora Droid. I can not help you.

Aurora droid is just a Fdroid client.

**Comment by Gedsh** [comment]
I know. But someone has to upload it.

**Comment by Raul1198** [comment]
> I know. But someone has to upload it.

I found a solution to this , I'll get the release notification directly whenever there's a new release 😏✌️
