### ISSUE TITLE
(Feature Request) Connect (Start)/Disconnect (Stop) in Notification

### ISSUE THREAD

**Issue by Raul1198** [Gedsh/InviZible#55]
![Screenshot_20201123-125817_Lawnchair (1)](https://user-images.githubusercontent.com/29801315/99937597-20915980-2d8c-11eb-8d6d-420f20efb134.jpg)
It would be easier if we have a start or stop option in Notification so as to quickly turn on or off rather than going into the app.

**Comment by Gedsh** [comment]
Thank you for the suggestion! I don't like large notifications, so I planned to add quick setting tiles for this purpose.

**Comment by Gedsh** [comment]
Tiles added in InviZible Pro beta 1.3.8
