### ISSUE TITLE
Setting for automatically allowing new apps through firewall

### ISSUE THREAD

**Issue by Brawl345** [Gedsh/InviZible#56]
I like the firewall feature in InviZible Pro but it currently blocks new apps which I always forget. Can you please add a setting that lets new apps automatically through the firewall? Thanks.

**Comment by Gedsh** [comment]
Thanks for the suggestion! I will try to add it in the next version.

**Comment by DI555** [comment]
...may be and an option to popup remindness with 'allow' or 'deny' ?

**Comment by Gedsh** [comment]
@DI555 Already done.

**Comment by Gedsh** [comment]
Implemented in InviZible Pro beta 1.1.8
