### ISSUE TITLE
Version 5 shows as lite

### ISSUE THREAD

**Issue by fusionneur** [Gedsh/InviZible#57]
I downloaded pro, but it shows as lite. Whatdoes pro really mean? Is there any difference between lite and pro. Will the app be paid in the future?

**Comment by Gedsh** [comment]
InviZible has long had paid features in the stable version. This makes it possible to continue development. So you can donate and get the stable premium version. The premium version has automatic updates and has no project support reminders, unlike the Lite version.

The beta version is required to test new features. You test the beta, send me logs, and thus support development. This is why the beta is free and will always be free.

Currently 1.1.5 is beta, 5.0.0 is stable.

**Comment by fusionneur** [comment]
Thank you for the clarification. Just a suggestion: there are various places within the app, where 'pro' term is used, even if it is the lite version, which creates a bit of confusion.

**Comment by Gedsh** [comment]
Yes, I know the 'pro' prefix can be confusing. But 'pro' is just part of the application name and makes sense, since InviZible Pro is intended for professional use, as it contains low-level options for DNSCrypt, Tor and I2P.

In any case, it is too late to change the app name.

**Comment by fusionneur** [comment]
What logs are sent in beta and towards which endpoint?

**Comment by Gedsh** [comment]
Neither version of InviZible sends logs anywhere. You can send logs only if you want to invizible.soft@gmail.com

If you have a version of InviZible not from the Play Market installed and auto-update is enabled, it checks once a day for a new version on invizible.net.
