### ISSUE TITLE
Does InviZible Pro support Anonymized DNS?

### ISSUE THREAD

**Issue by serovar** [Gedsh/InviZible#61]
I am referring to [this](https://github.com/dnscrypt/dnscrypt-proxy/wiki/Anonymized-DNS).

**Comment by Ilithy** [comment]
Hello, yes but these settings are not directly modifiable from the InviZible Pro interface, you must modify the dnscrypt-proxy.toml file (accessible from the DNSCrypt settings):
![Screenshot_20201221-214645](https://user-images.githubusercontent.com/36798218/102820858-408d5a80-43d6-11eb-8ac3-086f5f2375d5.jpg)

You will find at the end of the file the lines corresponding to what you are talking about (anonymized DNS):
![Screenshot_20201221-214902__01](https://user-images.githubusercontent.com/36798218/102821005-8a764080-43d6-11eb-9a00-25e681d1be6a.jpg)

Have a nice day

**Comment by serovar** [comment]
Perfect, thank you.

**Comment by Gedsh** [comment]
@serovar Sure! 
![screenshot_21 12 2020_23 31 18](https://user-images.githubusercontent.com/48843569/102824213-1000ed00-43e5-11eb-8751-8cc708e06c9a.png)

> are not directly modifiable from the InviZible Pro interface

InviZible has UI for this ;)

**Comment by serovar** [comment]
Great, thank you very much!

**Comment by Ilithy** [comment]
>InviZible has UI for this ;)

Too strong! \o/
Sorry for my stupidity and thank you for the information.

**Comment by Gedsh** [comment]
@Ilithy No problems. I'm here to help. InviZible is a complex application.
