### ISSUE TITLE
VPN is set as metered connection

### ISSUE THREAD

**Issue by Brawl345** [Gedsh/InviZible#62]
If VPN mode is active (even if only used with DNSCRYPT) the VPN connection will create a "metered" connection, meaning that all apps think they are on cellular data when in fact I'm on wifi. This leads to problems with several apps, like the Play Store not updating or downloading apps since it "thinks" I'm not on Wifi.

There are other VPN apps that ran into the same issue, like:

* Blokada: https://github.com/blokadaorg/blokada/issues/790 (fixed in https://github.com/blokadaorg/blokada/blob/89fbe0221ef9f539b2b7590bccf8c92b75c05a41/android5/app/src/engine/kotlin/engine/SystemTunnelConfigurator.kt#L70)
* or ProtonVPN: https://github.com/ProtonVPN/android-app/issues/52 (fixed in https://github.com/ProtonVPN/android-app/blob/29d43af9835a7ad728a74a44877010397e9fdb07/app/src/main/java/org/strongswan/android/logic/CharonVpnService.java#L643)

**Comment by Gedsh** [comment]
This is very strange, because InviZible detects metered network or not with the upstream network. 

Thus, you will have metered network on cellular data and non metered on WiFi. 

Are you sure you have this issue?

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            builder.setMetered(Util.isMeteredNetwork(this));
 }

public static boolean isMeteredNetwork(Context context) {
        ConnectivityManager cm = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        return (cm != null && ConnectivityManagerCompat.isActiveNetworkMetered(cm));
 }
```

**Comment by Brawl345** [comment]
Very strange indeed. It works when I disable and enable InviZible again, but after some time it seems to stop working. I have Always-On-VPN active and blocking all non-VPN connections if that matters. I'm using a Mi 9 Lite on MIUI 12/Android 10.

I've now downloaded an app which tells the network type and I'll keep an eye on this. But yeah, according to the code you posted it should work. Could also be some MIUI fuckery, who knows.

**Comment by Gedsh** [comment]
Some roms may return null in context.getSystemService(Context.CONNECTIVITY_SERVICE) when blocking all non-VPN connections feature is enabled. But even so you will have setMetered (false)

Perhaps this problem is related to MIUI. If you have any details, please contact me.

**Comment by Gedsh** [comment]
I decided to explicitly set the unmetered connection https://github.com/Gedsh/InviZible/commit/02bfd36daa59dc1983e8255faae447ddcbae1103 https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)

**Comment by Brawl345** [comment]
Just to report back: Since the update I haven't had any problems. Thanks!

**Comment by Gedsh** [comment]
Thank you for the detailed report! It was easy to make this successful experiment.
