### ISSUE TITLE
Support p2p filetype IP blocklist

### ISSUE THREAD

**Issue by gnuhead-chieb** [Gedsh/InviZible#66]
Currently,Invizible isn't supporting p2p filetype ip blocklist that can download in [iblocklist.com](https://www.iblocklist.com/lists)
so we have to convert(`sed -e "s/.*://g" -e "/^$/d" -e "/#/d"`) it before import blocklist.
It will better to make importable p2p type blocklist directly.

**Comment by Gedsh** [comment]
To support p2p blocklists, DNSCrypt should support blocking IP ranges. But as far as I know, it doesn't support. Therefore, it cannot be supported in InviZible.
