### ISSUE TITLE
[docs]Remove hiddenwiki's link and use another onion sites.

### ISSUE THREAD

**Issue by gnuhead-chieb** [Gedsh/InviZible#67]
https://github.com/Gedsh/InviZible/wiki/How-to-check-if-the-app-is-working-correctly.
https://invizible.net/en/how-to-check-the-app/

Hiddenwiki contains many fraud related links like cardings.
Use another onion instead is more better.
vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion
Here is riseup's onion mirror.

**Comment by Gedsh** [comment]
> Hiddenwiki contains many fraud related links like cardings.

This is just an example.

> Here is riseup's onion mirror.

Why should I advertise VPN? I don't trust any VPN.
