### ISSUE TITLE
Not working with default setting on Xiaomi Redmi Note 7 (default ROM)

### ISSUE THREAD

**Issue by Alexdiff** [Gedsh/InviZible#69]
I cannot make the app to connect to Tor, DNSCrypt and even i2p, the first thing I do is Force Shutdown the app, and it's not solve the problem, Restart the phone and now it's still not connect.![IMG_20210302_144326.jpg](https://user-images.githubusercontent.com/46273530/109614821-b3008080-7b65-11eb-80d9-712313a6e229.jpg)![IMG_20210302_144308.jpg](https://user-images.githubusercontent.com/46273530/109614835-b85dcb00-7b65-11eb-8154-8d1b4d9518a8.jpg)![IMG_20210302_144250.jpg](https://user-images.githubusercontent.com/46273530/109614849-be53ac00-7b65-11eb-8374-b41ca4a73c1d.jpg)

**Comment by chris-tian78** [comment]
5.1.0 is not working on xiaomi/ Poco. try the 1.2.3 Beta. working for me on poco m3

**Comment by linsui** [comment]
If it's downloaded from f-droid, it's broken.

**Comment by Alexdiff** [comment]
> I cannot make the app to connect to Tor, DNSCrypt and even i2p, the first thing I do is Force Shutdown the app, and it's not solve the problem, Restart the phone and now it's still not connect.![IMG_20210302_144326.jpg](https://user-images.githubusercontent.com/46273530/109614821-b3008080-7b65-11eb-80d9-712313a6e229.jpg)![IMG_20210302_144308.jpg](https://user-images.githubusercontent.com/46273530/109614835-b85dcb00-7b65-11eb-8154-8d1b4d9518a8.jpg)![IMG_20210302_144250.jpg](https://user-images.githubusercontent.com/46273530/109614849-be53ac00-7b65-11eb-8374-b41ca4a73c1d.jpg)

There's a settin' called “Compatibility mode”, I think 5.1.0 should work when enable that.

**Comment by Gedsh** [comment]
@Alexdiff Please specify your version. As mentioned above, the official f-droid build is currently broken.

> 5.1.0 is not working on xiaomi/ Poco.

If you mean non f-droid version please send me logs and details.

**Comment by Alexdiff** [comment]
F-Droid version is definitely broken, I switch to 1.2.3 and it's working great, my phone just getting hotter every hour so far.

**Comment by Gedsh** [comment]
The F-droid version is currently working, so I close the issue.
