### ISSUE TITLE
Firewall Does Not Display All Installed Apps

### ISSUE THREAD

**Issue by rhclayto** [Gedsh/InviZible#72]
Hi,

First, this is an excellent app! It changed the way I use my phone.

When I enable the firewall in InviZible, some of the apps installed on my phone are not shown. One example is OpenCamera, but there are several others. This is so in User apps, System apps, & All apps views. When I look in NetGuard, all of my installed apps are displayed.

**Comment by Gedsh** [comment]
Hi,

Thank you!

InviZible does not show applications that do not have permission to access the Internet and therefore cannot use the Internet.

**Comment by rhclayto** [comment]
Ah, I see. This makes sense. I did read in the NetGuard FAQ that they show apps without Internet permissions in order to block them pre-emptively, that is, in case an app without Internet permissions later gets an update that gives it Internet permissions, it will already be blocked. The apps without Internet permissions are dimmed. Something to consider.

**Comment by Gedsh** [comment]
> in case an app without Internet permissions later gets an update that gives it Internet permissions, it will already be blocked

In InviZible, all applications are blocked by default. So, if the Internet permission appears, in any case, this application will be blocked.

**Comment by rhclayto** [comment]
Beautiful, simple, exactly what I need!
