### ISSUE TITLE
[Feature Request] Add Option to Block All Requests When Tor or I2P Is Disabled

### ISSUE THREAD

**Issue by rhclayto** [Gedsh/InviZible#73]
I have InviZible set up in VPN mode, & in Android settings I have it enabled as an always-on VPN & to block connections without VPN. Sometimes I have found it necessary to disable Tor inside InviZible & re-enable it in order to get my connection working again (when the change circuit feature doesn't work). When I do this, I believe de-anonymized background connections can go out over the plain Internet. It would be useful to have an option (not on by default) to make InviZible block connections when Tor is disabled. For feature parity I2P should probably have the same option, although I haven't used I2P yet.

**Comment by Gedsh** [comment]
I cannot understand the purpose of your suggestion. If you don't want to use the internet, just turn it off. Why do you need to block all connections, and not just turn off the Internet?

**Comment by rhclayto** [comment]
Sometimes I have found that my connection times out when I have Tor enabled. In order to make it work again, I have found that disabling Tor & re-enabling it solves the problem.  I have tried disabling & re-enabling the Internet, as well as requesting a new Tor identity in InviZible, but only disabling then re-enabling Tor in InviZible seemed to work. Maybe there is a better way to solve this problem. But since this is the only way that has worked so far for me, I thought it might be useful to have the feature I requested, just to cover this corner case. I know this must not be a high priority, but it might be useful in some cases.

**Comment by Gedsh** [comment]
You can just start using Tor bridges. When Tor bridges are in use and you press the new Tor identity button, Tor performs a complete restart.

**Comment by Gedsh** [comment]
In any case, after turning on the screen, you should wait for Tor to establish a connection. This usually takes less than a minute.

**Comment by rhclayto** [comment]
Good suggestion, I will try that.

**Comment by Gedsh** [comment]
I do not see the point in this option, so I close the issue.
