### ISSUE TITLE
Firewall Documentation

### ISSUE THREAD

**Issue by rhclayto** [Gedsh/InviZible#75]
Hi,

Is there any documentation of the firewall in InviZible? Perhaps I missed it.

In my case, I am wondering about the meaning of the four toggle buttons for each application. My guess is LAN connection, Wi-Fi connection, mobile connection, & roaming mobile connection. Is this correct?

It might be worthwhile adding a wiki page for the firewall.

**Comment by Gedsh** [comment]
Hi,

> Is there any documentation of the firewall in InviZible? Perhaps I missed it.

Currently no. I will add.

> In my case, I am wondering about the meaning of the four toggle buttons for each application.

You can press and hold the buttons and you will see tooltips. Just try it.

> My guess is LAN connection, Wi-Fi connection, mobile connection, & roaming mobile connection. Is this correct?

You are right!

> It might be worthwhile adding a wiki page for the firewall.

I will add.

**Comment by Gedsh** [comment]
https://github.com/Gedsh/InviZible/wiki/Firewall
