### ISSUE TITLE
UDP Traffic

### ISSUE THREAD

**Issue by rhclayto** [Gedsh/InviZible#76]
On the wiki page for VPN Mode (https://github.com/Gedsh/InviZible/wiki/VPN-mode-(no-root-required)), there is this statement:

```
DNSCrypt and Tor are running (Route All traffic through Tor ON): InviZible encrypts 
DNS queries and sends them to the selected DNSCrypt server. All tcp internet traffic 
goes through Tor. You have access to onion sites from any browser. All other internet 
traffic is blocked. You can add applications to use them without Tor: 
MENU -> Fast Settings -> Exclude Applications.
```

I take 'All tcp internet traffic goes through Tor' & 'all other internet traffic is blocked' together to mean that all UDP traffic is blocked too. Or am I wrong?

I ask only to understand the workings of the app better. I am not having any problems that need to be rectified.

**Comment by Gedsh** [comment]
> I take 'All tcp internet traffic goes through Tor' & 'all other internet traffic is blocked' together to mean that all UDP traffic is blocked too.

You're right! UDP traffic cannot go through Tor, so it is blocked. If you select some applications that will not use Tor, UDP traffic for those applications will not be blocked.

> I ask only to understand the workings of the app better.

No problem. I'm here to help.

**Comment by rhclayto** [comment]
Thanks! So if InviZible is the Android VPN, & is configured to use Tor over VPN ( https://github.com/Gedsh/InviZible/wiki/Tor-over-VPN ) & pass certain applications' connections through to a proxy application (such as Shadowsocks), then any UDP for those applications will go to the proxy.
