### ISSUE TITLE
Problem Reaching .onion Sites

### ISSUE THREAD

**Issue by rhclayto** [Gedsh/InviZible#77]
Hi again,

This morning I was unable to resolve .onion sites. Last night everything was working fine. I looked in InviZible's DNS log, & saw that all the connections were yellow, & took the following form: App -> IP Address. Regular non-onion sites continued to resolve, but connecting to them all left yellow DNS log entries. The Tor project's Tor check page showed that my browser was being routed through Tor, so it seems it to be a DNS problem. GrapheneOS, InviZible from F-Droid, tried in two browsers: Bromite & Vanadium (both Chromium browsers).

To troubleshoot, I did the following in order:

1) Changed the Tor circuit in InviZible.
2) Stopped then started Tor in InviZible. Waited ten minutes before re-checking.
3) Stopped then started DNSCrypt in InviZible. I did this several times, checking after each time.
None of these steps solved the problem.
4) Switched InviZible from VPN mode to Proxy mode, then back to VPN mode. Everything began working correctly immediately after this.

Do you have any insight into why this might have happened? Also, when all the log entries are yellow, does that mean that potentially connections are bypassing DNSCrypt & going unencrypted to for instance the fallback DNS server?

**Comment by Gedsh** [comment]
> This morning I was unable to resolve .onion sites. Last night everything was working fine. I looked in InviZible's DNS log, & saw that all the connections were yellow

This usually means that Android does not use DNSCrypt or Tor DNS and therefore cannot resolve onion sites. You should check your Android settings to make sure you have disabled private DNS. And check your browser settings to make sure you are not using DNS encryption, proxies, etc.

> Also, when all the log entries are yellow, does that mean that potentially connections are bypassing DNSCrypt & going unencrypted to for instance the fallback DNS server?

Yellow means the application is not using InviZible for DNS resolution. This is normal, for example, for WatsApp or Telegram. They don't use plaintext DNS at all. But usually applications use plaintext DNS. It is impossible to know exactly which DNS was used on your system in your case, as I do not know the reason.

**Comment by rhclayto** [comment]
Hello, thank you again for your excellent support. Is there a way to donate to you?

Private DNS was set to Automatic. I disabled it last night, & this morning there were no problems. Maybe that was the cause.

By any chance, do you know of a source that lists common applications which don't use plaintext DNS? I would like to ensure that everything possible goes through DNSCrypt.

**Comment by Gedsh** [comment]
> Hello, thank you again for your excellent support.

Hello. Thank you!

> Is there a way to donate to you?

Sure! https://invizible.net/en/donate/

> Private DNS was set to Automatic. I disabled it last night, & this morning there were no problems. Maybe that was the cause.

It looks like it. Private DNS should be turned off. InviZible usually recommends this with a notification if it detects that Private DNS is not disabled.

> By any chance, do you know of a source that lists common applications which don't use plaintext DNS?

No. I have not seen such a list.

**Comment by rhclayto** [comment]
Thanks!
