### ISSUE TITLE
Logcat Shows Extra DNS Server

### ISSUE THREAD

**Issue by rhclayto** [Gedsh/InviZible#78]
When I run logcat on my device, & filter by `pan.alexander`, I get the following lines:

```log
2021-03-24 10:49:38.463 5633-29806/? I/pan.alexander.TPDCLogs: VPN DNS system= config=1.1.1.1,116.202.176.26
2021-03-24 10:49:38.463 5633-29806/? I/pan.alexander.TPDCLogs: VPN Using DNS=/1.1.1.1
2021-03-24 10:49:38.463 5633-29806/? I/pan.alexander.TPDCLogs: VPN Using DNS=/116.202.176.26
```

I have 1.1.1.1 configured as the `fallback_resolver` in DNSCrypt settings in InviZible. Where is 116.202.176.26 coming from? Is it built into InviZible? It seems to be the IP address of https://libredns.gr/ .

**Comment by Gedsh** [comment]
> Where is 116.202.176.26 coming from? Is it built into InviZible?

Yes. This is the second fallback resolver for Android VPN service. It is never used under normal circumstances.

**Comment by rhclayto** [comment]
I did see it a few times in the extended DNS leak test at https://www.dnsleaktest.com/  . I can't remember how I had InviZible configured when I saw those results. Under what conditions would the second fallback server be used?

**Comment by Gedsh** [comment]
> I did see it a few times in the extended DNS leak test at https://www.dnsleaktest.com/ . I can't remember how I had InviZible configured when I saw those results.

libredns-noads is used as one of the default DNSCrypt servers.

> Under what conditions would the second fallback server be used?

It sometimes can be used on some ROMs. It is usually not used. Better to enable Always On VPN and Block connections without VPN to definitely not use VPN service fallback resolvers.

**Comment by rhclayto** [comment]
Thank you, that is how I have it configured now.
