### ISSUE TITLE
.onion Sites Available to Excluded App

### ISSUE THREAD

**Issue by rhclayto** [Gedsh/InviZible#80]
Now for something truly mysterious to me.

I have InviZible configured as Tor over VPN. InviZible is an Always on/Block without VPN, is set to route all traffic through Tor with a few application exclusions, & is set in Common Settings to use a Socks5 proxy. Shadowsocks FOSS is running as a Socks5 proxy, which sends traffic to a Shadowsocks server. This is all working well.

I have two browsers, one configured to go through Tor, & the other to pass through to the Shadowsocks proxy. When I use the browser that goes through Tor, everything works as I would expect. The site https://check.torproject.org/ says I am using Tor, & .onion sites resolve as expected & are using Tor, I assume.

However, the Tor-excluded browser behaves strangely. https://check.torproject.org/ says that it is not using Tor, as expected, & IP check sites show the IP as that of the Shadowsocks server, but unexpectedly, .onion sites resolve & are served in that browser. For example, I can go to one of the Hidden Wikis & it works, & I can follow links on that page to any of the .onion sites listed. I have cleared all caches to make sure it's not an old cached version. How can this be? I know the DNSCrypt proxy has a forwarding rule for .onion TLDs, which sends DNS requests to Tor's DNSPort 5400. But for an excluded application, shouldn't this fail to work?

**Comment by Gedsh** [comment]
> 'Exclude Applications' disables that behavior for selected applications

Excluded apps will not use Tor for regular sites, but they can still use Tor for onion sites.

>  In logic terms, .onion site implies Tor, not Tor, therefore not .onion site (modus tollens).

Onion sites are not just sites, they are a hidden network. I see no reason not to allow access to them if Tor is already running.

> ust so I understand, is it correct to say that a browser I have added as an excluded application will not use Tor when requesting a regular TLD, but will use Tor when requesting an onion TLD?

It is correct.

**Comment by rhclayto** [comment]
Thanks for the explanation. I understand the way this works now.
