### ISSUE TITLE
Some apps doesn't appear on the exceptions list

### ISSUE THREAD

**Issue by stemy2** [Gedsh/InviZible#81]
Hello,

I installed the debug version of newpipe because the "stable" version is glitchy. To avoid these damn recaptchas, i wanted to add it as an exception, but it doesn't appears on the "apps to exclude" list. I have the stable version, but not the debug version. Why ?

**Comment by Gedsh** [comment]
InviZible does not show applications without INTERNET permission. Apps without this permission cannot use the internet connection.

Please send me the link for the version of newpipe you were using and I will check how the application have no INTERNET permission and use the Internet.

**Comment by stemy2** [comment]
Newpipe is aan alternative frontend for youtube, so it can't not have the internet permission.

Anyway, the direct link to the app: https://github.com/TeamNewPipe/NewPipe/files/6251337/app-debug.zip

**Comment by Gedsh** [comment]
![Firewall](https://user-images.githubusercontent.com/48843569/113518254-cac88b80-958d-11eb-8806-0b6f49ede3ee.png)

I cannot reproduce your issue.

**Comment by stemy2** [comment]
Well, the issue resolved itself, the app has finally appeared on the list.
