### ISSUE TITLE
Beta 1.2.6 - modules still often say starting even tho running

### ISSUE THREAD

**Issue by Yquas** [Gedsh/InviZible#83]
In the Changelog of Beta 1.2.6 it's said _Fixed modules(Tor, DNSCrypt, I2P) show starting, even if they are truly running._ But it still happens on my side, sadly. I don't really know why it happrns or what information I could provide, so right now I'm just telling you it seems not fixed yet.
(Maybe the problem is that I haven't rebooted my phone since the update to the supposably fixed version yet?)

**Comment by Gedsh** [comment]
In any case, the algorithm has changed when showing modules STARTING or RUNNING.

DNSCrypt changes state to RUNNING if you see "Server with lowest initial latency: ..." in the DNS tab.

Tor changes state to RUNNING if you see "Bootstrapped 100% (done)" in the TOR tab.

Purple I2P changes state to RUNNING if you see "Tunnel creation success rate:" greater than zero in the I2P tab.

So, if you see the above lines, but the corresponding modules still show STARTING, this is a bug. Please send me a screenshot.

**Comment by Yquas** [comment]
> In any case, the algorithm has changed when showing modules STARTING or RUNNING.
> 
> DNSCrypt changes state to RUNNING if you see "Server with lowest initial latency: ..." in the DNS tab.
> 
> Tor changes state to RUNNING if you see "Bootstrapped 100% (done)" in the TOR tab.
> 
> Purple I2P changes state to RUNNING if you see "Tunnel creation success rate:" greater than zero in the I2P tab.
> 
> So, if you see the above lines, but the corresponding modules still show STARTING, this is a bug. Please send me a screenshot.

Thanks for the quick response. I’m very sure this is happening. But then I must send you two screenshot per module, because it’s on different tabs.

**Comment by Yquas** [comment]
Now Tor is saying it’s starting although it was running for hours. But the problem is the log doesn’t have the Bootstrapped 100% because of the giant spam of the log from my issue #84 (which I couldn’t solve yet). Maybe that is the problem? The log lost the entry and so it shows it’s starting, not running.

**Comment by Gedsh** [comment]
>  But then I must send you two screenshot per module, because it’s on different tabs.

Two screenshots are ok.

> Now Tor is saying it’s starting although it was running for hours (that happened before too). But the problem is the log doesn’t have the Bootstrapped 100% because of the giant spam of the log from my issue #84

Please send me screenshots. In any case, Tor should not show STARTING if after the first startup, InviZible detects that Tor is RUNNING.

**Comment by Yquas** [comment]
After making a new Tor identity, Tor says it's starting, as always (since 1.2.6). But noe it stayed at starting for half an hour. But it was combined with a Tor Guard failing a lot and with my internet connection getting lost.. So probably that is not an issue. And the log doesn.t say Bootstrapped 100% anymore, again due to my issue with the Socks-HTPP spam.
So maybe this is just some issue that happens when such things are expected to happen? I don't really know..
But the internet connection still work, even tho it's saying starting. So that's wrong at least.

**Comment by Yquas** [comment]
But I guess that is the problem. You said Tor says running then the Tor tab says Bootstrapped 100%. And in all of my cases it doesn't, but it had said it before, before it was lost from the log.

**Comment by Gedsh** [comment]
> But noe it stayed at starting for half an hour. But it was combined with a Tor Guard failing a lot and with my internet connection getting lost.. So probably that is not an issue. And the log doesn.t say Bootstrapped 100% anymore, again due to my issue with the Socks-HTPP spam.

You have an unusual use case for InviZible with applications that spam in the Tor log. My algorithm cannot work correctly in such a situation. There is no easy solution on my part. But you can just change the Tor socks port. It will take you 5 seconds.

**Comment by Yquas** [comment]
I couldn't really reproduce this anymore. It was always fixed by goingto a different app and back to InviZible, then it said running again.
If someone has this issue too, feel free to comment here. But I'm closing it for now.
