### ISSUE TITLE
Firewall blocks anything except proxied apps

### ISSUE THREAD

**Issue by Yquas** [Gedsh/InviZible#85]
Since I use InviZible Pro, I sadly cannot productively use the firewall, which is a great feature in general, if it worked for me.
My problem: When I enable the firewall, even if the apps are allowed (even with all four options green) their internet access seems to get blocked. Nothing works. EXCEPT: Apps that have their app-internal Tor/Socks/HTTP Proxy setting on. These apps always do what they want, not getting blocked by any filter lists nor any firewall (without root) (I guess that’s an intended feature with Android). The Tor Browser is also an example.
But back to the topic: Why is this happening? Can it be fixed? I have to turn off the firewall for the non-proxied apps to work again, but then the apps I don’t want to give internet access to still have it (most practical for system apps which Stock Android doesn’t allow to take the network feature from). And It’s weird because I don’t think this is happening to other people, otherwise it would surely have been mentioned.

**Comment by Gedsh** [comment]
> When I enable the firewall, even if the apps are allowed (even with all four options green) their internet access seems to get blocked.

You may have blocked one of the system apps, which is required for all apps. Allow Internet access for all system applications and then block one by one to check which ones are necessary for the Internet to work properly.

> Apps that have their app-internal Tor/Socks/HTTP Proxy setting on. These apps always do what they want, not getting blocked by any filter lists nor any firewall (without root) (I guess that’s an intended feature with Android).

These apps cannot be blocked by a firewall because they do not use a VPN connection. This is not an Android feature, this is the basics of networking.

**Comment by Yquas** [comment]
> > When I enable the firewall, even if the apps are allowed (even with all four options green) their internet access seems to get blocked.
> 
> You may have blocked one of the system apps, which is required for all apps. Allow Internet access for all system applications and then block one by one to check which ones are necessary for the Internet to work properly.

Oh, ok! I’ll check that. Do you have any idea what it could be? I mean there’s almost 200 system app on my shitty phone.

> > Apps that have their app-internal Tor/Socks/HTTP Proxy setting on. These apps always do what they want, not getting blocked by any filter lists nor any firewall (without root) (I guess that’s an intended feature with Android).
> 
> These apps cannot be blocked by a firewall because they do not use a VPN connection. This is not an Android feature, this is the basics of networking.

Good to know, thanks.

**Comment by Gedsh** [comment]
> Do you have any idea what it could be?

This is usually DNS and/or NetworkStack and/or Root

**Comment by Yquas** [comment]
Ok, thanks a lot in advance now. Allowing all system apps and letting the firewall run truly fixes it. So I’ll test which system apps are needed later. And then I will tell you here what is needed, could be interesting for other people too.

**Comment by Yquas** [comment]
Wow, that was easy, XD! Allowing DNS (use the search, people) fixes all, with all other system apps disabled on all four connection kinds it still works, great! I’ll be looking if everything works this week with just this one system app enabled and I'll tell you then.

**Comment by Yquas** [comment]
For two weeks now, only allowing DNS from all the system apps solved my issue completely on my Xiaomi phone.
I also recommend allowing the Updater and the Downloads, MTP Storage and Media Storage system app (bundle). Some system apps and some user apps need it for downloading files.
