### ISSUE TITLE
Stopping firewall list always sliding back to top?

### ISSUE THREAD

**Issue by Yquas** [Gedsh/InviZible#87]
This is not very important, but I'd still like it to be implemented.
## **To reproduce:** 
1. Open the firewall tab in InviZible while the firewall is on.
2. Slide down in the app list a bit.
3. Go to another app or just go to your phones recent-apps-menu.
4. Go back to InviZible.
## **What happens:** 
The app immediately goes back to top of the app list, no matter where you had scrolled to before.
## **Expected result/feature request:** 
The app list should stay at the same place where it was before you went to another app or the recent-apps-menu and not go back to the top.

**Comment by Gedsh** [comment]
I will try to fix it.

**Comment by Gedsh** [comment]
Fixed. It will be available in the next beta.

**Comment by Yquas** [comment]
Wow, thanks for the quick fix! I'll close the issue when the beta is available for me and I can see it myself.

**Comment by Yquas** [comment]
It works well, thank you.
