### ISSUE TITLE
new feature: allow user to add their own host

### ISSUE THREAD

**Issue by NSTAdventure** [Gedsh/InviZible#89]
hey sup? i got idea

why you not add feature that will let user add their own host collection?

and did this app affect all apps even in work profile?

**Comment by Yquas** [comment]
`This issue already sort of exists at #53 and #41.`

**Comment by Gedsh** [comment]
> own host collection

And what is the purpose of this collection?

> did this app affect all apps even in work profile?

In Root mode, yes. In VPN mode, it depends on your ROM.

> This issue already sort of exists

May be. But this is not really clear.
