### ISSUE TITLE
Not executable: 64 bit ELF

### ISSUE THREAD

**Issue by stemy2** [Gedsh/InviZible#9]
Hello,

When i try to connect with any module, i get this error message.

**Comment by Gedsh** [comment]
Hello,
Please attach logs from InviZible: MENU -> Logs -> Save Logs, and screenshot. 
But in most cases this means you device firmware incompatible with modules binaries. Are you device has ARM processor? InviZible works only with ARM devices at the moment.

**Comment by stemy2** [comment]
Yes, i'm on ARM. The problem appeared after the update to 0.4.0. Until this, the app worked fine.

Sadly, the log is unreadable, there are plenty of seemingly random characters. I uploaded it here below, so you can see it by yourself.
[InvizibleLogs.txt](https://github.com/Gedsh/InviZible/files/3974067/InvizibleLogs.txt)

**Comment by Gedsh** [comment]
> The problem appeared after the update to 0.4.0.

Please try clean install.

>the log is unreadable

 This is zip. Just rename it.

**Comment by stemy2** [comment]
Okay. It would be more intuitive if it named itself with the zip extension and not txt.
[InvizibleLogs.zip](https://github.com/Gedsh/InviZible/files/3974376/InvizibleLogs.zip)

**Comment by Gedsh** [comment]
> Reinstallation fixed nothing.

Please try previous working version. But looks like the problem with firmware.

**Comment by stemy2** [comment]
I downgraded, but the error code is still there. This is very strange, it worked fine in the past, i don't understand why it doesn't anymore.

**Comment by Gedsh** [comment]
> i don't understand why it doesn't anymore

Something is changed. Perhaps firmware of your device is faulty, maybe you installed some program which is block InviZible.
