### ISSUE TITLE
Firewall, apps, dnscrypt

### ISSUE THREAD

**Issue by tommykarate** [Gedsh/InviZible#94]
I'm not sure if this is because I'm a noob or i can't find a setting but i have blocked google.com in dns blacklist, and I'm trying to use Newpipe which i figure will need to communicate with google at times, so i see Newpipe in the firewall app list and it's all green but when i look in the  dnscrypt logs while I'm trying to use it i don't see it at all trying to communicate online yet the app is timing out and won't connect. Same with Safechat. Showed up in the firewall and it's all green, but doesn't connect and doesn't show up in the logs. Also i have another app,  sms messenger and it doesn't even show up in the firewall app list nor in the dnscrypt logs. I'm not sure what is going on but when i turn off invizible they connect.

**Comment by Gedsh** [comment]
@tommykarate  So, first you need to decide - if you want to block Google, you will not be using Google services, including YouTube. Otherwise, you shouldn't block Google.

**Comment by tommykarate** [comment]
Thank you but I've blocked google before and YouTube itself worked fine, YouTube routes videos via YouTube, not google. I know it talks to google but it'll still work. But still doesn't answer my question why Safechat and newpipe doesn't connect at all and doesn't even show an attempt in the log and my sms app isn't showing up in the firewall app section at all. And if newpipe is attempting to talk to google it doesn't show up in the log. And actually i noticed everything seems blocked now when invizible is active with dnscrypt so i have to disable it to get online.

**Comment by Gedsh** [comment]
> But still doesn't answer my question

I cannot know how you configured InviZible, so I can only give advice on the default configuration. So, start by resetting your InviZible settings to their defaults.

> doesn't even show an attempt in the log 

This is only possible if you use in-app proxy settings or some other method to bypass the Android VPN service.

**Comment by tommykarate** [comment]
Resetting fixed the connections lol 
Thanks. Maybe i should just say what i want it to do and you can let me know if it's possible? I'm very simple. I just want to get online without google and facebook tracking or linking me to an account. If an app won't work because of this that's ok, I'll find an alternative. So simply i just want like a firewall to block certain sites from all my apps. I'm on e os, i just got it a few days ago. It's not rooted. Haven't gotten that far yet. I'm using a Samsung g965n s9 plus. If it's not possible, no problem. Thanks for your time.

**Comment by Gedsh** [comment]
>  I just want to get online without google and facebook tracking or linking me to an account.

Do you have google play services installed? Do you use any facebook apps?

**Comment by tommykarate** [comment]
No. I just got this eos, and haven't had time to look into rooting it, but it does have micro g, but i disabled it for now until i root it and delete it. Nothing from facebook at all.

**Comment by Gedsh** [comment]
@tommykarate So now you can import some nice blacklists. Something like that https://block.energized.pro/extensions/social/formats/domains.txt

You can select multiple blacklists for one-time import.
