### ISSUE TITLE
Using the custom or system dns resolver?

### ISSUE THREAD

**Issue by wafles38** [Gedsh/InviZible#95]
Hey, I wonder if there is a way for me to use the dns provided by my system? or to allow to use a custom dns.

I have a pihole dns that has dnssec and it's public ip rotates once a day. I would like to use this ip address instead of the tor's exit node or the ones provided by dns-crypt

**Comment by Gedsh** [comment]
> I have a pihole dns that has dnscrypt

You can add your DNSCrypt server if it has a public IP https://github.com/Gedsh/InviZible/wiki/Add-custom-DNSCrypt-server

> I would like to use this ip address instead of the tor's exit node

It's impossible.
