### ISSUE TITLE
reverse whilte/black list

### ISSUE THREAD

**Issue by xxjoe2** [Gedsh/InviZible#96]
hi

thanks for your work, it's more stable then orbot in my opinion and easy to manage both dnscrypt and tor

however i am facing a problem. any chance to create a reverse whilte/black list so that i can add only those apps i want to use tor like orbot?

thanks

**Comment by xxjoe2** [comment]
Menu -> Fast Settings -> Exclude Applications

Originally posted by @Gedsh in #96 (comment)

but that would be always on except app a b & c, with all the rests including system to go online via tor
i want to have included apps, so it would become "not always on" except app a b & c
ie only app a b and c will be go online via tor, others including system will be skipped and go online directly

**Comment by Gedsh** [comment]
@xxjoe2 Menu -> Fast Settings -> Route All traffic through Tor - disable
Menu -> Fast Settings -> Select Applications

**Comment by xxjoe2** [comment]
oh that will do the things properly? cool
let me try

thanks

**Comment by xxjoe2** [comment]
hi Gedsh

i have tested it for a few days and it's rock solid
however i have just found another problem

i have a wifi device which is connected to my router (with dnscrypt-proxy already), so i only turned on tor in invizible and leave dnscrypt uncheck. but i noticed that i have to switch on the dns option under tor or otherwise i wont have any dns service. how can i use my router as my default dns server as before since i need to resolve local address too? ie leaving the dns option under tor unchecked and use the system dns settings? note that this wifi device is not rooted so i cant setup iptables rules

thanks

**Comment by Gedsh** [comment]
> the only thing is i dont know why sometimes when i reopen the app it shows tor is not running, even though i have locked it and set it to not optimize in battery settings

It has to do with your phone battery optimization anyway. If InviZible crashes due to an internal error, the next time it starts, a message will be displayed asking you to send a crash report.

> how can i use my router as my default dns server

It is impossible with InviZible. If DNSCrypt is running, all applications use DNSCrypt DNS. If only Tor is running, all applications use Tor DNS. This is to prevent DNS leaks.

**Comment by xxjoe2** [comment]
> > how can i use my router as my default dns server
> 
> It is impossible with InviZible. If DNSCrypt is running, all applications use DNSCrypt DNS. If only Tor is running, all applications use Tor DNS. This is to prevent DNS leaks.


ok, i see. thanks a lot
