### ISSUE TITLE
[FEATURE REQUEST] DNS -> interactive black/white listing.

### ISSUE THREAD

**Issue by 0xlne** [Gedsh/InviZible#98]
As a user, I'd like to have the opportunity of cherrypicking hosts/IPs to add to local blacklists or whitelists, example, from the log window. It will be a more efficient way instead of manually copying & inserting entries to black/whitelists in the DNScrypt settings.
Maybe not the best implementation, but for the sake of an example, personalDNSFilter has this implemented:
https://github.com/IngoZenz/personaldnsfilter

**Comment by Gedsh** [comment]
I have planned to completely redo this log view, so I have no plans to improve it. Thanks for the suggestion.
